<?php
/**
 * @var $block \Magento\Bundle\Block\Adminhtml\Catalog\Product\Composite\Fieldset\Options\Type\Checkbox
 */ ?>
<?php $_option = $block->getOption(); ?>
<?php $_selections = $_option->getSelections(); ?>
<?php $_skipSaleableCheck = $this->helper(Magento\Catalog\Helper\Product::class)->getSkipSaleableCheck(); ?>

<div class="field admin__field checkbox-options options<?php if ($_option->getRequired()) { echo ' _required'; } ?>">
    <label class="label admin__field-label">
        <span><?= $block->escapeHtml($_option->getTitle()) ?></span>
    </label>

    <div class="control admin__field-control">
        <div class="nested <?php if ($_option->getDecoratedIsLast()) :?> last<?php endif;?>">

            <?php if (count($_selections) == 1 && $_option->getRequired()) : ?>
                <?= /* @noEscape */ $block->getSelectionQtyTitlePrice($_selections[0]) ?>
                <input type="hidden"
                       class="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>  product bundle option"
                       name="bundle_option[<?= $block->escapeHtmlAttr($_option->getId()) ?>]"
                       value="<?= $block->escapeHtmlAttr($_selections[0]->getSelectionId()) ?>"
                       price="<?= $block->escapeHtmlAttr($block->getSelectionPrice($_selections[0])) ?>" />
                <?php if ($selectionBlock = $block->getChildBlock('product.info.bundle.option.checkbox.selection')): ?>
                    <?php /* @escapeNotVerified */ echo $selectionBlock->setOption($_option)->setSelection($_selections[0])->toHtml(); ?>
                <?php endif; ?>
            <?php else :?>

                <?php foreach ($_selections as $_selection) : ?>
                    <div class="field choice admin__field admin__field-option">
                        <input
                            class="change-container-classname admin__control-checkbox checkbox bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?> <?php if ($_option->getRequired()) { echo 'validate-one-required-by-name'; } ?>"
                            id="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>-<?= $block->escapeHtmlAttr($_selection->getSelectionId()) ?>"
                            type="checkbox"
                            name="bundle_option[<?= $block->escapeHtmlAttr($_option->getId()) ?>][<?= $block->escapeHtmlAttr($_selection->getId()) ?>]"
                            <?php if ($block->isSelected($_selection)) :?>
                                <?= ' checked="checked"' ?>
                            <?php endif;?>
                            <?php if (!$_selection->isSaleable() && !$_skipSaleableCheck) :?>
                                <?= ' disabled="disabled"' ?>
                            <?php endif;?>
                            value="<?= $block->escapeHtmlAttr($_selection->getSelectionId()) ?>"
                            price="<?= $block->escapeHtmlAttr($block->getSelectionPrice($_selection)) ?>"
                            <?php if ($_option->getRequired()) echo 'data-validate="{\'validate-one-required-by-name\':\'input[name^=&quot;bundle_option[' . $_option->getId() . ']&quot;]:checked\'}"'?>/>

                        <label class="admin__field-label"
                               for="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>-<?= $block->escapeHtmlAttr($_selection->getSelectionId()) ?>">
                            <span><?= /* @noEscape */ $block->getSelectionQtyTitlePrice($_selection) ?></span>
                        </label>

                        <?php if ($_option->getRequired()) : ?>
                            <?= /* @noEscape */ $block->setValidationContainer('bundle-option-' . $_option->getId() . '-' . $_selection->getSelectionId(), 'bundle-option-' . $_option->getId() . '-container') ?>
                        <?php endif;?>
                    </div>
                    <div class="admin-selection" <?= $block->isSelected($_selection) ? '' : ' style="display: none;"' ?>>
                        <?php if ($selectionBlock = $block->getChildBlock('product.info.bundle.option.checkbox.selection')): ?>
                            <?php /* @escapeNotVerified */ echo $selectionBlock->setOption($_option)->setSelection($_selection)->toHtml(); ?>
                        <?php endif; ?>
                    </div>
                <?php endforeach; ?>

                <div id="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>-container"></div>
            <?php endif; ?>
        </div>
    </div>
</div>

<script>
require([
    'jquery'
], function($){

    var checkboxOptions = {
        init: function () {
            this.checkOptions();
            this.bind();
        },

        bind: function () {
            var self = this;
            $('#catalog_product_composite_configure_fields_bundle .checkbox-options [type="checkbox"]').off().on('change', function () {
                self.checkOptions();
            });
        },

        checkOptions: function() {
            var options = $('#catalog_product_composite_configure_fields_bundle  .checkbox-options').find('[type="checkbox"]'),
                requiredClass = "<?= $_option->getRequired() ? 'required-entry' : ''?>";

            options.each(function () {
                if ($(this).is(':checked')) {
                    $(this).parent().find('+ .admin-selection').show();
                    $(this).parent().find('+ .admin-selection [data-rule-required]').addClass(requiredClass);
                } else {
                    $(this).parent().find('+ .admin-selection').hide();
                    $(this).parent().find('+ .admin-selection [data-rule-required]').removeClass(requiredClass);
                }
            });
        }
    };

    checkboxOptions.init();
});
</script>
