<?php
/**
 * @var $block \Magento\Bundle\Block\Adminhtml\Catalog\Product\Composite\Fieldset\Options\Type\Radio
 */
?>
<?php $_option = $block->getOption(); ?>
<?php $_selections = $_option->getSelections(); ?>
<?php $_default = $_option->getDefaultSelection(); ?>
<?php $_skipSaleableCheck = $this->helper(Magento\Catalog\Helper\Product::class)->getSkipSaleableCheck(); ?>
<?php list($_defaultQty, $_canChangeQty) = $block->getDefaultValues(); ?>
<?php $_qtyDisabledClass = ' qty-disabled'; ?>

<div class="field admin__field radio-options options<?php if ($_option->getRequired()) {
    echo ' _required';
} ?> ">
    <label class="label admin__field-label"><span><?= $block->escapeHtml($_option->getTitle()) ?></span></label>
    <div class="control admin__field-control">
        <div class="nested<?php if ($_option->getDecoratedIsLast()) : ?> last<?php endif; ?>">
            <?php if ($block->showSingle()) : ?>
                <?= /* @noEscape */ $block->getSelectionTitlePrice($_selections[0]) ?>
                <input type="hidden"
                       name="bundle_option[<?= $block->escapeHtmlAttr($_option->getId()) ?>]"
                       value="<?= $block->escapeHtmlAttr($_selections[0]->getSelectionId()) ?>"
                       price="<?= $block->escapeHtmlAttr($block->getSelectionPrice($_selections[0])) ?>"/>
                <?php if ($selectionBlock = $block->getChildBlock('product.info.bundle.option.radio.selection')): ?>
                    <?php /* @escapeNotVerified */ echo $selectionBlock->setOption($_option)->setSelection($_selections[0])->toHtml(); ?>
                <?php endif; ?>
            <?php else : ?>
                <?php if (!$_option->getRequired()) : ?>
                    <div class="field choice admin__field admin__field-option">
                        <input type="radio"
                               class="radio admin__control-radio"
                               id="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>"
                               name="bundle_option[<?= $block->escapeHtmlAttr($_option->getId()) ?>]"<?= ($_default && $_default->isSalable()) ? '' : ' checked="checked" ' ?>
                               value="" />
                        <label class="admin__field-label"
                               for="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>"><span><?= $block->escapeHtml(__('None')) ?></span></label>
                    </div>
                <?php endif; ?>

                <?php foreach ($_selections as $_selection) : ?>
                    <div class="field choice admin__field admin__field-option">
                        <input type="radio"
                               class="radio admin__control-radio <?= $_option->getRequired() ? ' required-entry' : '' ?> change-container-classname"
                               id="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>-<?= $block->escapeHtmlAttr($_selection->getSelectionId()) ?>"
                               name="bundle_option[<?= $block->escapeHtmlAttr($_option->getId()) ?>]"
                            <?php if ($block->isSelected($_selection)) { echo ' checked="checked"'; } ?>
                            <?php if (!$_selection->isSaleable() && !$_skipSaleableCheck) { echo ' disabled="disabled"'; } ?>
                               data-default-qty="<?= intval($_selection->getSelectionQty())?>"
                               data-can-change-qty="<?= intval($_selection->getSelectionCanChangeQty()) ?>"
                               value="<?= $block->escapeHtmlAttr($_selection->getSelectionId()) ?>"
                               price="<?= $block->escapeHtmlAttr($block->getSelectionPrice($_selection)) ?>"
                               qtyId="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>-qty-input"/>
                        <label class="admin__field-label"
                               for="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>-<?= $block->escapeHtmlAttr($_selection->getSelectionId()) ?>">
                            <span><?= /* @noEscape */ $block->getSelectionTitlePrice($_selection) ?></span>
                        </label>
                        <?php if ($_option->getRequired()) : ?>
                            <?= /* @noEscape */ $block->setValidationContainer('bundle-option-' . $_option->getId() . '-' . $_selection->getSelectionId(), 'bundle-option-' . $_option->getId() . '-container') ?>
                        <?php endif; ?>
                    </div>

                    <div class="admin-selection type-configurable" style="display: none;">
                        <?php if ($selectionBlock = $block->getChildBlock('product.info.bundle.option.radio.selection')): ?>
                            <?php /* @escapeNotVerified */ echo $selectionBlock->setOption($_option)->setSelection($_selection)->toHtml(); ?>
                        <?php endif; ?>
                    </div>
                <?php endforeach; ?>
                <div id="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>-container"></div>
            <?php endif; ?>
            <div class="field admin__field qty">
                <label class="label admin__field-label"for="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>-qty-input">
                    <span><?= $block->escapeHtml(__('Quantity:')) ?></span>
                </label>
                <div class="control admin__field-control"><input <?php if (!$_canChangeQty) {echo ' disabled="disabled"';} ?>
                        id="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>-qty-input"
                        class="input-text admin__control-text qty validate-greater-than-zero<?php if (!$_canChangeQty) { echo $_qtyDisabledClass; } ?>"
                        type="text"
                        name="bundle_option_qty[<?= $block->escapeHtmlAttr($_option->getId()) ?>]"
                        value="<?= $block->escapeHtmlAttr($_defaultQty) ?>"/>
                </div>
            </div>
        </div>
    </div>
</div>

<script>

require([
    'jquery'
], function($){
    var radioOptions = {
        init: function () {
            this.checkOptions();
            this.bind();
        },

        bind: function () {
            var self = this;
            $('#catalog_product_composite_configure_fields_bundle .radio-options [type="radio"]').off().on('change', function () {
                self.checkOptions();
            });
        },

        checkOptions: function() {
            var options = $('#catalog_product_composite_configure_fields_bundle  .radio-options').find('[type="radio"]'),
                requiredClass = "<?= $_option->getRequired() ? 'required-entry' : ''; ?>",
                inputQty,
                qty,
                canChangeQty;

            options.each(function () {
                if ($(this).is(':checked')) {
                    qty = $(this).data('default-qty');
                    canChangeQty = $(this).data('can-change-qty');
                    inputQty = $(this).closest('.nested').find('input.qty');

                    $(this).parent().find('+ .admin-selection').show();
                    $(this).parent().find('+ .admin-selection [data-rule-required]').addClass(requiredClass);
                    inputQty.val(qty);
                    inputQty.attr('disabled', !canChangeQty);

                    if (canChangeQty) {
                        inputQty.removeClass('<?= $_qtyDisabledClass ?>').addClass('required-entry');
                    } else {
                        inputQty.addClass('<?= $_qtyDisabledClass ?>').removeClass('required-entry mage-error');
                    }

                } else {
                    $(this).parent().find('+ .admin-selection').hide();
                    $(this).parent().find('+ .admin-selection [data-rule-required]').removeClass(requiredClass);
                }
            });
        }
    };

    radioOptions.init();
});
</script>
