<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_SellerSubAccount
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
/** @var $block \Webkul\Marketplace\Block\Account\Becomeseller */
?>
<div>
    <div class="fieldset">
        <div class="wk_emptymsg"><h2><?= /* @noEscape */ __('Your account is disable by Seller') ?></h2></div>
    </div>
</div>
