<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_SellerSubAccount
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$helper = $block->getLayout()->createBlock(
    \Webkul\SellerSubAccount\Block\SubAccount::class
)->getSubAccountHelper();
$isPartner = $block->getLayout()->createBlock(
    \Webkul\SellerSubAccount\Block\SubAccount::class
)->getMarketplaceHelperInstance()->isSeller();
$displayAll = $block->getConfig('general/region/display_all');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$eavConfig = $objectManager->create(\Magento\Eav\Model\Config::class);
$attribute = $eavConfig->getAttribute('customer', 'gender');
$options = $attribute->getSource()->getAllOptions();
$dobMandatory = $helper->dobMandatory();
$genderMandatory = $helper->genderMandatory();
$tempblock = $block->getLayout()->createBlock(
    \Magento\Customer\Block\Form\Register::class
);
$formData = $tempblock->getFormData();
$addressHelper = $tempblock->getData('addressHelper');
$directoryHelper = $block->getData('directoryHelper');
?>

<?php if ($isPartner == 1): ?>
    <?php
    $allowedPermissions = [];
    $allPermissionTypes = $helper->getAllPermissionTypes();
    $id = (int)$block->getRequest()->getParam('id');
    $customerData = $helper->getCustomerModelById(0);
    $address=null;
    if (!empty($id)) {
        $subAccountData = $helper->getSubAccountById($id);
        if (!empty($subAccountData['permission_type'])) {
            $allowedPermissions = explode(',', $subAccountData['permission_type']);
        }
        $customerData = $helper->getCustomerById($subAccountData->getCustomerId());
        if ($customerData->getAddresses()) {
            foreach ($customerData->getAddresses() as $ad) {
                $address=$ad;
            }
        }
        $firstname = $customerData->getFirstname();
        $lastname = $customerData->getLastname();
        $email = $customerData->getEmail();
        $customerDob = $customerData->getDob();
        $customerGender = $customerData->getGender();

        $status = $subAccountData->getStatus();
    } else {
        $firstname = '';
        $lastname = '';
        $email = '';
        $status = 0;
        $customerDob='';
        $customerGender='';
    }
    /*
    *get permission allowed by admin
    */
    $getSellerPermissionForSubSellerByAdmin = $helper->getSellerPermissionForSubSellerByAdmin();
    ?>
    <input type="hidden" id="defaultdob" value="<?=$block->escapeHtmlAttr($customerDob); ?>"/>
    <input type="hidden" id="defaultgender" value="<?=$block->escapeHtmlAttr($customerGender); ?>">
    <form action="<?=$block->escapeUrl($block->getUrl('sellersubaccount/account/save')); ?>"
    enctype="multipart/form-data" method="post" id="form-sub-account" data-mage-init='{"validation":{}}'>
        <div class="fieldset wk-ui-component-container">
            <?= $block->getBlockHtml('formkey') ?>
            <?= $block->getBlockHtml('seller.formkey') ?>
            <input type="hidden" name="id" value="<?=$block->escapeHtmlAttr($id);?>"/>
            <div class="page-main-actions">
                <div class="page-actions-placeholder"></div>
                <div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
                    <div class="page-actions-inner" data-title="<?=$block->escapeHtmlAttr(__("New Sub Account")); ?>">
                        <!-- for save sub button -->
                            <div class="page-actions-buttons">
                                <button id="save" title="<?=$block->escapeHtmlAttr(__("Save Sub Account")); ?>"
                                type="submit" class="action- scalable save primary ui-button ui-widget
                                ui-state-default ui-corner-all ui-button-text-only"
                                data-form-role="save" data-ui-id="save-button"
                                role="button" aria-disabled="false">
                                    <span class="ui-button-text">
                                        <span><?=$block->escapeHtml(__("Save Sub Account")); ?></span>
                                    </span>
                                </button>
                            </div>
                        <!-- for reset button -->
                        <div class="page-actions-buttons">
                            <button id="reset" title="<?=$block->escapeHtmlAttr(__("Reset")); ?>"
                            type="reset" class="action- scalable reset" data-ui-id="reset-button" >
                                <span><?=$block->escapeHtml(__("Reset")); ?></span>
                            </button>
                        </div>
                        <!-- for back button -->
                        <div class="page-actions-buttons">
                          <button id="back" title="<?=$block->escapeHtmlAttr(__("Back")); ?>"
                          type="button" class="action- scalable back" onclick="javascript: window.history.back();"
                          data-ui-id="back-button">
                              <span><?=$block->escapeHtml(__("Back")); ?></span>
                          </button>
                        </div>
                    </div>
                </div>
            </div>
            <?= $block->getLayout()
                ->createBlock(\Magento\Customer\Block\Widget\Name::class)
                ->setObject($customerData)
                ->setForceUseCustomerAttributes(true)
                ->toHtml() ?>

            <?php if ($dobMandatory): ?>
                <div class="field required">
                    <label for="dob" class="label">
                        <span><?=$block->escapeHtml(__("Date Of Birth")); ?></span>
                    </label>
                    <div class="control">
                        <input type="text" class="input-text required-entry" id="dob" style="width: auto"
                        name="dob" data-validate="{required:true}" />
                    </div>
                </div>
            <?php endif ?>
            <?php $_gender = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Gender::class) ?>
            <?php if ($_gender->isEnabled() && $genderMandatory): ?>
                <?=$_gender->setGender($tempblock->getFormData()->getGender())->toHtml(); ?>
            <?php endif ?>

            <?php $_taxvat = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Taxvat::class) ?>
            <?php if ($_taxvat->isEnabled()): ?>
                <?= $_taxvat->setTaxvat($customerData->getTaxvat())->toHtml() ?>
            <?php endif ?>
            <?php $_company = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Company::class) ?>
            <?php $_telephone = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Telephone::class) ?>
            <?php $_fax = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Fax::class) ?>               
            <?php if ($_company->isEnabled() || $_telephone->isEnabled() || $_fax->isEnabled()): ?>
            <?php endif; ?>
            <?php if (false && $helper->isReqAddressEnable()): ?>
                    <?php $cityValidationClass = $addressHelper->getAttributeValidationClass('city'); ?>
                    <?php $postcodeValidationClass = $addressHelper->getAttributeValidationClass('postcode'); ?>
                    <?php $regionValidationClass = $addressHelper->getAttributeValidationClass('region'); ?>
                    <fieldset class="fieldset address">
                        <legend class="legend">
                        <span><?= $escaper->escapeHtml(__('Address Information')) ?></span></legend><br>
                        <input type="hidden" name="create_address" value="1" />
                        <?php $_company = $block->getLayout()
                                                ->createBlock(\Magento\Customer\Block\Widget\Company::class) ?>
                        <?php if ($_company->isEnabled()): ?>
                            <?php  if (($address)): ?>
                                 <?= $_company->setCompany($address->getCompany())->toHtml() ?>
                            <?php else:?>
                                <?= $_company->setCompany($formData->getCompany())->toHtml() ?>
                            <?php endif; ?>
                        <?php endif ?>
                        <?php if ($_telephone->isEnabled()): ?>
                            <?php  if (($address)): ?>
                                <?= $_telephone->setTelephone($address->getTelephone())->toHtml() ?>
                            <?php else:?>
                                <?= $_telephone->setTelephone($formData->getTelephone())->toHtml() ?>
                            <?php endif;?>
                        <?php endif ?>
                        <?php if ($_fax->isEnabled()): ?>
                            <?php  if (($address)): ?>
                                <?= $_fax->setFax($address->getFax())->toHtml() ?>
                            <?php else:?>
                                <?= $_fax->setFax($formData->getFax())->toHtml() ?>
                            <?php endif;?>
                        <?php endif ?>
                        <?php
                            $streetValClass = $addressHelper->getAttributeValidationClass('street');
                        ?>
                        <?php
                            $frontendStreetLabel = $block->getAttributeData()->getFrontendLabel('street');
                        ?>
                        <div class="field street required">
                            <label for="street_1" class="label">
                                <span><?= /* @noEscape */ $frontendStreetLabel ?></span>
                            </label>
                            <div class="control">
                            <?php  if (($address)): ?>
                                <input type="text"
                                    name="street[]"
                                    value="<?= $escaper->escapeHtmlAttr($address->getStreet()[0]) ?>"
                                    title="<?= /* @noEscape */ $frontendStreetLabel ?>"
                                    id="street_1"
                                    class="input-text <?= $escaper->escapeHtmlAttr($streetValClass) ?>">
                            <?php else:?>
                                <input type="text"
                                    name="street[]"
                                    value="<?= $escaper->escapeHtmlAttr($formData->getStreet(0)) ?>"
                                    title="<?= /* @noEscape */ $frontendStreetLabel ?>"
                                    id="street_1"
                                    class="input-text <?= $escaper->escapeHtmlAttr($streetValClass) ?>">
                            <?php endif;?>

                                <div class="nested">
                                    <?php
                                        $streetValClass =
                                            trim(str_replace('required-entry', '', $streetValClass));
                                        $streetLines = $addressHelper->getStreetLines();
                                    ?>
                                    <?php for ($_i = 2, $_n = $streetLines; $_i <= $_n; $_i++): ?>
                                        <div class="field additional">
                                            <label class="label" for="street_<?= /* @noEscape */ $_i ?>">
                                                <span><?= $escaper->escapeHtml(__('Address')) ?></span>
                                            </label>
                                            <div class="control">
                                                <?php  if (($address)):
                                                        $addStreet = $address->getStreet();
                                                    ?>
                                                    <?php $st1=isset($addStreet[$_i - 1])?$addStreet[$_i - 1]:'';?>
                                                <?php else:?>
                                                    <?php $st1=$formData->getStreetLine($_i - 1);?>
                                                <?php endif;?>
                                                <input type="text"
                                                    name="street[]"
                                                    value="<?= $escaper->escapeHtml($st1) ?>"
                                                    title=
                                                        "<?= $escaper->escapeHtmlAttr(__('Street Address %1', $_i)) ?>"
                                                    id="street_<?= /* @noEscape */ $_i ?>"
                                                    class=
                                                        "input-text <?= $escaper->escapeHtmlAttr($streetValClass) ?>">
                                            </div>
                                        </div>
                                    <?php endfor; ?>
                                </div>
                            </div>
                        </div>

                        <div class="field country required">
                            <label for="country" class="label">
                                <span>
                                    <?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('country_id') ?>
                                </span>
                            </label>
                            <div class="control">
                            <?php  if (($address)): ?>
                                <?= $block->getCountryHtmlSelect($address->getCountryId()) ?>
                                <?php else:?>
                                    <?= $block->getCountryHtmlSelect() ?>
                                <?php endif;?>
                            </div>
                        </div>
                        <?php  if (($address)): ?>
                            <?php $region=$address->getRegion()->getRegionId(); ?>
                        <?php else:?>
                            <?php $region=$block->getRegion(); ?>
                        <?php endif;?>
                        <?php
                            $frontendRegionLabel = $block->getAttributeData()->getFrontendLabel('region');
                        ?>
                        <div class="field region required">
                            <label for="region_id" class="label">
                                <span><?= /* @noEscape */ $frontendRegionLabel ?></span>
                            </label>
                            <div class="control">
                                <select id="region_id"
                                        name="region_id"
                                        title="<?= /* @noEscape */ $frontendRegionLabel ?>"
                                        class="validate-select region_id" value="<?= $escaper->escapeHtml($region) ?>">
                                    <option value="">
                                        <?= $escaper->escapeHtml(__('Please select a region, state or province.')) ?>
                                      
                                    </option>
                                </select>
                                <?= /* @noEscape */ $secureRenderer
                                                        ->renderStyleAsTag("display: none;", 'select#region_id') ?>

                                <input type="text"
                                    id="region"
                                    name="region"
                                    value="<?= $escaper->escapeHtml($region) ?>"
                                    title="<?= /* @noEscape */ $frontendRegionLabel ?>"
                                    class="input-text <?= $escaper->escapeHtmlAttr($regionValidationClass) ?>">
                                <?= /* @noEscape */ $secureRenderer
                                                        ->renderStyleAsTag("display: none;", 'input#region') ?>
                            </div>
                        </div>

                        <div class="field required">
                            <label for="city" class="label">
                                <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?></span>
                            </label>
                            <div class="control">
                             
                            <?php  if (($address)): ?>
                                    <?php $city=$address->getCity(); ?>
                                <?php else:?>
                                    <?php $city=$block->getCity(); ?>
                            <?php endif;?>
                                <input type="text"
                                    name="city"
                                    value="<?= $escaper->escapeHtmlAttr($city) ?>"
                                    title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?>"
                                    class="input-text <?= $escaper->escapeHtmlAttr($cityValidationClass) ?>"
                                    id="city">
                            </div>
                        </div>
                        <?php
                            $frontendPostcodeLabel = $block->getAttributeData()->getFrontendLabel('postcode');
                        ?>
                        <div class="field zip required">
                            <label for="zip" class="label">
                                <span><?= /* @noEscape */ $frontendPostcodeLabel ?></span>
                            </label>
                            <div class="control">
                            <?php  if (($address)): ?>
                                    <?php $postcode=$address->getPostcode(); ?>
                                <?php else:?>
                                    <?php $postcode=$block->getPostcode(); ?>
                            <?php endif;?>
                                <input type="text"
                                    name="postcode"
                                    value="<?= $escaper->escapeHtmlAttr($postcode) ?>"
                                    title="<?= /* @noEscape */ $frontendPostcodeLabel ?>"
                                    id="zip"
                                    class="input-text validate-zip-international
                                        <?= $escaper->escapeHtmlAttr($postcodeValidationClass) ?>">
                            </div>
                        </div>

                        <?php $addressAttributes = $block->getChildBlock('customer_form_address_user_attributes');?>
                        <?php if ($addressAttributes): ?>
                            <?php $addressAttributes->setEntityType('customer_address'); ?>
                            <?php $addressAttributes
                                    ->setFieldIdFormat('address:%1$s')
                                    ->setFieldNameFormat('address[%1$s]');
                            ?>
                            <?php $block->restoreSessionData($addressAttributes->getMetadataForm(), 'address');?>
                            <?= $addressAttributes->setShowContainer(false)->toHtml() ?>
                        <?php endif;?>
                        <input type="hidden" name="default_billing" value="1">
                        <input type="hidden" name="default_shipping" value="1">
                    </fieldset>
            <?php endif; ?>
                    
<script>
  require([
    'jquery',
    'mage/translate',
    'mage/calendar'
    ], function ($, $t) {
      $("#dob").val($("#defaultdob").val());
      $("#gender").val($("#defaultgender").val());
      $("#reset").on("click",function(e){ e.preventDefault();location.reload();});

      $('#dob').calendar({
        changeMonth: true,
        changeYear: true,
        showButtonPanel: true,
        currentText: $t('Go Today'),
        closeText: $t('Close'),
        showWeek: true,
        showsTime: false,
        dateFormat: "M/d/Y",
        yearRange: "-120y:c+nn",
        buttonText: "Select Date", maxDate: "-1d", changeMonth: true, changeYear: true, showOn: "both"

      });
    })


</script>

            <div class="field required">
                <label for="email" class="label">
                    <span><?=$block->escapeHtml(__("Email")); ?></span>
                </label>
                <div class="control">
                    <input type="text" class="input-text required-entry validate-email" name="email"
                    data-validate="{required:true}" title="<?=$block->escapeHtmlAttr(__("Email")); ?>"
                    id="email" value="<?=$block->escapeHtml($email) ?>">
                </div>
            </div>
            <div class="field required">
                <label for="permission_type" class="label">
                    <span><?=$block->escapeHtml(__("Allowed Permissions")); ?></span>
                </label>
                <?php if (($getSellerPermissionForSubSellerByAdmin[0])=="") {?>
                    <label for="permission_type" class="wk-label-for-permission">
                    <span><?=$block->escapeHtml(__("Admin didn't select any
                    permission to seller sub account")); ?></span>
                    </label>
                <?php } else { ?>
                <div class="control">
                    <select data-validate="{'validate-select':true}"
                    title="<?=$block->escapeHtmlAttr(__("Allowed Permissions")); ?>"
                    id="permission_type" name="permission_type[]"
                    class="required-entry select multiselect admin__control-multiselect"
                    size="<?=$block->escapeHtmlAttr(count($allPermissionTypes));?>" data-ui-id="select-permission-type"
                    multiple="multiple">
                        <?php
                        foreach ($allPermissionTypes as $value => $label):
                            foreach ($getSellerPermissionForSubSellerByAdmin as $value1):
                                if ($value == $value1):
                                    ?>
                                        <option value="<?=$block->escapeHtmlAttr($value); ?>"
                                        <?php if (in_array($value, $allowedPermissions)): ?>selected<?php endif; ?>>
                                        <?=$block->escapeHtml($label); ?></option>
                                    <?php
                                    endif;
                                endforeach;
                            endforeach;
                        ?>
                    </select>
                </div>
                <?php } ?>
            </div>
            <div class="field required">
                <label for="account_status" class="label">
                    <span><?=$block->escapeHtml(__("Active")); ?></span>
                </label>
                <div class="control">
                    <select data-validate="{'validate-select':true}" title="<?=$block->escapeHtmlAttr(__("Active"));
                    ?>" id="account_status" name="status" class="required-entry" data-ui-id="select-status">
                        <option value="1" <?php if ($status == 1): ?>selected<?php
                         endif; ?>><?=$block->escapeHtml(__('Yes')); ?></option>
                        <option value="0" <?php if ($status == 0): ?>selected<?php
                        endif; ?>><?=$block->escapeHtml(__('No')); ?></option>
                    </select>
                </div>
            </div>
        </div>
    </form>
    <div class="buttons-set">
        <p class="back-link">
            <a href="javascript:;" onclick="javascript: window.history.back();"
            class="left">&laquo; <?=$block->escapeHtml(__('Back'));?></a>
        </p>
    </div>
<?php else: ?>
    <h2 class="wk-mp-error-msg">
        <?=$block->escapeHtml(__("To Become Seller Please Contact to Admin.")); ?>
    </h2>
<?php endif; ?>
<?php if ($block->getShowAddressFields()): ?>
    <?php
    $regionJson = /* @noEscape */ $directoryHelper->getRegionJson();
    if (($address)):
        $regionId=$address->getRegion()->getRegionId();
     else:
         $regionId = (int) $formData->getRegionId();
    endif;
     $countriesWithOptionalZip = /* @noEscape */ $directoryHelper->getCountriesWithOptionalZip(true);
        ?>
<script type="text/x-magento-init">
    {
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */ $displayAll ? 'true' : 'false' ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "currentRegion":<?= /* @noEscape */ $regionId; ?>,
                "form": "#form-validate",
                "regionJson":  <?= /* @noEscape */ $regionJson; ?>,
                "defaultRegion": <?= /* @noEscape */ $regionId; ?>,
                "countriesWithOptionalZip": <?= /* @noEscape */ $countriesWithOptionalZip; ?>
            }
        }
    }
</script>
<?php endif; ?>