<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>

<div class="block <?= $escaper->escapeHtmlAttr($block->getBlockCss()) ?>  bg-ahy-bg filter-option mb-6"
     x-data="{ open: true }">
    <div class="title border-t-4 pt-4 border-ahy-blue <?= $escaper->escapeHtmlAttr($block->getBlockCss()) ?>-title flex justify-between
        items-center cursor-pointer hover:text-secondary-darker"
         @click="open = !open"
    >
        <span class="text-lg title">
            <?= $escaper->escapeHtml(__('Menu')) ?>
        </span>
    </div>
    <div class="content <?= $escaper->escapeHtmlAttr($block->getBlockCss()) ?>-content pt-3 block"
         :class="{ 'hidden': !open , 'block': open }"
         id="<?= $escaper->escapeHtmlAttr($block->getBlockCss()) ?>">
        <?= $block->getChildHtml() ?>
    </div>
</div>
