<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Hyva\Theme\ViewModel\Navigation;
use Magento\Cms\Block\Block as CmsBlock;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var Navigation $viewModelNavigation */
$viewModelNavigation = $viewModels->require(Navigation::class);

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

// Order is important here: 1. build the menu data, 2. then set the cache tags from the view model identities
$menuItems = $viewModelNavigation->getNavigation(4);
$block->setData('cache_tags', $viewModelNavigation->getIdentities());

?>
<div class="z-20 order-2 sm:order-1 lg:order-2 navigation"
     x-data="initHeaderNavigation()"
>
    <!-- mobile -->
    <div x-ref="nav-mobile"
         @load.window="setActiveMenuMobile($refs['nav-mobile'])"
         class="bg-container-lighter lg:hidden"
         :class="{'min-h-screen fixed top-0 left-0 w-full' : open}"
         @toggle-mobile-menu.window="open = !open"
         @keydown.window.escape="open=false"
    >
        <div class="flex justify-between items-baseline menu-icon">
            <div class="flex justify-end w-full">
                <a @click="$dispatch('toggle-mobile-menu')"
                       class="flex justify-center items-center cursor-pointer"
                       :class="{ 'ml-auto': open }">
                    <svg class="hidden p-4 w-16 h-16 fill-current"
                         :class="{ 'hidden' : !open, 'block': open }"
                         xmlns="http://www.w3.org/2000/svg" width="20" height="20"
                         viewBox="0 0 20 20">
                        <path fill-rule="evenodd" clip-rule="evenodd"
                              d="M18.278 16.864a1 1 0 0 1-1.414 1.414l-4.829-4.828-4.828 4.828a1 1 0 0
                          1-1.414-1.414l4.828-4.829-4.828-4.828a1 1 0 0 1 1.414-1.414l4.829 4.828
                          4.828-4.828a1 1 0 1 1 1.414 1.414l-4.828 4.829 4.828 4.828z">
                        </path>
                    </svg>
                    <svg class="block p-3 w-12 h-12 fill-current"
                         :class="{ 'hidden' : open, 'block': !open }"
                         xmlns="http://www.w3.org/2000/svg" width="20" height="20"
                         viewBox="0 0 20 20">
                        <path
                              d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z">
                        </path>
                    </svg>
                </a>
            </div>
        </div>

        <nav
            class="hidden w-full border-t duration-150 ease-in-out transform transition-display border-container"
            :class="{ 'hidden' : !open }"
        >
        <?php foreach ($menuItems as $index => $menuItem): ?>
            <div class="level-0">
                <span
                    class="flex items-center transition-transform duration-150 ease-in-out transform"
                    :class="{
                        '-translate-x-full' : mobilePanelActiveId,
                        'translate-x-0' : !mobilePanelActiveId
                    }"
                >
                    <a class="flex items-center w-full px-8 py-4 border-b cursor-pointer
                        bg-container-lighter border-container hover:bg-container-darker hover:underline level-0"
                       href="<?= $escaper->escapeUrl($menuItem['url']) ?>"
                       title="<?= $escaper->escapeHtmlAttr($menuItem['name']) ?>">
                        <?= $escaper->escapeHtml($menuItem['name']) ?>
                    </a>
                    <?php if (!empty($menuItem['childData'])): ?>
                    <a class="absolute right-0 flex w-8 h-8 mr-8 border rounded cursor-pointer
                        bg-container-lighter border-container hover:bg-container hover:border-container"
                          @click="mobilePanelActiveId =
                          mobilePanelActiveId === '<?= /* @noEscape */ (string) $index ?>' ?
                           0 : '<?= /* @noEscape */ (string) $index ?>'"
                    >
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" height="24" width="24"
                             stroke="currentColor"
                             class="p-1 w-full h-full"
                        >
                          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/>
                        </svg>
                    </a>
                    <?php endif; ?>
                </span>
                <?php if (!empty($menuItem['childData'])): ?>
                    <div
                        class="absolute top-0 right-0 z-10 w-full h-full transition-transform duration-200 ease-in-out
                            translate-x-full transform bg-container-lighter"
                        :class="{
                            'translate-x-full' : mobilePanelActiveId !== '<?= /* @noEscape */ (string) $index ?>',
                            'translate-x-0' : mobilePanelActiveId === '<?= /* @noEscape */ (string) $index ?>',
                        }"
                    >
                        <a class="flex items-center py-4 px-8 border-b cursor-pointer bg-container border-container"
                              @click="mobilePanelActiveId = 0"
                        >
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" height="24"
                                 width="24"
                                 stroke="currentColor">
                              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M15 19l-7-7 7-7"/>
                            </svg>
                            <span class="ml-4">
                                <?= $escaper->escapeHtml($menuItem['name']) ?>
                            </span>
                        </a>
                        <a href="<?= $escaper->escapeUrl($menuItem['url']) ?>" title="<?= $escaper->escapeHtmlAttr($menuItem['name']) ?>"
                           class="flex items-center w-full px-8 py-4 border-b cursor-pointer
                            bg-container-lighter border-container hover:bg-container-darker hover:underline"
                        >
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none"
                                 viewBox="0 0 24 24" height="24"
                                 width="24"></svg>
                            <span class="ml-4"><?= $escaper->escapeHtml(__('View All')) ?></span></a>
                        <?php foreach ($menuItem['childData'] as $subMenuItem): ?>

                            <a href="<?= $escaper->escapeUrl($subMenuItem['url']) ?>"
                               title="<?= $escaper->escapeHtmlAttr($subMenuItem['name']) ?>"
                               class="flex items-center w-full px-8 py-4 border-b cursor-pointer
                                bg-container-lighter border-container hover:bg-container-darker hover:underline"
                            >
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none"
                                     viewBox="0 0 24 24" height="24"
                                     width="24"></svg>
                                <span class="ml-4 text-base text-gray-700 lg:ml-0">
                                    <?= $escaper->escapeHtml($subMenuItem['name']) ?>
                                </span>
                            </a>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
        </nav>
    </div>

    <!-- desktop -->
    <div x-ref="nav-desktop"
         @load.window="setActiveMenuDesktop($refs['nav-desktop'])"
         class="hidden justify-between items-center mx-auto w-full max-w-7xl lg:flex">
        <nav
            class="flex flex-wrap"
        >
                <?php foreach ($menuItems as $index => $itemLevel1): ?>
                    <?php $singleItems = []; ?>
                    <div class="level-0 flex items-center p-1 mx-1 border-b-2 border-transparent transition transition-colors duration-500 group xl:p-2 xl:mx-2 hover:border-primary focus-within:border-primary"
                         @mouseover.stop="hoverTopPosition = $event.currentTarget.offsetTop + $event.currentTarget.getBoundingClientRect().height"
                    >
                        <a href="<?= $escaper->escapeUrl($itemLevel1['url']) ?>"
                           @focus="hoverTopPosition = $event.currentTarget.parentNode.offsetTop + $event.currentTarget.parentNode.getBoundingClientRect().height"
                           title="<?= $escaper->escapeHtmlAttr($itemLevel1['name']) ?>"
                           class="level-0 block p-2 text-base text-gray-700 whitespace-nowrap">
                            <span><?= $escaper->escapeHtml($itemLevel1['name']) ?></span>
                            <?php if (!empty($itemLevel1['childData'])): ?>
                            <span class="inline items-center">
                                <?= $heroiconsSolid->chevronDownHtml('w-5 h-5 inline', 25, 25) ?>
                            </span>
                            <?php endif; ?>
                        </a>
                        <?php if (!empty($itemLevel1['childData'])): ?>
                            <div class="absolute left-0 top-full z-10 -mt-3 w-full bg-white opacity-0 transition-opacity ease-out pointer-events-none group-hover:opacity-100 focus-within:opacity-100 group-hover:pointer-events-auto"
                                 :style="`margin-top: 0; top: ${hoverTopPosition}px;`"
                            >
                                <div class="flex justify-between mt-4 mb-8">
                                    <?php
                                    $catIdLvl1    = ($pos = strrpos($itemLevel1['id'], '-')) !== false
                                        ? substr($itemLevel1['id'], $pos + 1)
                                        : 0;
                                    $cmsBlockHtml = $catIdLvl1
                                        ? $this->getLayout()
                                               ->createBlock(CmsBlock::class)
                                               ->setBlockId('megamenu_block_left_cat' . $catIdLvl1)
                                               ->toHtml()
                                        : '';

                                    if (! empty($cmsBlockHtml)): ?>
                                        <div class="max-w-xs 2xl:block">
                                            <?= /** @noEscape */ $cmsBlockHtml ?>
                                        </div>
                                    <?php endif; ?>
                                    <div class="mx-auto">
                                        <ul class="grid flex-1 grid-cols-4 gap-y-4 gap-x-8 p-4">
                                            <?php foreach ($itemLevel1['childData'] as $itemLevel2): ?>
                                                <?php if (empty($itemLevel2['childData'])): ?>
                                                    <?php $singleItems[] = $itemLevel2 ?>
                                                    <?php continue; ?>
                                                <?php endif; ?>
                                                <li class="level-1 min-w-48">
                                                    <a href="<?= $escaper->escapeUrl($itemLevel2['url']) ?>"
                                                       title="<?= $escaper->escapeHtmlAttr($itemLevel2['name']) ?>"
                                                       class="level-1 p-1 block text-base font-semibold leading-loose hover:underline">
                                                        <?= $escaper->escapeHtml($itemLevel2['name']) ?>
                                                    </a>

                                                    <ul class="z-10 w-full">
                                                        <?php foreach ($itemLevel2['childData'] as $itemLevel3): ?>
                                                            <li class="level-2">
                                                                <a href="<?= $escaper->escapeUrl($itemLevel3['url']) ?>"
                                                                   title="<?= $escaper->escapeHtmlAttr($itemLevel3['name']) ?>"
                                                                   class="level-2 p-1 block text-lg md:text-sm hover:underline"><?= $escaper->escapeHtml($itemLevel3['name']) ?></a>
                                                            </li>
                                                        <?php endforeach; ?>
                                                    </ul>

                                                </li>
                                            <?php endforeach; ?>
                                            <?php if ($singleItems): ?>
                                                <li class="level-1 min-w-48">
                                                    <?php foreach ($singleItems as $item): ?>
                                                        <a href="<?= $escaper->escapeUrl($item['url']) ?>"
                                                           title="<?= $escaper->escapeHtmlAttr($item['name']) ?>"
                                                           class="level-1 p-1 block text-base font-semibold leading-loose hover:underline">
                                                            <?= $escaper->escapeHtml($item['name']) ?>
                                                        </a>
                                                    <?php endforeach; ?>
                                            <?php endif; ?>
                                        </ul>
                                    </div>
                                    <?php
                                    $cmsBlockHtml = $catIdLvl1
                                        ? $this->getLayout()
                                               ->createBlock(CmsBlock::class)
                                               ->setBlockId('megamenu_block_right_cat' . $catIdLvl1)
                                               ->toHtml()
                                        : '';

                                    if (! empty($cmsBlockHtml)): ?>
                                        <div class="max-w-xs 2xl:block">
                                            <?= /** @noEscape */ $cmsBlockHtml ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        <?php endif; ?>
                    </div>
                <?php endforeach; ?>

        </nav>
    </div>
</div>
<script>
    'use strict';

    const initHeaderNavigation = () => {
        return {
            mobilePanelActiveId: null,
            hoverPanelActiveId: null,
            open: false,
            hoverTopPosition: '100%',
            setActiveMenuMobile(menuNode) {
                Array.from(menuNode.querySelectorAll('a')).filter(link => {
                    return link.href === window.location.href.split('?')[0];
                }).map(item => {
                    item.classList.add('underline');
                    item.closest('div.level-0') &&
                    item.closest('div.level-0').querySelector('a.level-0').classList.add('underline');
                });
            },
            setActiveMenuDesktop(menuNode) {
                Array.from(menuNode.querySelectorAll('a')).filter(link => {
                    return link.href === window.location.href.split('?')[0];
                }).map(item => {
                    if (!item.classList.contains('level-0')) {
                        item.classList.add('underline');
                    }
                    item.closest('div.level-0') &&
                    item.closest('div.level-0').classList.add('border-secondary');
                });
            }
        }
    }
</script>
