<section class="creator-program-page">
    <div class="md:text-center sm:text-left pt-10  md:pt-24 md:pb-12 xl:pb-12 xl:pt-24">
        <h1 class="text-[92px] leading-[0.9]  sm:text-8xl md:text-[120px] lg:text-[160px] xl:text-[210px] uppercase font-league-gothic text-ahy-blue">
            CREATOR PROGRAM
        </h1>
        <p class="sm:text-2xl text-xs md:text-3xl !leading-normal font-extrabold uppercase text-ahy-blue">BUILD YOUR OUTDOOR BRAND & GET REWARDED</p>
        <a target="_blank" href="https://share.hsforms.com/1V9RU2MA-RNmmN6iF6n4WXw4ri79"><button class="w-full bg-ahy-red text-white font-bold py-4 text-white rounded-full md:w-60 mt-10 hover:bg-ahy-red-light">Sign Up</button></a>
    </div>

    <div x-data="scrollSmoothOnClick()" id="tab_wrapper" class="py-8">
        <div class="tab-bg-line-desktop relative pb-4 flex justify-center">
            <div class="text-ahy-blue tab-bg-mobile relative flex border-b-2 border-white sm:px-4 px-2 w-[100%] md:w-[400px] justify-center sm:pl-6 md:pl-12 md:pr-8">
                <button @click.prevent="scrollToHowItWorks()" class="mx-2 sm:mx-4  h-16 text-xs sm:text-sm flex items-center font-medium hover:underline underline-offset-6">
                    How it works
                </button>

                <button @click.prevent="scrollToThePerks()" class="mx-2 sm:mx-4  h-16 text-xs sm:text-sm flex items-center font-medium hover:underline underline-offset-6">
                    The Perks
                </button>

                <button @click.prevent="scrollToFaq()" class="mx-2 sm:mx-4  h-16 text-xs sm:text-sm flex items-center font-medium hover:underline underline-offset-6">
                    FAQs
                </button>
            </div>
        </div>
    </div>

    <div class="w-full md:w-[65%] mx-auto">
        <p class="sm:text-2xl text-xl md:text-4xl !leading-loose font-light md:text-center text-left text-ahy-blue">We are looking for creators who love the hunting, fishing, shooting sports, backpacking, hiking, ski, and well-all outdoors!</p>
    </div>

    <div id="howitworks" class="lg:mt-14">
        <div class="py-9  mx-auto">
            <h2 class="text-3xl md:text-5xl !leading-normal font-extrabold uppercase text-ahy-blue text-center">How it works</h2>
            <div class="flex flex-col md:flex-row md:mt-16 mt-10">
                <div class="w-full  text-center flex items-center flex-col ">
                    <img class="rounded-full h-[90px]" src="/media/creator_program/sign-up-icon.png" alt="Sign Up Icon">
                    <p class="font-extrabold uppercase text-ahy-blue py-5">Sign Up</p>
                    <p class="text-center font-light text-ahy-blue text-sm md:text-lg w-[80%]">Sign up with your email and social info on this page. Look out for an email confirming from our team and welcome Everest gift goodies!</p>
                </div>
                <div class="w-full  text-center flex items-center flex-col pt-10 md:pt-0">
                    <img class="rounded-full  h-[90px] " src="/media/creator_program/post-icon.png" alt="Post On Social Icon">
                    <p class="font-extrabold uppercase text-ahy-blue py-5">Post on social</p>
                    <p class="text-center font-light text-ahy-blue text-sm md:text-lg w-[80%]">We value authentic connections and your creativity - so we like to keep things simple. Just share your outdoor passion wearing your Everest swag. It would be even sweeter if you could mention our community cause partners. Make sure to tag us at <a class="hover:underline underline-offset-6" href="https://www.instagram.com/_everest_com/">@_everest_com</a></p>
                </div>
                <div class="w-full  text-center flex items-center flex-col pt-10 md:pt-0">
                    <img class="rounded-full  h-[90px]" src="/media/creator_program/reward-icon.png" alt="Get Rewarded Icom">
                    <p class="font-extrabold uppercase text-ahy-blue py-5">Get REWARDED</p>
                    <p class="text-center font-light text-ahy-blue text-sm md:text-lg w-[80%]">We pack our program rewards with commissions and coupon codes, the chance to get free products, and we work with you to grow your following and brand.</p>
                </div>
            </div>
        </div>
    </div>

    <div class="lg:my-24">
        <div class="py-5 md:py-9  mx-auto  lg:w-[80%]">
            <div class="flex md:flex-row flex-col">
                <div class="lg:w-1/2 flex flex-col justify-center mt-7 md:mt-0">
                    <h2 class="font-extrabold text-ahy-red uppercase text-xs md:text-xl  text-center md:text-left">Coming Soon:</h2>
                    <p class="font-extrabold uppercase text-ahy-blue md:text-5xl md:w-[90%] w-full  text-2xl text-center md:text-left">Creator Storefronts</p>
                    <p class="text-ahy-blue font-light py-5 text-sm text-center md:text-left md:text-3xl md:w-[90%] w-full">
                        We are launching creator storefronts so that you can showcase the products you love and create new bridges to building brand.
                    </p>
                </div>
                <div class="lg:w-1/2 flex items-center order-first md:order-last"><img class=" hover:bg-ahy-red-light rounded-xl shadow-2xl" src="/media/creator_program/creator-storefront.jpg" alt="Creator Store Front"></div>
            </div>
        </div>
    </div>
    
    <div class="md:py-10 py-2" id="the-perks">
        <div class="py-9  mx-auto text-center">
            <h2 class="text-3xl md:text-5xl !leading-normal font-extrabold uppercase text-ahy-blue text-center">The Perks</h2>
            <div class="flex flex-col md:flex-row mt-16">
                <div class="w-full  text-center flex items-center flex-col ">
                    <img class="rounded-full h-[90px]" src="/media/creator_program/welcome-icon.png" alt="Welcome Icon">
                    <p class="font-extrabold uppercase text-ahy-blue py-5">welcome Package</p>
                    <p class="text-center font-light text-ahy-blue text-sm md:text-lg w-[75%]">We send our creator community members a welcome gift swag set.</p>
                </div>
                <div class="w-full  text-center flex items-center flex-col pt-10 md:pt-0">
                    <img class="rounded-full  h-[90px] " src="/media/creator_program/earn-icon.png" alt="Earn Icon">
                    <p class="font-extrabold uppercase text-ahy-blue py-5">Earn</p>
                    <p class="text-center font-light text-ahy-blue text-sm md:text-lg w-[75%]">Earn 3% to 8% commission back on every sale on every purchase that uses your code. Plus, get a 10% coupon code for your followers.</p>
                </div>
                <div class="w-full  text-center flex items-center flex-col pt-10 md:pt-0">
                    <img class="rounded-full  h-[90px]" src="/media/creator_program/grow-icon.png" alt="Grow Icom">
                    <p class="font-extrabold uppercase text-ahy-blue py-5">grow brand</p>
                    <p class="text-center font-light text-ahy-blue text-sm md:text-lg w-[75%]">From unique branded giveaways that build engagement to storefronts, we will work with you to build your brand.</p>
                </div>
            </div>
            <div class="py-4">
                <a target="_blank" href="https://share.hsforms.com/1V9RU2MA-RNmmN6iF6n4WXw4ri79"><button class="hover:bg-ahy-red-light w-[90%] bg-ahy-red text-white font-bold py-4 text-white rounded-full md:w-60 mt-10">Sign Up</button></a>
            </div>
        </div>
    </div>

    <div>
        <div class="py-9  mx-auto text-center md:w-[80%]">
            <h2 class="text-3xl md:text-5xl !leading-normal font-extrabold uppercase text-ahy-blue text-center mb-10 md:mb-14">Community Post</h2>
            <div class="flex h-[350px] lg:h-[500px] xl:h-[700px] 2xl:h-[900px] community-post">
                <div class="align-start flex px-2 md:px-5 parent-class-community-post">
                    <img class="rounded-2xl shadow-2xl community-post-image" src="/media/creator_program/bethany-image.jpg" alt="Community Post">
                </div>
                <div class="justify-end items-end flex px-2 md:px-5">
                <img class="rounded-2xl shadow-2xl" src="/media/creator_program/al-image.jpg" alt="Community Post">
                </div>
            </div>
        </div>
    </div>
    <div class="md:my-20" id="faqs">
        <div class="py-9  mx-auto text-center md:w-[80%]">
            <h2 class="text-3xl md:text-5xl !leading-normal font-extrabold uppercase text-ahy-blue text-center mb-10 md:mb-14">faqs</h2>
            <p class="font-extrabold text-ahy-blue uppercase text-xl">What platform can i get Rewarded on?</p>
            <p class="font-light text-ahy-blue mt-5 text-md leading-normal">We are currently building communities on Instagram, Youtube, and Facebook.
            We are expanding into other platforms shortly.
            </p>
            <p class="font-extrabold text-ahy-blue uppercase text-xl mt-12">How do I get paid?</p>
            <p class="font-light text-ahy-blue mt-5 text-md md:w-[70%] mx-auto leading-normal">To become an Everest Creator you need to have a Paypal account. Paypal is a free online payment system that allows you to send and receive money securely. To create an account visit paypal.com and provide your personal information. Once you have created your account, you can link it to your bank account or credit card to send and receive money. </p>
            <p class="font-extrabold text-ahy-blue uppercase text-xl mt-12">are there additional rules, terms, and condition</p>
            <p class="font-light text-ahy-blue mt-5 text-md w-[80%] mx-auto">Posts must made from accounts that are public.</p>
            <p class="font-light text-ahy-blue mt-5 text-md w-[80%] mx-auto">Post must visibly display <a class="hover:underline underline-offset-6" href="https://www.instagram.com/_everest_com/">@_everest_com.</a></p>
            <p class="font-light text-ahy-blue mt-5 text-md w-[80%] mx-auto">Creators must be 21 years old or older.</p>
            <p class="font-light text-ahy-blue mt-5 text-md w-[80%] mx-auto">Everest may use creator member photos for marketing purposes.</p>
            <p class="font-light text-ahy-blue mt-5 text-md w-[80%] mx-auto">Everest may update the rewards program at anytime.</p>
        </div>
    </div>
    <div class="md:my-20">
        <div class="py-9  mx-auto text-center md:w-[60%]">
        <h2 class="text-4xl md:text-6xl !leading-none font-extrabold uppercase text-ahy-blue text-center mb-10 md:mb-14">let's help the community find their everest</h2>
        <a target="_blank" href="https://share.hsforms.com/1V9RU2MA-RNmmN6iF6n4WXw4ri79"><button class="hover:bg-ahy-red-light w-[90%] bg-ahy-red text-white font-bold py-4 text-white rounded-full md:w-60 ">Sign Up</button></a>
        </div>
    </div>
</section>

<style type="text/css">
    @media screen and (min-width:320px) and (max-width:420px) {
        .community-post{
            height: 200px !important;
        }
    }
    @media screen and (min-width:420px) and (max-width:450px) {
        .community-post{
            height: 300px !important;
        }
    }
    .parent-class-community-post picture{
        height: 0 !important;
    }
</style>
<script>
    function scrollSmoothOnClick() {
        return {
            scrollToHowItWorks() {
                const conservationEl = document.getElementById("howitworks");
                if (conservationEl) {
                    conservationEl.scrollIntoView({
                        behavior: "smooth",
                    });
                }
            },
            scrollToThePerks() {
                const howYouGiveEl = document.getElementById("the-perks");
                if (howYouGiveEl) {
                    howYouGiveEl.scrollIntoView({
                        behavior: "smooth",
                    });
                }
            },
            scrollToFaq() {
                const partnersEl = document.getElementById("faqs");
                if (partnersEl) {
                    partnersEl.scrollIntoView({
                        behavior: "smooth",
                    });
                }
            },
        };
    }

</script>