<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Paypal\Block\Express\InContext\Minicart\SmartButton;

/** @var SmartButton $block */
/** @var Escaper $escaper */

$widgetData = json_decode($block->getJsInitParams(), true);
$widgetJson = json_encode($widgetData['Magento_Paypal/js/in-context/button']);
$uniqueId   = '_' . uniqid();
if (
    empty($widgetData['Magento_Paypal/js/in-context/button']) ||
    empty($widgetData['Magento_Paypal/js/in-context/button']['clientConfig'])
) {
    return;
}

?>
<section class="pt-6 pb-0 md:pb-6">
    <div class="py-4 text-center font-semibold text-ahy-blue">
        Express Checkout
    </div>
    <div x-data="initPayPalInContextButton<?= $escaper->escapeHtmlAttr($uniqueId) ?>" x-init="function() {
            refs = $refs;
            console.log('initPayPalInContextButton');
            const bodyElement = document.body;
            // Check if the 'catalog-product-view' class is present
            this.isClassPresent = bodyElement.classList.contains('checkout-cart-index');
            // Check the result
            if (!this.isClassPresent) {
                console.log('initPayPalInContextButton function');
                this.initializeButtons();
            }
        }"
        id="buttonContainer-<?= $escaper->escapeHtmlAttr($uniqueId) ?>"
        x-ref="buttonContainer-<?= $escaper->escapeHtmlAttr($uniqueId) ?>"
        @private-content-loaded.window="getSectionData($event.detail.data);"
        class="paypal checkout h-16 paypal-logo paypal-express-in-context-mini-cart-container z-0 relative">
    </div>
    <div class="flex flex-row gap-4 items-center py-6">
        <div class="w-[47%]"><hr class="border border-ahy-blue"></div>
        <div class="text-center">OR</div>
        <div class="w-[47%]"><hr class="border border-ahy-blue"></div>
    </div>
</section>

<script>
    function initPayPalInContextButton<?= $escaper->escapeHtmlAttr($uniqueId) ?>() {
        return {
            refs: false,
            clientConfig: <?= /** @noEscape */ $widgetJson ?>.clientConfig || {},
            customerSection: {},
            cartSection: false,
            actions: {},
            isClassPresent:false,
            getSectionData(sectionData) {
                console.log('initialize section data');
                if (sectionData.customer) {
                    this.customerSection = sectionData.customer;
                }
                if (sectionData.cart) {
                    this.cartSection = sectionData.cart;
                }
                if (this.cartSection.items && this.cartSection.items.length) {
                    // todo: check if allowed by verifying logged in and isGuestCheckoutAllowed = true
                    this.initializeButtons();
                }
            },
            initializeButtons() {
                // Get the <body> element
                const bodyElement = document.body;
                var element = null;
                // Check if the 'catalog-product-view' class is present
                if (!this.isClassPresent) {
                    element = document.getElementById('buttonContainer-<?= $escaper->escapeHtmlAttr($uniqueId) ?>');
                } else {
                    element = this.refs['buttonContainer-<?= $escaper->escapeJs($uniqueId) ?>'];
                }
                const clientConfig = this.clientConfig;
                const updatedStyles = Object.assign({}, clientConfig.styles, {
                    "disableMaxWidth": "true"
                });

                // Now updatedStyles includes the "disableMaxWidth" key-value pair
                // console.log(updatedStyles);
                const loadPayPalScriptPromise = this.createScriptLoadPromise(clientConfig.sdkUrl);

                Promise.all(loadPayPalScriptPromise).then(() => {
                    const paypal = window.paypal;
                    const getCookie = this.getCookie;

                    paypal && paypal.Buttons({
                        style: updatedStyles,

                        /**
                         * onInit is called when the button first renders
                         * @param {Object} data
                         * @param {Object} actions
                         */
                        onInit(data, actions) {
                            this.actions = actions || this.actions;
                        },

                        /**
                         * Triggers beforePayment action on PayPal buttons
                         * @returns {Object} jQuery promise
                         */
                        createOrder() {
                            const params = "quote_id="+clientConfig.quoteId +
                                "&customer_id=" + ( clientConfig.customerId ?
                                    clientConfig.customerId :
                                    ''
                                ) +
                                "&form_key=" + (getCookie('form_key') || '') +
                                "&button=" + clientConfig.button;

                            return window.fetch(clientConfig.getTokenUrl, {
                                "headers": {
                                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                                },
                                "body": params,
                                "method": "POST",
                                "mode": "cors",
                                "credentials": "include"
                            })
                                .then(result => result.json())
                                .then(data => data.token)
                                .catch((error)=>console.log(error));

                        },

                        /**
                         * Triggers beforeOnAuthorize action on PayPal buttons
                         * @param {Object} data
                         * @param {Object} actions
                         */
                        onApprove(data, actions) {
                            const params = "paymentToken=" + (data.orderID || '') +
                                "&payerId=" + (data.payerID || '') +
                                "&quoteId=" + (clientConfig.quoteId || '') +
                                "&customerId=" + (clientConfig.customerId || '') +
                                "&form_key=" + (getCookie('form_key') || '');

                            return window.fetch(clientConfig.onAuthorizeUrl, {
                                "headers": {
                                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                                },
                                "body": params,
                                "method": "POST",
                                "mode": "cors",
                                "credentials": "include"
                            })
                                .then(data => {
                                    return data.json()
                                }).then(response => {
                                    if (response.success) {
                                        return actions.redirect(response.redirectUrl);
                                    }

                                    throw new Error(response['error_message']);
                                })
                                .catch((error)=>console.log(error)).finally(()=>{
                                    const reloadCustomerDataEvent = new CustomEvent("reload-customer-section-data");
                                    window.dispatchEvent(reloadCustomerDataEvent);
                                });
                        },

                        /**
                         * Execute logic on Paypal button click
                         */
                        onClick() {

                            paypal.actions = this.actions;
                            //clientConfig.rendererComponent.validate();
                            //clientConfig.rendererComponent.onClick();
                        },

                        /**
                         * Process cancel action
                         * @param {Object} data
                         * @param {Object} actions
                         */
                        onCancel(data, actions) {
                            //clientConfig.rendererComponent.onCancel(data, actions);

                        },

                        /**
                         * Process errors
                         *
                         * @param {Error} err
                         */
                        onError(err) {
                            //clientConfig.rendererComponent.onError(err);

                        }
                    }).render(element);
                });
            },
            createScriptLoadPromise(url) {
                const promises = [];

                promises.push(new Promise(function(resolve, reject) {
                    const script = document.createElement('script');
                    script.src = url;

                    script.addEventListener('load', function() {
                        resolve(script);
                    }, false);

                    script.addEventListener('error', function(event) {
                        reject(script);
                        console.log('The PayPal script could not be loaded', event);
                    }, false);

                    document.body.appendChild(script);
                }));

                return promises;
            },
            getCookie(name) {
                const v = document.cookie.match('(^|;) ?' + name + '=([^;]*)(;|$)');
                return v ? v[2] : null;
            }
        }
    }
</script>
<style>
    .buttons-container {
        display: flex;
        justify-content: center;
    }
    iframe.paypal-button-container {
        max-width: 100% !important;
    }
</style>