<?php 
/** @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Checkbox */ 
?>
<?php $_option = $block->getOption() ?>
<?php $_selections = $_option->getSelections() ?>
<?php
    $default = $_option->getDefaultSelection();
    $optionId = $_option->getId();
?>
<?php $isEnableImages = $this->helper('Ewave\ExtendedBundleProduct\Helper\Data')->showImages(); ?>
<div class="field option <?php echo ($_option->getRequired()) ? ' required': ''; ?>">
    <div class="control">
        <div class="nested options-list" x-bind="eventListeners" >
            <?php if ($block->showSingle()): ?>
                <?php if ($isEnableImages): ?>
                    <?php $imageUrl = $this->helper('Magento\Catalog\Helper\Image')->init($_selections[0], 'product_thumbnail_image')->getUrl(); ?>
                    <div class="bundle-item -image">
                        <div class="content">
                            <?php /* @escapeNotVerified */ echo $block->getSelectionQtyTitlePrice($_selections[0]) ?>
                            <?php if ($tierPriceBlock = $block->getTierPriceRenderer()): ?>
                                <?= /* @noEscape */ $tierPriceBlock->renderTierPrice($_selections[0]) ?>
                            <?php endif; ?>
                            <input type="hidden"
                                   class="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>  product bundle option"
                                   name="bundle_option[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                                   id="bundle-option-<?php echo (int)$_option->getId() ?>-<?php echo (int)$_selections[0]->getSelectionId() ?>"
                                   value="<?php /* @escapeNotVerified */ echo $_selections[0]->getSelectionId() ?>"/>
                        </div>
                        <div class="image">
                            <img data-image="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-<?php /* @escapeNotVerified */ echo $_selections[0]->getSelectionId() ?>" class="img" src="<?php echo $block->escapeUrl($imageUrl); ?>" alt="<?php echo $block->escapeHtml($_selections[0]->getName()) ?>">
                        </div>
                    </div>
                <?php else:?>
                    <?php /* @escapeNotVerified */ echo $block->getSelectionQtyTitlePrice($_selections[0]) ?>
                    <?php if ($tierPriceBlock = $block->getTierPriceRenderer()): ?>
                        <?= /* @noEscape */ $tierPriceBlock->renderTierPrice($_selections[0]) ?>
                    <?php endif; ?>
                    <input type="hidden"
                           class="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>  product bundle option"
                           name="bundle_option[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                           value="<?php /* @escapeNotVerified */ echo $_selections[0]->getSelectionId() ?>"/>
                <?php endif; ?>
                <?php if ($selectionBlock = $block->getChildBlock('product.info.bundle.option.checkbox.selection')): ?>
                    <?php /* @escapeNotVerified */ echo $selectionBlock->setOption($_option)->setSelection($_selections[0])->toHtml(); ?>
                <?php endif; ?>
            <?php else:?>
                <?php foreach($_selections as $_selection): ?>
                    <?php if ($isEnableImages): ?>
                        <?php $imageUrl = $this->helper('Magento\Catalog\Helper\Image')->init($_selection, 'product_thumbnail_image')->getUrl(); ?>
                        <div class="bundle-item -image">
                            <?php $selectionId = $_selection->getSelectionId(); ?>
                            <?php $optionSelectionId = $optionId . '-' . $selectionId ?>
                            <div class="flex flex-col" x-data="getConfigurableSimpleProduct()">
                                <div class="field choice mt-1 flex items-center gap-x-2 my-1">
                                    <input class="bundle-option-<?= (int)$optionId ?> form-checkbox <?= $_selection->getTypeId() ?>"
                                            id="bundle-option-<?= $escaper->escapeHtmlAttr($optionSelectionId) ?>"
                                            name="bundle_option[<?= (int)$optionId ?>][<?= (int)$selectionId ?>]"
                                            form="product_addtocart_form"
                                            type="checkbox"
                                            <?php if ($block->isSelected($_selection)) { echo ' checked="checked"'; } ?>
                                            <?php if (!$_selection->isSaleable()): ?>
                                                disabled="disabled"
                                            <?php endif; ?>
                                            value="<?= (int)$selectionId ?>"
                                            data-option-id="<?= $escaper->escapeHtmlAttr($optionSelectionId) ?>"
                                            @change="
                                                setProductType('<?= $_selection->getTypeId() ?>');
                                                calculateTotalPrice();
                                                showConfigurableProductDetails(<?= $_selection->getId() ?>, '<?= $_selection->getTypeId() ?>', <?= (int)$selectionId ?>)
                                            "
                                    />
                                    <div class="image">
                                        <img data-image="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-<?php /* @escapeNotVerified */ echo $_selection->getSelectionId() ?>" class="img" src="<?php echo $block->escapeUrl($imageUrl); ?>" alt="<?php echo $block->escapeHtml($_selection->getName()) ?>">
                                    </div>
                                    <label class="label" for="bundle-option-<?= $escaper->escapeHtmlAttr($optionSelectionId) ?>">
                                        <span><?= /* @noEscape */ $block->getSelectionQtyTitlePrice($_selection) ?></span>
                                    </label>
                                </div>
                            </div>
                            <?= /* @noEscape */ $block->getTierPriceRenderer()->renderTierPrice($_selection) ?>
                        </div>
                    <?php else: ?>
                        <?php $selectionId = $_selection->getSelectionId(); ?>
                            <?php $optionSelectionId = $optionId . '-' . $selectionId ?>
                            <div class="flex flex-col" x-bind="eventListeners" x-data="getConfigurableSimpleProduct()">
                                <div class="field choice mt-1 flex items-center gap-x-2 my-1">
                                    <input class="bundle-option-<?= (int)$optionId ?> form-checkbox"
                                            id="bundle-option-<?= $escaper->escapeHtmlAttr($optionSelectionId) ?>"
                                            name="bundle_option[<?= (int)$optionId ?>][<?= (int)$selectionId ?>]"
                                            form="product_addtocart_form"
                                            type="checkbox"
                                            <?php if ($block->isSelected($_selection)) { echo ' checked="checked"'; } ?>
                                            <?php if (!$_selection->isSaleable()): ?>
                                                disabled="disabled"
                                            <?php endif; ?>
                                            value="<?= (int)$selectionId ?>"
                                            data-option-id="<?= $escaper->escapeHtmlAttr($optionSelectionId) ?>"
                                            @change=" 
                                                calculateTotalPrice();
                                                showConfigurableProductDetails(<?= $_selection->getId() ?>, '<?= $_selection->getTypeId() ?>', <?= (int)$selectionId ?>)
                                            "
                                    />
                                    <label class="label" for="bundle-option-<?= $escaper->escapeHtmlAttr($optionSelectionId) ?>">
                                        <span><?= /* @noEscape */ $block->getSelectionQtyTitlePrice($_selection) ?></span>
                                    </label>
                                </div>
                                <div class="">
                                    <div id="product-price-ahy-<?= (int)$selectionId ?>"></div>
                                    <div id="swatch-html-<?= (int)$selectionId ?>"></div>
                                </div>
                            </div>
                            <?= /* @noEscape */ $block->getTierPriceRenderer()->renderTierPrice($_selection) ?>
                    <?php endif; ?>
                    <?php if ($selectionBlock = $block->getChildBlock('product.info.bundle.option.checkbox.selection')): ?>
                        <?php /* @escapeNotVerified */ echo $selectionBlock->setOption($_option)->setSelection($_selection)->toHtml(); ?>
                    <?php endif; ?>
                <?php endforeach; ?>
                <div id="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-container"></div>
            <?php endif; ?>
        </div>
    </div>
</div>


