<!--
/**
 * Webkul Software
 *
 * @category    Webkul
 * @package     Webkul_MpSellerBuyerCommunication
 * @author      Webkul
 * @copyright   Copyright (c)  Webkul Software Private Limited (https://webkul.com)
 * @license     https://store.webkul.com/license.html
 */
-->
<?php
$helperBlock = $block->getLayout()->createBlock(\Webkul\MpSellerBuyerCommunication\Block\Helper::class);
$_helper = $helperBlock->getMpHelper();
$isPartner= $_helper->isSeller();
$magentoCurrentUrl = $block->getCurrentUrl();
?>
<?php
if ($isPartner) { ?>
    <li class="nav item <?php if (strpos($magentoCurrentUrl, 'mpsellerbuyercommunication/seller/history')!== false) {
        echo ' current ';
                        } ?>">     
        <?php if (strpos($magentoCurrentUrl, 'mpsellerbuyercommunication/seller/history')!== false) { ?>   
            <strong><?= $escaper->escapeHtml(__('My Communication History')) ?></strong>        
            <?php
        } else { ?>    
            <a href="<?= $escaper->escapeUrl($block->getUrl(
                'mpsellerbuyercommunication/seller/history',
                ['_secure' => $block->getRequest()->isSecure()]
            )); ?>">
                <?= $escaper->escapeHtml(__('My Communication History')) ?>
            </a>                
            <?php
        } ?>      
    </li>
<?php } ?>

