<section class="container py-8 meatmas-holiday-sale">
    <div class="holiday-sale-img-banner flex items-center justify-center ">
        <img src="/media/holiday-sales/meatmas-slices/intro.jpg" alt="intro.jpg" width="600" height="600" class="flex">
    </div>
    <div class="intro-holiday-sale pb-6">
        <p class="text-white text-center text-2xl md:text-3xl">Celebrate the spirit of Meatmas with outdoor holiday gifts. </p>
        <p class="text-white text-center text-2xl md:text-3xl w-full md:w-3/4 m-auto">Unleash a strategic strike of joy with gear that’s got more layers than your uncle’s holiday jokes.</p>
    </div>
    <div class="md:hidden free-decal-banner">
        <img src="/media/wysiwyg/free-decal-pdp-banner.jpeg" alt="free-decal-banner h-full hover:brightness-[1.1]">
    </div>
    <div class="sale-callout space-y-4 w-full lg:w-[78%] xl:w-8/12 2xl:w-[57%] m-auto py-8">
        <div class="flex bg-[#fef9eb] flex-col md:flex-row sale-callout-card">
            <div class="flex sale-callout-img w-full md:w-[60%]">
                <a href="/meatmas-gyao-holiday-bundle.html" class="">
                    <img src="/media/holiday-sales/meatmas-slices/meatmas.jpg" alt="meatmas.jpg" class="flex h-full hover:brightness-[1.1]">
                </a>
            </div>
            <div class="flex gap-4 flex-col px-6 pt-8 pb-6 sale-callout-content w-full">
                <div class="pb-4">
                    <a href="/meatmas-gyao-holiday-bundle.html" class="underline-offset-6 hover:underline">
                        <p class="font-bold text-4xl md:text-5xl">Me<span class="text-ahy-red-light">a</span>tmas B<span class="text-ahy-red-light">B</span>Q Bund<span class="text-ahy-red-light">l</span>e</p>
                    </a>
                </div>
                <div class="pb-4">
                    <p class="">Wrap up in Ugly Meatmas Style: Shirt + GYAO BBQ Seasoning, hat and FREE digital thermometer – So good, even the Yeti would share... Maybe!</p>
                </div>
                <div class="flex md:justify-end">
                    <a href="/meatmas-gyao-holiday-bundle.html" class="">
                        <button class="border-3 border-ahy-blue rounded-full font-bold text-sm w-32 h-10 hover:shadow-[#0d2f47_0px_0px_0px_1px_inset]">Explore</button>
                    </a>
                </div>
            </div>
        </div>
        <div class="flex bg-[#fef9eb] flex-col md:flex-row sale-callout-card">
            <div class="flex sale-callout-img w-full md:w-[60%]">
                <a href="/burn-barriers-rise-stronger-omar-crispy-avila-everest-shirt.html" class="">
                    <img src="/media/holiday-sales/meatmas-slices/omar.jpg" alt="omar.jpg" class="flex h-full hover:brightness-[1.1]">
                </a>
            </div>
            <div class="flex gap-4 flex-col px-6 pt-8 pb-6 sale-callout-content w-full">
                <div class="pb-4">
                    <a href="/burn-barriers-rise-stronger-omar-crispy-avila-everest-shirt.html" class="underline-offset-6 hover:underline">
                        <p class="font-bold text-4xl md:text-5xl">O<span class="text-ahy-red-light">m</span>ar’s B<span class="text-ahy-red-light">u</span>rn Barr<span class="text-ahy-red-light">i</span>ers</p>
                    </a>
                </div>
                <div class="pb-4">
                    <p class="">Presenting Resilience Woven In: The Rise Stronger Series, a t-shirt collaboration with Omar Crispy Avila that embodies the triumph over adversity.</p>
                </div>
                <div class="flex md:justify-end">
                    <a href="/burn-barriers-rise-stronger-omar-crispy-avila-everest-shirt.html" class="">
                        <button class="border-3 border-ahy-blue rounded-full font-bold text-sm w-32 h-10 hover:shadow-[#0d2f47_0px_0px_0px_1px_inset]">Explore</button>
                    </a>
                </div>
            </div>
        </div>
        <div class="flex bg-[#fef9eb] flex-col md:flex-row sale-callout-card">
            <div class="flex sale-callout-img w-full md:w-[60%]">
                <a href="/vincent-rocco-vargas-hoodie.html" class="">
                    <img src="/media/holiday-sales/meatmas-slices/rocco.jpg" alt="rocco.jpg" class="flex h-full hover:brightness-[1.1]">
                </a>
            </div>
            <div class="flex gap-4 flex-col px-6 pt-8 pb-6 sale-callout-content w-full">
                <div class="pb-4">
                    <a href="/vincent-rocco-vargas-hoodie.html" class="underline-offset-6 hover:underline">
                        <p class="font-bold text-4xl md:text-5xl">Ro<span class="text-ahy-red-light">c</span>co’s Fix Myself F<span class="text-ahy-red-light">i</span>rst</p>
                    </a>
                </div>
                <div class="pb-4">
                    <p class="">Elevate Your Style with the 'Fix Myself First' hoodie, inspired by Vincent Rocco Vargas, championing men's mental health.</p>
                </div>
                <div class="flex md:justify-end">
                    <a href="/vincent-rocco-vargas-hoodie.html" class="">
                        <button class="border-3 border-ahy-blue rounded-full font-bold text-sm w-32 h-10 hover:shadow-[#0d2f47_0px_0px_0px_1px_inset]">Explore</button>
                    </a>
                </div>
            </div>
        </div>
        <div class="flex bg-[#fef9eb] flex-col md:flex-row sale-callout-card">
            <div class="flex sale-callout-img w-full md:w-[60%]">
                <a href="/everest-gift-bundle.html" class="">
                    <img src="/media/holiday-sales/meatmas-slices/swag-bundle.jpeg" alt="swag-bundle.jpg" class="flex h-full hover:brightness-[1.1]">
                </a>
            </div>
            <div class="flex gap-4 flex-col px-6 pt-8 pb-6 sale-callout-content w-full">
                <div class="pb-4">
                    <a href="/everest-gift-bundle.html" class="underline-offset-6 hover:underline">
                        <p class="font-bold text-4xl md:text-5xl">Ev<span class="text-ahy-red-light">e</span>rest S<span class="text-ahy-red-light">w</span>ag Bun<span class="text-ahy-red-light">d</span>le</p>
                    </a>
                </div>
                <div class="pb-4">
                    <p class="">Everest's Holiday Bundle: Gift card, cheeky t-shirts, decals, for wild wanderers with a taste for adventure—and coffee.</p>
                </div>
                <div class="flex md:justify-end">
                    <a href="/everest-gift-bundle.html" class="">
                        <button class="border-3 border-ahy-blue rounded-full font-bold text-sm w-32 h-10 hover:shadow-[#0d2f47_0px_0px_0px_1px_inset]">Explore</button>
                    </a>
                </div>
            </div>
        </div>
        <div class="flex bg-[#fef9eb] flex-col md:flex-row sale-callout-card">
            <div class="flex sale-callout-img w-full md:w-[60%]">
                <a href="/best-gifts-for-tactical-guys.html" class="">
                    <img src="/media/holiday-sales/meatmas-slices/gifts.jpeg" alt="gifts.jpg" class="flex h-full hover:brightness-[1.1]">
                </a>
            </div>
            <div class="flex gap-4 flex-col px-6 pt-8 pb-6 sale-callout-content w-full">
                <div class="pb-4">
                    <a href="/best-gifts-for-tactical-guys.html" class="underline-offset-6 hover:underline">
                        <p class="font-bold text-4xl md:text-5xl">Gi<span class="text-ahy-red-light">f</span>ts for T<span class="text-ahy-red-light">a</span>cti<span class="text-ahy-red-light">c</span>al Guys</p>
                    </a>
                </div>
                <div class="pb-4">
                    <p class="">These tactical gifts will make your loved ones say, 'I'd hug you, but I have tactical gear in my arms!</p>
                </div>
                <div class="flex md:justify-end">
                    <a href="/best-gifts-for-tactical-guys.html" class="">
                        <button class="border-3 border-ahy-blue rounded-full font-bold text-sm w-32 h-10 hover:shadow-[#0d2f47_0px_0px_0px_1px_inset]">Explore</button>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>
<style>
    .meatmas-holiday-sale .sale-callout .sale-callout-card{
        filter: drop-shadow(0px 64px 58.5px rgba(0,0,0,0.48));
    }
</style>