<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Sales\Block\Adminhtml\Order\View\Tab\Info */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<?php 
$_order = $block->getOrder();
$payment = $_order->getPayment();
?>

<div id="order-messages">
    <?= $block->getChildHtml('order_messages') ?>
</div>

<?= $block->getChildHtml('order_info') ?>
<input type="hidden" name="order_id" value="<?= (int) $_order->getId() ?>"/>

<section class="admin__page-section order-view-billing-shipping">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Payment &amp; Shipping Method')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-payment-method<?= ($_order->getIsVirtual() ?
            ' order-payment-method-virtual' : '') ?>">
            <?php /* Payment Method */ ?>
            <div class="admin__page-section-item-title">
                <span class="title"><?= $block->escapeHtml(__('Payment Information')) ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <div class="order-payment-method-title"><?= $block->getPaymentHtml() ?></div>
                <div class="additional-information">
                    <table>
                        <tbody>
                            <?php if ($payment->getAdditionalInformation('card_number')): ?>
                                <tr>
                                    <td><strong><?= __('Card Number:') ?></strong></td>
                                    <td><?= $block->escapeHtml($payment->getAdditionalInformation('card_number')) ?></td>
                                </tr>
                            <?php endif; ?>

                            <?php if ($payment->getAdditionalInformation('cvv_response')): ?>
                                <tr>
                                    <td><strong><?= __('CVV Response:') ?></strong></td>
                                    <td><?= $block->escapeHtml($payment->getAdditionalInformation('cvv_response')) ?></td>
                                </tr>
                            <?php endif; ?>

                            <?php if ($payment->getAdditionalInformation('card_type')): ?>
                                <tr>
                                    <td><strong><?= __('Card Type:') ?></strong></td>
                                    <td><?= $block->escapeHtml($payment->getAdditionalInformation('card_type')) ?></td>
                                </tr>
                            <?php endif; ?>

                            <?php if ($payment->getAdditionalInformation('expiry')): ?>
                                <tr>
                                    <td><strong><?= __('Expiry:') ?></strong></td>
                                    <td><?= $block->escapeHtml($payment->getAdditionalInformation('expiry')) ?></td>
                                </tr>
                            <?php endif; ?>

                            <?php if ($payment->getAdditionalInformation('trans_id')): ?>
                                <tr>
                                    <td><strong><?= __('Transaction ID:') ?></strong></td>
                                    <td><?= $block->escapeHtml($payment->getAdditionalInformation('trans_id')) ?></td>
                                </tr>
                            <?php endif; ?>

                            <?php if ($payment->getAdditionalInformation('ref_trans_id')): ?>
                                <tr>
                                    <td><strong><?= __('Ref. Transaction ID:') ?></strong></td>
                                    <td><?= $block->escapeHtml($payment->getAdditionalInformation('ref_trans_id')) ?></td>
                                </tr>
                            <?php endif; ?>

                            <?php if ($payment->getAdditionalInformation('avs_response')): ?>
                                <tr>
                                    <td><strong><?= __('AVS Response:') ?></strong></td>
                                    <td><?= $block->escapeHtml($payment->getAdditionalInformation('avs_response')) ?></td>
                                </tr>
                            <?php endif; ?>
                        </tbody>
                    </table>
                </div>

                <style>
                    .additional-information table {
                        width: 100%;
                    }
                    .additional-information table tr:nth-child(odd) {
                        background: #f1f1f1;
                    }
                    .additional-information table tr td {
                        padding: 1rem;
                    }
                    .additional-information {
                        padding: 15px 0;
                    }
                    .additional-information table tr td:nth-child(even) {
                        text-align: end;
                    }
                </style>
                <div class="order-payment-currency">
                    <?= $block->escapeHtml(__('The order was placed using %1.', $_order->getOrderCurrencyCode())) ?>
                </div>
                <div class="order-payment-additional">
                    <?= $block->getChildHtml('order_payment_additional') ?>
                    <?= $block->getChildHtml('payment_additional_info') ?>
                </div>
            </div>
        </div>
        <?= $block->getChildHtml('order_shipping_view') ?>
    </div>
</section>

<?= $block->getChildHtml('order_additional_info') ?>

<?= $block->getGiftOptionsHtml() ?>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Items Ordered')) ?></span>
    </div>
    <?= $block->getItemsHtml() ?>
</section>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Order Total')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-comments-history">
            <div class="admin__page-section-item-title">
                <span class="title"><?= $block->escapeHtml(__('Notes for this Order')) ?></span>
            </div>
            <?= $block->getChildHtml('order_history') ?>
        </div>

        <div class="admin__page-section-item order-totals">
            <div class="admin__page-section-item-title">
                <span class="title"><?= $block->escapeHtml(__('Order Totals')) ?></span>
            </div>
            <?= $block->getChildHtml('order_totals') ?>
        </div>
    </div>
</section>

<?= $block->getChildHtml('popup_window') ?>

<?php $scriptString = <<<script
require([
    "prototype",
    "Magento_Sales/order/giftoptions_tooltip"
], function(){

//<![CDATA[
    /**
     * Retrieve gift options tooltip content
     */
    function getGiftOptionsTooltipContent(itemId) {
        var contentLines = [];
        var headerLine = null;
        var contentLine = null;

        \$$('#gift_options_data_' + itemId + ' .gift-options-tooltip-content').each(function (element) {
            if (element.down(0)) {
                headerLine = element.down(0).innerHTML;
                contentLine = element.down(0).next().innerHTML;
                if (contentLine.length > 30) {
                    contentLine = contentLine.slice(0,30) + '...';
                }
                contentLines.push(headerLine + ' ' + contentLine);
            }
        });
        return contentLines.join('<br/>');
    }
    giftOptionsTooltip.setTooltipContentLoaderFunction(getGiftOptionsTooltipContent);
    window.getGiftOptionsTooltipContent = getGiftOptionsTooltipContent;
//]]>

});
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
