<?php declare(strict_types=1);
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magento\Checkout\Block\Registration;
use Magento\Framework\Escaper;

/** @var Registration $block */
/** @var Escaper $escaper */
?>
<div class="container text-center py-4 px-6">
    <p class="text-center"><?= $escaper->escapeHtml(__('You can track your order status by creating an account.')) ?></p>
    <p class="text-center"><?= $escaper->escapeHtml(__('Email Address:')) ?><span class="font-bold"> <?= $escaper->escapeHtml($block->getEmailAddress()) ?></span></p>
    <div class="my-4">
        <a class="text-center" href="<?= $escaper->escapeUrl($block->getCreateAccountUrl()) ?>">
            <button class="border-3 border-ahy-blue rounded-full font-bold text-sm w-56 h-12 hover:shadow-[#0d2f47_0px_0px_0px_1px_inset]">
                <span>
                    <?= $escaper->escapeHtml(__('Create an Account')) ?>
                </span>
            </button>
        </a>
    </div>
</div>
