<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<?php
    /** @var $block \Webkul\Marketplace\Block\Product\Create */
    $viewModel = $block->getViewModel();
    $helper = $viewModel->getHelper();
    $globalProductLimitQty = $helper->getGlobalProductLimitQty();
    $productId=$block->getRequest()->getParam('id');
if ($productId) {
    $productColl = $block->getProduct($productId);
    $productTypeId = $productColl['type_id'];
    $mpProductCartLimit = $productColl['mp_product_cart_limit'];
} else {
    $productTypeId = $block->getRequest()->getParam('type');
    $mpProductCartLimit = '';
}
?>
<?php if ($productTypeId != 'downloadable' && $productTypeId != 'virtual'): ?>
    <div class="field">
        <label class="label"><?= $escaper
        ->escapeHtml(__('Allowed Product Qty on Product Purchase for Customer')) ?>:</label>
        <div class="control">
            <input type="text" class="input-text validate-number" name="product[mp_product_cart_limit]" 
            id="mp_product_cart_limit" value="<?= $escaper->escapeHtml($mpProductCartLimit); ?>"/>
            <span>
                <?= $escaper->escapeHtml(__(
                    "By default %1 qty will be allowed for customer to add in cart.",
                    $globalProductLimitQty
                ));?>
            </span>
        </div>
    </div>
<?php endif; ?>
