<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

/** @var Template $block */
/** @var FormatterViewModel $formatterViewModel */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Checkout\ViewModel\Checkout\Formatter as FormatterViewModel;
use Hyva\Theme\Model\ViewModelRegistry;

$formatterViewModel = $viewModels->require(FormatterViewModel::class);
$segment = $block->getSegment();
?>
<div class="flex gap-4 justify-between border-t border-ahy-blue pt-4 mt-4 md:gap-0 text-ahy-blue">
    <span class="label font-bold text-xl">
        <?= $escaper->escapeHtml(__(($segment['title'] ?? 'Order Total'))) ?>
    </span>
    <span class="value text-right font-bold">
        <?= /* @noEscape */ $formatterViewModel->currency($segment['value'] ?? 0) ?>
    </span>
</div>
