<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

use Hyva\Checkout\ViewModel\Breadcrumbs;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\View\Element\Template;

$viewModel = $viewModels->require(Breadcrumbs::class);
$config = $viewModel->getCheckoutConfig();
$steps = $config->getSteps();
$stepCount = is_array($steps) ? count($steps) : 0;

?>
<nav id="breadcrumbs"
    class="nav-braincrumbs mb-6 pb-1 flex justify-center md:space-x-4 md:border-b md:border-gray-200 bg-ahy-blue w-screen left-1/2 right-1/2 mx-[-50vw] relative <?= $stepCount === 3 ? 'three-steps' : '' ?>"
>
    <?php if ($config->hasSteps() && $config->isMultiStepper()): ?>
        <?= $block->getChildHtml('hyva.checkout.breadcrumbs.waypoints') ?>
        <style>

        @media screen and (max-width: 767px) {

            .step-shipping #breadcrumbs::before {
                content: '';
                position: absolute;
                top: 35%;
                left: 52.6%;
                transform: translate(-50%, -50%);
                width: 165px;
                height: 2px;
                background-color: white;
                max-width: 156px;

            }

            /* Hide line when checkout has 3 steps */
            #breadcrumbs.three-steps::before {
                display: none;
            }
            .step-payment #breadcrumbs::before {
                content: '';
                position: absolute;
                top: 35%;
                left: 53.6%;
                transform: translate(-50%, -50%);
                width: 165px;
                height: 2px;
                background-color: white;
                max-width: 156px;

            }
        }
        @media screen and (max-width: 364px) {
            .step-shipping #breadcrumbs::before {
                content: '';
                position: absolute;
                top: 30%;
                left: 55%;
                transform: translate(-50%, -50%);
                width: 43vw;
                height: 2px;
                background-color: white;
            }
            .step-payment #breadcrumbs::before {
                content: '';
                position: absolute;
                top: 30%;
                left: 55%;
                transform: translate(-50%, -50%);
                width: 43vw;
                height: 2px;
                background-color: white;
            }
        }
        </style>
    <?php endif ?>

    <div class="flex flex-col space-y-4 float-right md:space-x-4 md:space-y-0 md:flex-row">
        <?= $block->getChildHtml('hyva.checkout.breadcrumbs.additional') ?>
    </div>
</nav>