<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

/** @var Template $block */

use Magento\Framework\View\Element\Template;

$navHtmlLeft = $block->getChildHtml('hyva.checkout.navigation.left');
$navHtmlRight = $block->getChildHtml('hyva.checkout.navigation.right');
?>
<nav x-data="initCheckoutNavigation()"
     class="nav-main
            text-center
            flex flex-col-reverse md:flex-row
            gap-y-2 md:gap-y-0 md:gap-x-0
            
            md:mb-0"
>
    <?php if (! empty($navHtmlLeft)): ?>
        <div class="flex flex-col-reverse md:flex-row
                    gap-y-2 md:gap-x-2
                    w-full
                    md:items-center
                    p-2
                    rounded-lg md:rounded-r-none  px-2 md:px-12 mt-0"
        >
            <?= /* @noEscape */ $navHtmlLeft ?>
        </div>
    <?php endif ?>

    <div class="flex flex-col-reverse md:flex-row
                gap-y-2 md:gap-x-2
                w-full
                justify-end
                md:items-center
                p-2
                rounded-lg md:rounded-l-none px-2 md:px-12 mt-0
                "
    >
        <?= /* @noEscape */ $navHtmlRight ?>
    </div>
</nav>
