<?php

declare(strict_types=1);

use Magento\Framework\Escaper;

/** @var Escaper $escaper */
?>

<div x-data="braintreeApplePay" x-init="() => { console.log('[Pravin Check] x-init fired on Alpine component mount'); initialise(); }" id="braintreeApplePay" wire:key="<?= uniqid('', true) ?>">
    <template x-if="hasApplePayToken">
        <p class="nonce_thankyou_message">
            Thank you. Please click <span>Place Order</span> to finish checkout with Apple Pay.
        </p>
    </template>
    <template x-if="!showApplePayButtonOnCheckout">
        <p>Apple Pay is not available on this device. Please use a supported Apple device with Wallet enabled.</p>
    </template>
    <template x-if="showApplePayButtonOnCheckout && hasNoApplePayToken">
        <div id="braintreeApplePayButton" class="relative z-10"></div>
    </template>
</div>

<style>
    /* TODO: Generate this through Tailwind: */
    .nonce_thankyou_message {
        font-size: 20px;
        margin: 25px 0;
        color: #a0802c;
        font-weight: 500;
    }

    .nonce_thankyou_message span {
        font-weight: 700;
    }

    @media screen(max-width: 700px) {
        .nonce_thankyou_message {
            font-size: 12px;
        }
    }
</style>