<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_ProductStockAlert
 * @author     Extension Team
 * @copyright  Copyright (c) 2015-2022 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

// @codingStandardsIgnoreFile

/** @var $block \Bss\ProductStockAlert\Block\Email\Stock */
?>
<?php if ($_productDataArr = $block->getProductData()): ?>
    <p><?= /* @escapeNotVerified */  __('In stock alert! We wanted you to know that these products are now available:') ?></p>
    <table>
        <?php foreach ($_productDataArr as $_productData): ?>
            <?php $_product = $block->getProductFromData($_productData); ?>
            <?php $_parentProduct = $block->getProductFromData($_productData, false); ?>
            <tr>
                <td class="col photo">

                    <?php if ($block->hasProductUrl($_product)):?>
                    <a href="<?= /* @escapeNotVerified */ $block->getProductUrl($_parentProduct) ?>"
                       title="<?= $block->escapeHtml($block->getProductName()) ?>"
                       tabindex="-1"
                       class="product-item-photo">
                        <?php else:?>
                        <span class="product-item-photo">
            <?php endif;?>
            <?= $block->getImage($_product, 'cart_page_product_thumbnail')->toHtml() ?>
            <?php if ($block->hasProductUrl($_product)):?>
                    </a>
                <?php else: ?>
                    </span>
                <?php endif; ?>
                </td>
                <td class="col item">
                    <p>
                        <strong class="product name">
                            <a href="<?= /* @escapeNotVerified */  $block->getProductUrl($_parentProduct) ?>"><?= $block->escapeHtml($_product->getName()) ?></a>
                        </strong>
                    </p>
                    <?php if ($_product->getShortDescription() !== null && $shortDescription = $block->getFilteredContent($_product->getShortDescription())): ?>
                        <p><small><?= /* @escapeNotVerified */  $shortDescription ?></small></p>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif; ?>
