<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\ReCaptcha;
use Magento\Framework\Escaper;
use Magento\Newsletter\Block\Subscribe;

/** @var Subscribe $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var ReCaptcha $recaptcha */
/** @var HeroiconsOutline $heroicons */

$heroicons = $viewModels->require(HeroiconsOutline::class);

// Do not replace this with $viewModels->require(ReCaptcha::class); that might break the dependency
// on the Magento_ReCaptchaNewsletter module
$recaptcha = $block->getData('viewModelRecaptcha');
?>
<div class="px-4">
    <!-- <form class="form subscribe" action="<?= $escaper->escapeUrl($block->getFormActionUrl()) ?>" method="post" x-data="initNewsletterForm()" @submit.prevent="submitForm()"
        id="newsletter-validate-detail">
        <div class="mb-3 font-bold tracking-widest text-ahy-blue">
            <h3 class="leading-6 text-ahy-blue flex justify-center md:justify-start"><?= $escaper->escapeHtml(__('Email Alerts')) ?></h3>
            <p class="text-xs font-normal tracking-normal text-center md:text-start"><?= $escaper->escapeHtml(__('Join over 100k outdoor enthusiast and get exclusive deals, outdoor tips & more.'))?></p>
        </div>
        <div class="flex justify-center md:justify-start">
            <label for="newsletter-subscribe" class="sr-only">
                <?= $escaper->escapeHtml(__('Email Address')) ?>
            </label>
            <input name="email" type="email" required id="newsletter-subscribe" class="rounded-l border-none focus:ring-transparent rounded-none inline-flex w-full" placeholder="<?= $escaper->escapeHtmlAttr(__('Your Email')) ?>">
            <?= $block->getBlockHtml('formkey') ?>
            <?= $recaptcha ? $recaptcha->getInputHtml(ReCaptcha::RECAPTCHA_FORM_ID_NEWSLETTER) : '' ?>
            <button class="inline-flex shrink-0 ml-auto xl:mt-0 btn rounded-none bg-ahy-blue hover:bg-ahy-blue focus:ring-transparent rounded-r">
                <?= $escaper->escapeHtml(__('Sign up')) ?>
            </button>
        </div>
        <div>
            <template x-if="displayErrorMessage">
                <p class="flex items-center text-red">
                    <span class="inline-block w-8 h-8 mr-3">
                        <?= $heroicons->exclamationCircleHtml(); ?>
                    </span>
                    <template x-for="errorMessage in errorMessages">
                        <span x-html="errorMessage"></span>
                    </template>
                </p>
            </template>
        </div>
    </form> 
    <div class="w-full">
        <?= $recaptcha ? $recaptcha->getLegalNoticeHtml(ReCaptcha::RECAPTCHA_FORM_ID_NEWSLETTER) : '' ?>
    </div> -->

    <div class="klaviyo-form-XZqU8g"></div>
    
    <div class="mt-6 mb-4">
        <div class="title mt-4"><span class="font-bold text-ahy-blue flex justify-center md:justify-start">Payment types we accept</span></div>
        <div class="card-image mt-4">
            <img 
                src="https://www.everest.com/media/wysiwyg/footer/credit-card.svg" 
                alt="Card we accept" 
                srcset=""
                class="w-full h-auto"
                width="250"
                height="250"
            >
        </div>
    </div>

    <div class="my-8 pt-4 relative">
        <span class="w-full justify-center inline-flex items-center border-3 uppercase border-ahy-blue px-6 py-3 text-[15px] font-bold text-gray-700 shadow-sm">
            <svg id="icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 14.66 20" class="w-3 h-3 mr-2"><defs><style>.cls-121{fill:#0d2f47;}</style></defs>
                <path class="cls-1" d="M4,5.35a3.35,3.35,0,0,1,6.7,0v.87h2V5.35A5.35,5.35,0,0,0,2,5.35v.87H4Z"/><path class="cls-121" d="M13.66,8.22H1a1,1,0,0,0-1,1V19a1,1,0,0,0,1,1H13.66a1,1,0,0,0,1-1V9.22A1,1,0,0,0,13.66,8.22ZM7.83,17.05a.5.5,0,0,1-1,0V15.12a2,2,0,1,1,1,0Z"/>
            </svg> Securely Processed
        </span>
    </div>

    <div class="flex justify-center items-center">
        <a href="//www.securitymetrics.com/site_certificate?id=1990116&tk=ae70735bafa2e421fdcb8c09272d895a"
            target="_blank" rel="noopener noreferrer">
            <img 
                src="https://www.securitymetrics.com/portal/app/ngsm/assets/img/GreyContent_PCI_Validation_White_Sqr.png"
                alt="SecurityMetrics PCI validation certification logo"
                class="w-full h-auto"
                width="250"
                height="250"
                loading="lazy"
            />
        </a>
    </div>

    <script>
        function initNewsletterForm() {
            return {
                errors: 0,
                hasCaptchaToken: 0,
                displayErrorMessage: false,
                errorMessages: [],
                setErrorMessages(messages) {
                    this.errorMessages = [messages]
                    this.displayErrorMessage = this.errorMessages.length
                },
                submitForm() {
                    // Do not rename $form, the variable is expected to be declared in the recaptcha output
                    const $form = document.querySelector('#newsletter-validate-detail');
                    <?= $recaptcha ? $recaptcha->getValidationJsHtml(ReCaptcha::RECAPTCHA_FORM_ID_NEWSLETTER) : '' ?>

                    if (this.errors === 0) {
                        $form.submit();
                    }
                }
            }
        }
    </script>
</div>
