<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$viewModel  = $block->getViewModel();
$helper     = $viewModel->getHelper();
$pageLayout = $helper->getSellerProfileLayout();
$pageLayout = 'ahy';
if ($pageLayout == 1) {
    echo $block->getChildHtml('marketplace_sellerprofile_layout1');
} elseif ($pageLayout == 2) {
    echo $block->getChildHtml('microsite.details');
} elseif ($pageLayout == 'ahy'){    
    echo $block->getChildHtml('marketplace_sellerprofile_layout_ahy');
}
