<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

/** @var Template $block */
/** @var HeroiconsOutline $heroiconsViewModel */
/** @var Magewire $magewire */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Checkout\Magewire\Checkout\CouponCode as Magewire;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

$heroiconsViewModel = $viewModels->require(HeroiconsOutline::class);
$classCouponAvailability = $magewire->couponCode ? 'available' : 'not-available';
$saveAction = $magewire->couponCode ? 'revokeCouponCode' : 'applyCouponCode';
?>

<div class="coupon-code <?= $escaper->escapeHtmlAttr($classCouponAvailability) ?> flex flex-col mt-2 items-stretch" x-data="{
         couponCode: $wire.entangle('couponCode'),
         couponHits: $wire.entangle('couponHits')
     }">
    <div class="page messages">
        <script>
            function initMessages() {
                "use strict";
                return {
                    messages: window.mageMessages || [],
                    isEmpty() {
                        return this.messages.reduce(
                            function (isEmpty, message) {
                                return isEmpty && message === undefined
                            }, true
                        )
                    },
                    removeMessage(messageIndex) {
                        this.messages[messageIndex] = undefined;
                    },
                    addMessages(messages, hideAfter) {
                        messages.map((message) => {
                            this.messages = this.messages.concat(message);
                            if (hideAfter) {
                                this.setHideTimeOut(this.messages.length - 1, hideAfter);
                            }
                        });
                    },
                    setHideTimeOut(messageIndex, hideAfter) {
                        setTimeout((messageIndex) => {
                            this.removeMessage(messageIndex);
                        }, hideAfter, messageIndex);
                    },
                    eventListeners: {
                        ['@messages-loaded.window']() {
                            this.addMessages(event.detail.messages, event.detail.hideAfter)
                        },
                        ['@private-content-loaded.window'](event) {
                            const data = event.detail.data;
                            if (
                                data.messages &&
                                data.messages.messages &&
                                data.messages.messages.length
                            ) {
                                this.addMessages(data.messages.messages);
                            }
                        },
                        ['@clear-messages.window']() {
                            this.messages = [];
                        }
                    }
                }
            }
        </script>
        <section id="messages" x-data="initMessages()" x-bind="eventListeners">
            <template x-if="!isEmpty()">
                <div class="w-full">
                    <div role="alert" class="messages container mx-auto py-3">
                        <template x-for="(message, index) in messages" :key="index">
                            <div>
                                <template x-if="message">
                                    <div class="message" :class="message.type" :ui-id="'message-' + message.type">
                                        <span x-html="message.text"></span>
                                        <a href="#" class="close cursor-pointer" title="close" @click.prevent="removeMessage(index)">
                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="text-white" width="18" height="18">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
                                            </svg>
                                        </a>
                                    </div>
                                </template>
                            </div>
                        </template>
                    </div>
                </div>
            </template>
        </section>
    </div>
    <div class="flex">
        <input type="text" class="form-input rounded-none rounded-l-md border-r-0 text-sm w-1/2 focus:ring-0" placeholder="<?= $escaper->escapeHtmlAttr(__('Enter discount code')) ?>"
            wire:model.defer="couponCode" wire:loading.attr="disabled" wire:keydown.enter="<?= /* @noEscape */ $saveAction ?>"
            x-bind:class="{ 'has-coupon': couponCode, 'disabled': couponCode, 'invalid': couponHits !== 0 }" x-bind:disabled="couponCode" />
        <button type="button" class="btn btn-secondary justify-center w-1/2 rounded-none rounded-r-md bottom-0"
            wire:click="<?= /* @noEscape */ $saveAction ?>"
            wire:loading.attr="disabled"
            wire:loading.class="disabled"
            x-bind:class="{ 'has-coupon': couponCode, 'disabled': ! couponCode, 'invalid': couponHits !== 0 }"
            x-cloak
        >
            <span wire:loading.block class="hidden">
                <?= $escaper->escapeHtml(__('Processing...')) ?>
            </span>
            <?php if ($magewire->couponCode): ?>
            <span wire:loading.remove>
                <?= $escaper->escapeHtml(__('Cancel coupon')) ?>
            </span>
            <?php else: ?>
            <span wire:loading.remove>
                <?= $escaper->escapeHtml(__('Apply Discount')) ?>
            </span>
            <?php endif ?>
        </button>
    </div>
</div>

