<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_ProductStockAlert
 * @author     Extension Team
 * @copyright  Copyright (c) 2015-2017 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
// @codingStandardsIgnoreFile
/** @var $block \Bss\ProductStockAlert\Block\System\Config\Form\Button */
?>
<div class="hidden" id="URL"><?php echo $block->getCronUrl() ?></div>
<div class="pp-buttons-container">
    <a id="<?php echo $block->getId() ?>" class="action-primary">
        <span><span><span><?php echo $block->escapeHtml($block->getButtonLabel()); ?></span></span></span>
    </a>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "cronModal" : {
            }
        }
    }
</script>
