<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */

use Hyva\Checkout\ViewModel\Navigation;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

$viewModel = $viewModels->require(Navigation::class);
$next = $viewModel->getConfig()->getStepAfter();
?>
<?php if ($next === null): ?>
    <div class="flex w-full items-center justify-center flex-col">
        <button 
            type="button"
            class="ahy-proceed-btn ahy-custom-btn btn bg-ahy-red rounded-full w-full h-14 flex leading-none !border-0 justify-center hover:bg-ahy-red-light rounded-full focus:ring-transparent p-4"
            x-spread="buttonPlaceOrder()"
            x-bind="buttonPlaceOrder()"
        >
            <?= $escaper->escapeHtml(__('Place Order')) ?>
        </button>
        <div class="my-8 max-w-xs w-full pt-4 relative">
            <span class="w-full justify-center inline-flex items-center border-3 uppercase border-ahy-blue px-6 py-3 text-[15px] font-bold text-gray-700 shadow-sm">
                <svg id="icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 14.66 20" class="w-3 h-3 mr-2"><defs><style>.cls-121{fill:#0d2f47;}</style></defs>
                    <path class="cls-1" d="M4,5.35a3.35,3.35,0,0,1,6.7,0v.87h2V5.35A5.35,5.35,0,0,0,2,5.35v.87H4Z"></path><path class="cls-121" d="M13.66,8.22H1a1,1,0,0,0-1,1V19a1,1,0,0,0,1,1H13.66a1,1,0,0,0,1-1V9.22A1,1,0,0,0,13.66,8.22ZM7.83,17.05a.5.5,0,0,1-1,0V15.12a2,2,0,1,1,1,0Z"></path>
                </svg> Securely Processed
            </span>
        </div>
        <div class="flex justify-center items-center">
            <a href="//www.securitymetrics.com/site_certificate?id=1990116&tk=ae70735bafa2e421fdcb8c09272d895a"
                target="_blank" rel="noopener noreferrer">
                <img src="https://www.securitymetrics.com/portal/app/ngsm/assets/img/GreyContent_PCI_Validation_White_Sqr.png"
                    alt="SecurityMetrics PCI validation certification logo"/>
            </a>
        </div>
    </div>
<?php endif ?>
