<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$viewModel = $block->getViewModel();
$helper = $viewModel->getHelper();
$partner = $block->getProfileDetail();
if ($partner['shop_url'] && $helper->getSellerPolicyApproval()) {
  /* @noEscape */ echo $partner['privacy_policy'];
}  ?>
