<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Customer\CreateAccountButton;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Hyva\Theme\ViewModel\ReCaptcha;
use Magento\Customer\Block\Form\Register;
use Magento\Customer\Block\Widget\Dob;
use Magento\Customer\Block\Widget\Gender;
use Magento\Customer\Block\Widget\Name as NameWidget;
use Magento\Customer\Block\Widget\Taxvat;
use Magento\Customer\Helper\Address;
use Magento\Framework\Escaper;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper
// phpcs:disable Generic.Files.LineLength.TooLong

/** @var Register $block */
/** @var Escaper $escaper */
/** @var ReCaptcha $recaptcha */
/** @var CreateAccountButton $createAccountButtonViewModel */
/** @var ViewModelRegistry $viewModels */
/** @var HeroiconsSolid $heroicons */

$formId = 'accountcreate';

// Do not replace this with $viewModels->require(ReCaptcha::class); that might break the dependency
// on the Magento_ReCaptchaCustomer module
$recaptcha = $block->getData('viewModelRecaptcha');
$heroIcons = $viewModels->require(HeroiconsSolid::class);
$createAccountButtonViewModel = $viewModels->require(CreateAccountButton::class);
$region = $block->getAttributeData()->getFrontendLabel('region');
$selectRegion = 'Please select a region, state or province.';
$showOptionalRegions = $block->getConfig('general/region/display_all');
$regionLabel = $block->getAttributeData()->getFrontendLabel('region');
$minimumPasswordLength = $block->getMinimumPasswordLength();
$passwordMinCharacterSets = $block->getRequiredCharacterClassesNumber();
?>
<div class="registration-container registation-container container p-0 flex-columns-wrapper py-6 max-w-6xl">
    <div class="w-full md:w-4/5 card mr-12 bg-ahy-yellow-card px-0 py-8 relative">
        <?php /* Extensions placeholder */ ?>
        <?= $block->getChildHtml('customer.form.register.extra') ?>
        <form class="form create account form-create-account"
              action="<?= $escaper->escapeUrl($block->getPostActionUrl()) ?>"
              x-data="Object.assign(hyva.formValidation($el), initForm())"
              <?php if ($block->getShowAddressFields()): ?>
              @private-content-loaded.window="onPrivateContentLoaded(event.detail.data)"
              <?php endif; ?>
              id="<?= $escaper->escapeHtmlAttr($formId) ?>"
              @submit.prevent="submitForm()"
              method="post" id="form-validate" enctype="multipart/form-data" autocomplete="off">
            <?= /* @noEscape */ $block->getBlockHtml('formkey'); ?>
            <?= $block->getChildHtml('form_fields_before') ?>
            
            <div class="relative">
                <fieldset >
                    <legend class="contents">
                        <div class="flex flex-col px-12">
                            <span class="font-extrabold text-xl" >
                                <?= $escaper->escapeHtml(__('Sign Up with Email')) ?>
                            </span>
                            <span class="text-xs font-medium mb-4">
                                <?= $escaper->escapeHtml(__('* Required Information')) ?>
                            </span>
                        </div>
                    </legend>
                    <div class="pre-header my-4 flex hidden bg-ahy-blue text-white">
                        <span class="py-3  px-12 text-center text-sm">
                            We’ll email you an <strong class="">EXTRA 20% OFF</strong> your next purchase! <a href="javascript:void()" class="underline underline-offset-3">Details</a>
                        </span>
                    </div>
                    <input type="hidden" name="success_url" value="<?= $escaper->escapeUrl($block->getSuccessUrl()) ?>">
                    <input type="hidden" name="error_url" value="<?= $escaper->escapeUrl($block->getErrorUrl()) ?>">
                    <div class="field field-reserved px-12 w-full field-name-firstname ahy-styling required">
                        <label class="label font-bold" for="firstname">
                            <span> <?= $escaper->escapeHtml(__('First Name *')) ?> </span>
                        </label>
                        <div class="control">
                            <input type="text" id="firstname" name="firstname" value="" required="" title="First Name" class="form-input required-entry w-full !h-14">
                        </div>
                    </div>
                    <div class="field field-reserved px-12 w-full field-name-lastname ahy-styling required">
                        <label class="label font-bold" for="lastname">
                            <span> <?= $escaper->escapeHtml(__('Last Name *')) ?> </span>
                        </label>
                        <div class="control">
                            <input type="text" id="lastname" name="lastname" required="" value="" title="Last Name" class="form-input required-entry w-full !h-14">
                        </div>
                    </div>
                    <div class="field field-reserved px-12 ahy-styling required">
                        <label for="email_address" class="label font-bold">
                            <span>
                                <?= $escaper->escapeHtml(__('Email *')) ?>
                            </span>
                        </label>
                        <div class="control">
                            <input type="email" name="email" autocomplete="email" id="email_address" required
                                   value="<?= $escaper->escapeHtmlAttr($block->getFormData()->getEmail()) ?>"
                                   title="<?= $escaper->escapeHtmlAttr(__('Email')) ?>" class="form-input w-full !h-14" />
                        </div>
                    </div>
                    <div class="field field-reserved ahy-styling px-12">
                        <label for="password" class="label font-bold"><span><?= $escaper->escapeHtml(__('Password')) ?></span></label>
                        <div class="control flex items-center relative">
                            <?php $minimumPasswordLength = $block->getMinimumPasswordLength() ?>
                            <input :type="showPassword ? 'text' : 'password'" type="password" id="password" name="password"
                                   title="<?= $escaper->escapeHtmlAttr(__('Password *')) ?>"
                                   minlength="<?= $escaper->escapeHtmlAttr($minimumPasswordLength) ?>"
                                   class="form-input w-full !h-14"
                                   required
                                   data-validate='{"password-strength": {"minCharacterSets": <?= (int) $passwordMinCharacterSets ?>}}'
                                   @input="onChange"
                                   autocomplete="off">
                            <div x-on:click="showPassword = !showPassword"
                                 class="cursor-pointer px-4 absolute right-0"
                                 :aria-label="showPassword ? '<?= $escaper->escapeJs(__('Hide Password')) ?>' : '<?= $escaper->escapeJs(__('Show Password')) ?>'"
                            >
                                <template x-if="!showPassword">
                                    <?= $heroIcons->eyeHtml('w-5 h-5'); ?>
                                </template>
                                <template x-if="showPassword">
                                    <?= $heroIcons->eyeOffHtml('w-5 h-5'); ?>
                                </template>
                            </div>
                        </div>
                        <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                            <div id="password-strength-meter" class="password-strength-meter">
                                <?= $escaper->escapeHtml(__('Password Strength')) ?>:
                                <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                                    <?= $escaper->escapeHtml(__('No Password')) ?>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="field field-reserved ahy-styling px-12">
                        <label for="password-confirmation" class="label font-bold">
                            <span>
                                <?= $escaper->escapeHtml(__('Confirm Password *')) ?>
                            </span>
                        </label>
                        <div class="control flex items-center relative">
                            <input :type="showPasswordConfirm ? 'text' : 'password'" type="password"
                                   name="password_confirmation"
                                   title="<?= $escaper->escapeHtmlAttr(__('Confirm Password')) ?>"
                                   id="password-confirmation"
                                   data-validate='{"equalTo": "password"}'
                                   @input="onChange"
                                   required
                                   class="form-input w-full !h-14"
                                   autocomplete="off">
                            <div x-on:click="showPasswordConfirm = !showPasswordConfirm"
                                 class="cursor-pointer px-4 absolute right-0"
                                 :aria-label="showPasswordConfirm ? '<?= $escaper->escapeJs(__('Hide Password')) ?>' : '<?= $escaper->escapeJs(__('Show Password')) ?>'"
                            >
                                <template x-if="!showPasswordConfirm">
                                    <?= $heroIcons->eyeHtml('w-5 h-5'); ?>
                                </template>
                                <template x-if="showPasswordConfirm">
                                    <?= $heroIcons->eyeOffHtml('w-5 h-5'); ?>
                                </template>
                            </div>
                        </div>
                    </div>
                    <?= $block->getChildHtml('form_additional_info') ?>
                    <div class="px-12 mb-6"><?= $recaptcha ? $recaptcha->getInputHtml(ReCaptcha::RECAPTCHA_FORM_ID_CUSTOMER_CREATE) : '' ?></div>
                    <?= $recaptcha ? $recaptcha->getLegalNoticeHtml(ReCaptcha::RECAPTCHA_FORM_ID_CUSTOMER_CREATE) : '' ?>
                    <?php if ($block->isNewsletterEnabled()): ?>
                        <div class="field choice newsletter  px-12 ">
                            <input type="checkbox" name="is_subscribed"
                                   title="<?= $escaper->escapeHtmlAttr(__('Sign up for Weekly Everest Email Newsletters')) ?>" value="1"
                                   id="is_subscribed"
                                    <?php if ($block->getFormData()->getIsSubscribed()): ?>
                                        checked="checked"
                                    <?php endif; ?>
                                   class="checkbox !mr-2">
                            <label for="is_subscribed" class="label">
                                <span class=" text-sm font-medium text-ahy-blue">
                                    <?= $escaper->escapeHtml(__('Sign Up for Newsletter')) ?>
                                </span>
                            </label>
                        </div>
                        <?php /* Extensions placeholder */ ?>
                        <?= $block->getChildHtml('customer.form.register.newsletter') ?>
                    <?php endif ?>
    
                    <?php $dob = $block->getLayout()->createBlock(Dob::class) ?>
                    <?php if ($dob->isEnabled()): ?>
                        <?= $dob->setDate($block->getFormData()->getDob())->toHtml() ?>
                    <?php endif ?>
    
                    <?php $taxvat = $block->getLayout()->createBlock(Taxvat::class) ?>
                    <?php if ($taxvat->isEnabled()): ?>
                        <?= $taxvat->setTaxvat($block->getFormData()->getTaxvat())->toHtml() ?>
                    <?php endif ?>
    
                    <?php $gender = $block->getLayout()->createBlock(Gender::class) ?>
                    <?php if ($gender->isEnabled()): ?>
                        <?= $gender->setGender($block->getFormData()->getGender())->toHtml() ?>
                    <?php endif ?>
                    <?= $block->getChildHtml('fieldset_create_info_additional') ?>
                </fieldset>
            </div>
            <?php if ($block->getShowAddressFields()): ?>
                <fieldset class="my-8 card bg-ahy-yellow-card">
                    <legend class="contents">
                        <span>
                            <?= $escaper->escapeHtml(__('Address Information')) ?>
                        </span>
                    </legend>
                    <input type="hidden" name="create_address" value="1"/>
    
                    <?php $company = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Company::class) ?>
                    <?php if ($company->isEnabled()): ?>
                        <?= $company->setCompany($block->getFormData()->getCompany())->toHtml() ?>
                    <?php endif ?>
    
                    <?php $telephone = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Telephone::class) ?>
                    <?php if ($telephone->isEnabled()): ?>
                        <?= $telephone->setTelephone($block->getFormData()->getTelephone())->toHtml() ?>
                    <?php endif ?>
    
                    <?php $fax = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Fax::class) ?>
                    <?php if ($fax->isEnabled()): ?>
                        <?= $fax->setFax($block->getFormData()->getFax())->toHtml() ?>
                    <?php endif ?>
                    <?php $streetValidationClass =
                        $this->helper(Address::class)->getAttributeValidationClass(
                            'street'
                        ); ?>
                    <div class="field field-reserved street required">
                        <label for="street_1" class="label"><span><?= /* @noEscape */
                                $block->getAttributeData()->getFrontendLabel('street') ?></span></label>
                        <div class="control">
                            <input type="text" name="street[]"
                                   value="<?= $escaper->escapeHtmlAttr($block->getFormData()->getStreet(0)) ?>"
                                   title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('street') ?>"
                                   id="street_1"
                                   class="form-input <?= $escaper->escapeHtmlAttr($streetValidationClass) ?>">
                            <div class="nested">
                                <?php $streetValidationClass =
                                    trim(str_replace('required-entry', '', $streetValidationClass)); ?>
                                <?php for ($i = 2, $n = $this->helper(Address::class)->getStreetLines(); $i <= $n; $i++): ?>
                                    <div class="field additional">
                                        <label class="label" for="street_<?= /* @noEscape */ $i ?>">
                                            <span><?= $escaper->escapeHtml(__('Address')) ?></span>
                                        </label>
                                        <div class="control">
                                            <input type="text" name="street[]"
                                                   value="<?= $escaper->escapeHtmlAttr($block
                                                       ->getFormData()
                                                       ->getStreetLine($i - 1)) ?>"
                                                   title="<?= $escaper
                                                       ->escapeHtmlAttr(__('Street Address %1', $i)) ?>"
                                                   id="street_<?= (int) $i ?>"
                                                   class="form-input <?= $escaper
                                                       ->escapeHtmlAttr($streetValidationClass) ?>"
                                            >
                                        </div>
                                    </div>
                                <?php endfor; ?>
                            </div>
                        </div>
                    </div>
    
                    <div class="field field-reserved required">
                        <label for="city" class="label">
                            <span>
                                <?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?>
                            </span>
                        </label>
                        <div class="control">
                            <input type="text" name="city"
                                   value="<?= $escaper->escapeHtmlAttr($block->getFormData()->getCity()) ?>"
                                   title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?>"
                                   class="form-input <?= $escaper->escapeHtmlAttr($this
                                       ->helper(Address::class)
                                       ->getAttributeValidationClass('city')) ?>"
                                   id="city">
    
                        </div>
                    </div>
    
                    <div class="field field-reserved region w-full"
                          x-cloak
                          x-show="(hasAvailableRegions() && isRegionRequired) || showOptionalRegions"
                    >
                        <label class="label" for="region_id">
                            <span><?= /* @noEscape */ $regionLabel ?></span>
                        </label>
                        <div class="control">
                            <template x-if="hasAvailableRegions() && (isRegionRequired || showOptionalRegions)">
                                <select id="region_id" name="region_id"
                                        title="<?= /* @noEscape */ $regionLabel ?>"
                                        class="form-select validate-select region_id"
                                        x-ref="region_id"
                                        x-model="selectedRegion"
                                        @change="$refs.region.value = availableRegions[selectedRegion].name"
                                >
                                    <option value=""><?= $escaper->escapeHtml(__('Please select a region, state or province.')) ?></option>
                                    <template x-for="regionId in Object.keys(availableRegions)">
                                        <?php /* in alpine v3, if the bound props update, the template body gets evaluated before the template condition */ ?>
                                        <?php /* because of this it is required to check if availableRegions[regionId] is set */ ?>
                                        <option :value="regionId"
                                                :name="availableRegions[regionId] && availableRegions[regionId].name"
                                                x-text="availableRegions[regionId] && availableRegions[regionId].name"
                                                :selected="selectedRegion === regionId"
                                        >
                                        </option>
                                    </template>
                                </select>
                            </template>
                            <input :type="hasAvailableRegions() && (isRegionRequired || showOptionalRegions) ? 'hidden' : 'text'"
                                   id="region"
                                   name="region"
                                   x-ref="region"
                                   value="<?= $escaper->escapeHtmlAttr($block->getRegion()) ?>"
                                   title="<?= /* @noEscape */ $regionLabel ?>"
                                   class="form-input"
                                   :required="isRegionRequired"
                            />
                        </div>
                    </div>
    
                    <div class="field field-reserved zip w-full">
                        <label class="label" for="zip">
                        <span>
                            <?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?>
                        </span>
                        </label>
                        <div class="control">
                            <input type="text"
                                   name="postcode"
                                   x-ref="postcode"
                                   value=""
                                   title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?>"
                                   id="zip"
                                   :required="isZipRequired"
                                   @change="onChange"
                                   data-validate='{"postcode": true}'
                            class="form-input validate-zip-international
                            <?= $escaper->escapeHtmlAttr($this->helper(Address::class)->getAttributeValidationClass('postcode')) ?>">
                        </div>
                    </div>
    
                    <div class="field field-reserved country w-full">
                        <label class="label" for="country">
                        <span>
                            <?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('country_id') ?>
                        </span>
                        </label>
                        <div class="control">
                            <?php $countries = $block
                                ->getCountryCollection()
                                ->setForegroundCountries($block->getTopDestinations())
                                ->toOptionArray();
                            ?>
                            <select name="country_id"
                                    id="country"
                                    title="Country"
                                    required
                                    class="form-select"
                                    x-ref="country_id"
                                    @change="changeCountry($event.target)"
                            >
                                <?php foreach ($countries as $country): ?>
                                    <option name="<?= /** @noEscape */ $country['label'] ?>"
                                            value="<?= /** @noEscape */ $country['value'] ?>"
                                            data-is-zip-required="<?= (isset($country['is_zipcode_optional'])) ? '0' : '1' ?>"
                                            data-is-region-required="<?= (isset($country['is_region_required'])) ? '1' : '0' ?>"
                                        <?= ($block->getCountryId() ===  $country['value']) ? 'selected="selected"' : '' ?>
                                    >
                                        <?= /** @noEscape */ $country['label'] ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <?php $addressAttributes = $block->getChildBlock('customer_form_address_user_attributes'); ?>
                    <?php if ($addressAttributes): ?>
                        <?php $addressAttributes->setEntityType('customer_address'); ?>
                        <?php $addressAttributes->setFieldIdFormat('address:%1$s')->setFieldNameFormat('address[%1$s]'); ?>
                        <?php $block->restoreSessionData($addressAttributes->getMetadataForm(), 'address'); ?>
                        <?= $addressAttributes->setShowContainer(false)->toHtml() ?>
                    <?php endif; ?>
                    <input type="hidden" name="default_billing" value="1">
                    <input type="hidden" name="default_shipping" value="1">
                </fieldset>
            <?php endif; ?>
            <div class="flex py-6 px-12 ">
                <button type="submit" class="btn ahy-custom-btn font-bold bg-ahy-red hover:bg-ahy-red-light h-12 rounded-full w-full focus:ring-transparent disabled:opacity-75"
                    title="<?= $escaper->escapeHtmlAttr(__('Create an Account')) ?>"
                    <?php if ($createAccountButtonViewModel->disabled()): ?> disabled="disabled" data-recaptcha-btn<?php endif; ?>
                >
                    <span class="w-full text-sm py-3 md:py-0"><?= $escaper->escapeHtml(__('Create Account')) ?></span>
                </button>
            </div>
            <div class="terms-and-condition px-12">
                <p class="text-center text-ahy-blue text-sm font-medium">
                    When you create an account, you agree to Everest’s <a href="/terms-and-conditions" class="underline underline-offset-3">Terms of Use</a> and acknowledge you have read its <a href="/privacy-policy" class="underline underline-offset-4">Privacy Policy.</a>
                </p>
            </div>
        </form>
    
        <script>
            function initForm() {
                return {
                    errors: 0,
                    hasCaptchaToken: 0,
                    showPassword: false,
                    showPasswordConfirm: false,
                    submitForm() {
                        this.validate()
                            .then(() => {
                                // Do not rename $form, the variable is expected to be declared in the recaptcha output
                                const $form = document.querySelector('#<?= $escaper->escapeJs($formId) ?>');
                                <?= $recaptcha ? $recaptcha->getValidationJsHtml(ReCaptcha::RECAPTCHA_FORM_ID_CUSTOMER_CREATE) : '' ?>
    
                                if (this.errors === 0) {
                                    $form.submit();
                                }
                            })
                            .catch((invalid) => {
                                if (invalid.length > 0) {
                                    invalid[0].focus();
                                }
                            });
                    },
                    <?php if ($block->getShowAddressFields()): ?>
                    directoryData: {},
                    availableRegions: {},
                    selectedRegion: <?= $escaper->escapeJs($block->getRegion() ?: 0) ?>,
                    isZipRequired: true,
                    isRegionRequired: true,
                    showOptionalRegions: <?= $showOptionalRegions ? 'true' : 'false' ?>,
                    onPrivateContentLoaded(data) {
                        this.directoryData = data['directory-data'] || {};
    
                        <?php if ($block->getCountryId()): ?>
                        this.setCountry(this.$refs['country_id'], '<?= $escaper->escapeJs($block->getRegion()) ?>');
                        <?php endif; ?>
    
                    },
                    setRegionInputValue(regionName) {
                        this.$nextTick(() => {
                            const regionInputElement = this.$refs['region'];
                            if (regionInputElement) {
                                regionInputElement.value = regionName;
                            }
                        })
                    },
                    setCountry(countrySelectElement, initialRegion) {
                        const selectedOption = countrySelectElement.options[countrySelectElement.selectedIndex];
                        const countryCode = countrySelectElement.value;
                        const countryData = this.directoryData[countryCode] || false;
    
                        if (!countryData) {
                            this.setRegionInputValue('');
                            return;
                        }
    
                        this.isZipRequired = selectedOption.dataset.isZipRequired === '1';
                        this.isRegionRequired = selectedOption.dataset.isRegionRequired === '1';
    
                        this.availableRegions = countryData.regions || {};
    
                        const initialRegionId = Object.keys(this.availableRegions).filter(regionId => this.availableRegions[regionId].name === initialRegion)[0];
                        this.selectedRegion = initialRegionId || '0';
                        this.setRegionInputValue(initialRegionId && this.availableRegions[initialRegionId].name || '');
    
                    },
                    changeCountry(countrySelectElement, initialRegion) {
                        this.setCountry(countrySelectElement, initialRegion);
    
                        this.validateCountryDependentFields();
                    },
                    validateCountryDependentFields() {
                        this.$nextTick(() => {
                            <?php /* Reinitialize validation rules for fields that depend on the country */ ?>
                            this.fields['postcode'] && this.removeMessages(this.fields['postcode'])
                            this.fields['region'] && this.removeMessages(this.fields['region'])
                            delete this.fields['postcode'];
                            delete this.fields['region'];
                            <?php /* Initialize country_id, too, because the postcode validation depends on it */ ?>
                            this.setupField(this.$refs['country_id']);
                            this.setupField(this.$refs['postcode']);
                            this.setupField(this.$refs['region']);
    
                            this.fields['postcode'] && this.validateField(this.fields['postcode']);
                            this.fields['region'] && this.validateField(this.fields['region']);
                        })
                    },
                    hasAvailableRegions() {
                        return Object.keys(this.availableRegions).length > 0;
                    }
                    <?php endif; ?>
                }
            }
    
            window.addEventListener('DOMContentLoaded', () => {
    
                hyva.formValidation.addRule('telephone', (value, options) => {
                    const phoneNumber = value.trim().replace(' ', '');
                    if (phoneNumber && phoneNumber.length < (options.minlength || 3)) {
                        return '<?= $escaper->escapeJs(__('The telephone number is too short.')) ?>';
                    }
    
                    return true;
                });
    
                const postCodeSpecs = <?= /* @noEscape */ $block->getPostCodeConfig()->getSerializedPostCodes() ?>;
    
                hyva.formValidation.addRule('postcode', (postCode, options, field, context) => {
                    context.removeMessages(field, 'postcode-warning')
                    const countryId = (context.fields['country_id'] && context.fields['country_id'].element.value),
                        validatedPostCodeExamples = [],
                        countryPostCodeSpecs = countryId && postCodeSpecs ? postCodeSpecs[countryId] : false;
    
                    if (! postCode || ! countryPostCodeSpecs) return true;
    
                    for (const postCodeSpec of Object.values(countryPostCodeSpecs)) {
                        if (new RegExp(postCodeSpec.pattern).test(postCode)) return true;
                        validatedPostCodeExamples.push(postCodeSpec.example);
                    }
                    if (validatedPostCodeExamples) {
                        context.addMessages(field, 'postcode-warning', [
                            '<?= $escaper->escapeJs(__('Provided Zip/Postal Code seems to be invalid.')) ?>',
                            '<?= $escaper->escapeJs(__('Example: ')) ?>' + validatedPostCodeExamples.join('; ') + '. ',
                            '<?= $escaper->escapeJs(__('If you believe it is the right one you can ignore this notice.')) ?>'
                        ]);
                    }
    
                    return true;
                });
            })
        </script>
    </div>
    
    <div class="benefits w-full md:w-1/2 ">
        <h2 class="font-extrabold text-ahy-blue text-xl mt-8 pb-4">Benefits of My Account </h2>
        <div class="flex gap-4 py-4">
            <div class="!h-14 w-14">
                <img src="/media/icons/fast-checkout-icon.png" alt="Enjoy faster checkout" class="aspect-ratio-3/2 object-contain rounded-full ">
            </div>
            <div class="flex w-4/5 flex-col">
                <div class="">
                    <span class="font-bold text-ahy-blue">Enjoy faster checkout</span>
                </div>
                <div class="">
                    <span class="text-ahy-blue">Enjoy express checkout like a Yeti on the move, making your outdoor shopping experience quick and easy! Know your info is stored securely for every order.</span>
                </div>
            </div>
        </div>
        <div class="flex gap-4 py-4 hidden">
            <div class="!h-14 w-14">
                <img src="/media/icons/gift-checkout-icon.png" alt="Earn points and gifts" class="aspect-ratio-3/2 object-contain rounded-full ">
            </div>
            <div class="flex w-4/5 flex-col">
                <div class="">
                    <span class="font-bold text-ahy-blue">Earn points and gifts</span>
                </div>
                <div class="">
                    <span class="text-ahy-blue">Earn rewards points on purchases and redeem them for discount on future orders.</span>
                </div>
            </div>
        </div>
        <div class="flex gap-4 py-4">
            <div class="!h-14 w-14">
                <img src="/media/icons/track-checkout-icon.png" alt="Track your orders" class="aspect-ratio-3/2 object-contain rounded-full ">
            </div>
            <div class="flex w-4/5 flex-col">
                <div class="">
                    <span class="font-bold text-ahy-blue">Track your orders</span>
                </div>
                <div class="">
                    <span class="text-ahy-blue">Easily track and manage your online order.</span>
                </div>
            </div>
        </div>
    </div>
</div>


<style>
    .registration-container fieldset .field.field-reserved ul:last-of-type, form .field.field-reserved ul:last-of-type{
        margin-bottom: 0;
        margin-top: 5px;
    }
    .relative .my-4.text-sm.text-gray-900{
        padding-inline: 3rem;
    }
    .ahy-styling{
        padding-bottom: 1.75rem;
    }
</style>