<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<div class="grid">
    <?php $randomId = rand(); ?>
    <div class="admin__table-wrapper">
        <table class="data-grid">
            <thead>
                <tr>
                    <th class="data-grid-checkbox-cell">
                        <label class="data-grid-checkbox-cell-inner">
                            <input type="checkbox"
                                   id="select-items-<?= /* @noEscape */ $randomId ?>"
                                   onchange="packaging.checkAllItems(this);"
                                   class="shipment checkbox admin__control-checkbox"
                                   title="<?= /* @noEscape */ __('Select All') ?>">
                            <label for="select-items-<?= /* @noEscape */ $randomId ?>"></label>
                        </label>
                    </th>
                    <th class="data-grid-th"><?= /* @noEscape */ __('Product Name') ?></th>
                    <th class="data-grid-th"><?= /* @noEscape */ __('Weight') ?></th>
                    <th class="data-grid-th" <?= $block->displayCustomsValue() ? '' : 'style="display: none;"' ?>>
                        <?= /* @noEscape */ __('Customs Value') ?>
                    </th>
                    <th class="data-grid-th"><?= /* @noEscape */ __('Qty Ordered') ?></th>
                    <th class="data-grid-th"><?= /* @noEscape */ __('Qty') ?></th>
                </tr>
            </thead>
            <tbody>
            <?php $i=0; ?>
            <?php foreach ($block->getCollection() as $item): ?>
                <?php
                $_order = $block->getShipment()->getOrder();
                $marketplaceOrder = $block->getLayout()->createBlock(\Webkul\Marketplace\Block\Order\View::class);
                $sellerOrderslist = $marketplaceOrder->getSellerOrdersList(
                    $_order->getId(),
                    $item->getProductId(),
                    $item->getOrderItemId()
                );
                
                if (!$sellerOrderslist->getSize()) {
                    continue;
                }
                ?>
                
                <?php
                    $_order = $block->getShipment()->getOrder();
                    $_orderItem = $_order->getItemById($item->getOrderItemId());
                ?>
                <?php if ($item->getIsVirtual()
                    || ($_orderItem->isShipSeparately() &&
                    !($_orderItem->getParentItemId() || $_orderItem->getParentItem()))
                    || (!$_orderItem->isShipSeparately() &&
                    ($_orderItem->getParentItemId() || $_orderItem->getParentItem()))) {
                        continue;
                }
                ?>
                <tr class="data-grid-controls-row data-row <?= ($i++ % 2 != 0) ? '_odd-row' : '' ?>">
                    <td class="data-grid-checkbox-cell">
                        <?php $id = $item->getId() ? $item->getId() : $item->getOrderItemId(); ?>
                        <label class="data-grid-checkbox-cell-inner">
                            <input type="checkbox"
                                   name=""
                                   id="select-item-<?= /* @noEscape */ $randomId . '-' . $id ?>"
                                   value="<?= /* @noEscape */ $id ?>"
                                   class="shipment checkbox admin__control-checkbox">
                            <label for="select-item-<?= /* @noEscape */ $randomId . '-' . $id ?>"></label>
                        </label>
                    </td>
                    <td>
                        <?= /* @noEscape */ $item->getName() ?>
                    </td>
                    <td data-role="item-weight">
                        <?= /* @noEscape */ $item->getWeight() ?>
                    </td>
                    <?php
                    if ($block->displayCustomsValue()) {
                        $customsValueDisplay = '';
                        $customsValueValidation = ' validate-zero-or-greater ';
                    } else {
                        $customsValueDisplay = ' style="display: none;" ';
                        $customsValueValidation = '';
                    }

                    ?>
                    <td <?= /* @noEscape */ $customsValueDisplay ?>>
                        <input type="text"
                               name="customs_value"
                               class="input-text admin__control-text <?= /* @noEscape */ $customsValueValidation ?>"
                               value="<?= /* @noEscape */ $block->formatPrice($item->getPrice()) ?>"
                               size="10"
                               onblur="packaging.recalcContainerWeightAndCustomsValue(this);">
                    </td>
                    <td>
                        <?= /* @escapeNotVerified */ $item->getOrderItem()->getQtyOrdered()*1 ?>
                    </td>
                    <td>
                        <input type="hidden" name="price" value="<?= /* @noEscape */ $item->getPrice() ?>">
                        <input type="text"
                               name="qty"
                               value="<?= /* @escapeNotVerified */ $item->getQty()*1 ?>"
                               class="shipment input-text admin__control-text qty<?php
                                if ($item->getOrderItem()->getIsQtyDecimal()): ?> qty-decimal<?php endif ?>">&nbsp;
                        <button type="button" class="shipment action-delete" data-action="package-delete-item" 
                        onclick="packaging.deleteItem(this);" style="display:none;">
                            <span><?= /* @noEscape */ __('Delete') ?></span>
                        </button>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
