<div class="page-main-actions">
    <div class="page-actions-placeholder"></div>
    <div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
    <div class="page-actions-inner" data-title="Add Assign Product">
    <div class="page-actions-buttons add-assign-button">
    <a href="<?=/* @noEscape */$block->getUrl('mpassignproduct/product/view')?>">
        <span class="label wk-assignproduct-action">
            <?=/* @noEscape */__('Add Assign Product')?>
        </span>
        </a>
    </div>
    </div>
    </div>
</div>
