<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpAssignProduct
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<?php
    $mpAssignBlock = $block->getLayout()->createBlock(\Webkul\MpAssignProduct\Block\Link::class);
    $productId = $block->getProduct()->getId();
    $helper = $mpAssignBlock->getHelperObject();
    $collection = $helper->getAssignProductCollection($productId);
    $collection->addFieldToFilter('main_table.status', 1);
    $totalSellers = $collection->getSize();
    $newProdId = $collection->getFirstItem()->getProductId();
    $doesHaveUsedProductPrice = $helper->getUsedProductPrice($newProdId);
?>
<?php if ($totalSellers > 0): ?>
    <div class="wk-ap-price-block">
        <div class="wk-ap-available-sellers">
            <?php if ($doesHaveUsedProductPrice) { ?><p>
                <?= $escaper->escapeHtml(__('From '.$doesHaveUsedProductPrice)); ?>
            </p><?php } ?>
            <a href="#wk_list_header">
                <?= $escaper->escapeHtml(__('Available from %1 more seller(s)', $totalSellers));  ?>
            </a>
        </div>
    </div>
<?php endif; ?>
