<section class="no-route-page py-24 flex flex-col justify-center items-center">
    <div class="oops-sorry flex flex-col justify-center items-center text-ahy-blue">
        <div class="">
            <img src="/media/404-page/yeti-search-icon.svg" alt="yeti-search-icon" width="80">
        </div>
        <div class="details-404 text-center">
            <h1 class="text-6xl font-bold uppercase">
                oops, sorry!
            </h1>
            <p class="">We can’t find the page you are looking for.</p>
        </div>
    </div>
    <div class="category-callout py-8">
        <div class="text-center pt-4 pb-8">
            <p class="font-bold">
                Let's get you back on track!
            </p>
        </div>
        <div class="flex space-x-8">
            <div class="hunting">
                <a href="/" class="flex flex-col space-y-4 justify-center items-center">
                    <img src="/media/404-page/category-icon-hunting.png" alt="hunting" class="rounded-full" width="150" height="150">
                    <p class="font-bold capitalize">
                        hunting
                    </p>
                </a>
            </div>
            <div class="shooting-sports">
                <a href="/" class="flex flex-col space-y-4 justify-center items-center">
                    <img src="/media/404-page/category-icon-shooting-sports.png" alt="shooting-sports" class="rounded-full" width="150" height="150">
                    <p class="font-bold capitalize">
                        shooting sports
                    </p>
                </a>
            </div>
            <div class="camping">
                <a href="/" class="flex flex-col space-y-4 justify-center items-center">
                    <img src="/media/404-page/category-icon-camping.png" alt="camping" class="rounded-full" width="150" height="150">
                    <p class="font-bold capitalize">
                        camping
                    </p>
                </a>
            </div>
            <div class="fishing">
                <a href="/" class="flex flex-col space-y-4 justify-center items-center">
                    <img src="/media/404-page/category-icon-fishing.png" alt="fishing" class="rounded-full" width="150" height="150">
                    <p class="font-bold capitalize">
                        fishing
                    </p>
                </a>
            </div>
        </div>
    </div>
    <div class="first-order-coupon-code">
        <div class="w-3/4 m-auto py-4 space-y-6">
            <div style="max-width: 600px;" class="klaviyo-embed">
                <script async type="text/javascript" src="https://static.klaviyo.com/onsite/js/klaviyo.js?company_id=XbQwFK"></script>
                <div class="klaviyo-form-XmXfRr"></div>
            </div>
        </div>
    </div>
</section>
<style>
    .klaviyo-embed span{font-size:1.25rem;}
    .klaviyo-embed h2 span{font-size:2rem;}

</style>