<section class="terms-and-condition space-y-4 text-ahy-blue">
    <div class="md:text-center sm:text-left py-20 md:py-24 xl:pt-10 pb-0">
        <h1 class="text-6xl leading-none sm:leading-none sm:text-8xl md:text-[120px] lg:text-[160px] xl:text-[210px] uppercase font-league-gothic">
            The independent outdoor marketplace 
        </h1>
        <p class="sm:text-2xl text-xs md:text-3xl !leading-normal font-extrabold uppercase mt-4">
            By rights-valued people
        </p>
    </div>
    <div class="w-full flex m-auto flex-col">
        <div class="space-y-8 pb-12 md:pb-24 w-full flex flex-col md:flex-row text-ahy-blue justify-between items-center">
            <div class="w-full md:w-1/2 md:text-center">
                <h2 class="font-extrabold text-3xl md:text-6xl uppercase md:pb-7 py-5 mt-2 md:mt-0">Howdy!</h2>
                <p class="tracking-wide w-full md:w-[82%] m-auto leading-[1.75] pb-4 md:text-xl text-sm">
                “I founded Everest with the mission of helping our rights-valued community thrive. You see folks today are struggling with a culture of bulling fueled by algorithmic echo chambers that are driving people apart. We are here to unite the community and help them become better versions of themselves by connecting with the outdoors that shapes them.”
                </p>
                <img class="flex justify-center max-w-[120px] m-auto md:max-w-none midway-usa-foundation w-auto" width="250" height="250" src="/media/about-us/bill-signature.png" alt="Bill Voss signature">
                <p class="md:text-xl text-sm">— Bill Voss. Founder and CEO</p>
            </div>
            <div class="bill-voss w-full md:w-1/3 order-first md:order-last">
                <img src="/media/about-us/bill-voss-ceo-everest.jpg" width="250" height="250" alt="Bill Voss CEO" class="w-auto">
            </div>
        </div>
        <div class="space-y-8 pb-12 md:pb-24 w-full flex flex-col md:flex-row text-ahy-blue justify-between items-center">
            <div class="bill-voss w-full md:w-1/3 ">
                <img src="/media/about-us/everest-mission.jpg" width="250" height="250" alt="everest-mission" class="w-auto">
            </div>
            <div class="w-full md:w-1/2 md:text-center">
                <h2 class="font-extrabold text-3xl md:text-6xl  uppercase  md:pb-7 py-5">Our mission</h2>
                <p class="tracking-wide w-full md:w-[82%] m-auto leading-[1.75] pb-4 md:text-xl text-sm order-first md:order-last">
                We are dedicated to building a marketplace filled with the community passion project for all outdoors. After all, the outdoors is for all. So we team up with storytellers and community causes to help people become better versions of themselves through empowerment and developing a healthy relationship with food. Together, we are building the outdoor marketplace dedicated to helping everyone climb their Everest.
                </p>
            </div>
        </div>
        <div class="space-y-8 pb-24 w-full flex flex-col md:flex-row text-ahy-blue justify-between items-center">
            <div class="w-full md:w-1/2 md:text-center ">
                <h2 class="font-extrabold text-3xl md:text-6xl uppercase md:pb-7 py-5">SUPPORT VALUES</h2>
                <p class="tracking-wide w-full md:w-[82%] m-auto leading-[1.75] pb-4 md:text-xl text-sm ">
                    Everest commits to giving back. Every quarter, we donate a portion of our revenue to projects and organizations that are crucial to the outdoors. Philanthropic programs, local communities, charitable work, and causes that make a significant impact. We do this because we know that TOGETHER as one clan, we make the outdoors even greater.
                </p>
                <p class="text-xl"></p>
                <a href="/give-back-fund">
                    <button class="border-ahy-blue text-ahy-blue rounded-full border-2 px-6 py-2 text-[14px] font-extrabold capitalize my-4 hover:shadow-[#0d2f47_0px_0px_0px_1px_inset]">causes We Back</button>
                </a> 
            </div>
            <div class="bill-voss w-full md:w-1/3 order-first md:order-last pb-5 md:pb-0">
                <img src="/media/about-us/midway-usa-foundation.jpg" width="250" height="250" alt="Bill Voss CEO" class="w-auto">
            </div>
        </div>
        <div class="space-y-8 pb-24 w-full flex flex-col md:flex-row text-ahy-blue justify-between items-center">
            <div class="bill-voss w-full md:w-1/3 pb-5 md:pb-0">
            <img src="/media/about-us/support-independent.png" width="250" height="250" alt="Support Independent" class="w-auto">
            </div>
            <div class="w-full md:w-1/2 md:text-center ">
            <img class="flex justify-center sm:py-4 max-w-[240px] w-auto md:max-w-none"src="/media/about-us/everest-sellers.png" width="250" height="250" alt="Everest Sellers" >
                <h2 class="font-extrabold text-3xl md:text-6xl uppercase  md:pb-7 py-5">SUPPORT </br>INDEPENDENTS</h2>
                <p class="tracking-wide w-full md:w-[82%] m-auto leading-[1.75] pb-4 md:text-xl text-sm">
                    Everest helps outdoor brands and sellers build relationships and trust with our piece of the outdoor community. Our reach puts quality products in front of thousands of explorers who are seeking superior gear.
                </p>
                <a href="/storefront">
                    <button class="border-ahy-blue text-ahy-blue rounded-full border-2 px-6 py-2 text-[14px] font-extrabold capitalize my-4 hover:shadow-[#0d2f47_0px_0px_0px_1px_inset]">Become A Seller </button>
                </a>
            </div>
        </div>
        <!-- <div class="space-y-8 pb-24 w-full flex flex-col md:flex-row text-ahy-blue justify-between items-center">
            <div class="w-full md:w-2/5 md:text-center">
                <h2 class="font-extrabold text-6xl uppercase pb-2">CREATOR STORES</h2>
                <p class="tracking-wide w-full md:w-[82%] m-auto leading-[1.75] pb-4 text-xl pb-4">
                    Explorers are different. We journey outside to fuel our need to discover something new. Or, continue our journey to finding something old. To awaken our souls. To feel connected, and maybe, a little bit wild. We're looking for connection. Creators use their imaginative talents to connect explorers to their journeys. We highlight our favorite people in the outdoor community who are building new bridges across the internet. We offer support to creators to continue using their specialized knowledge, insight, and voices.
                </p>
                <p class="text-xl"></p>
                <button class="border-ahy-blue text-ahy-blue rounded-full border-2 px-6 py-2 text-[14px] font-extrabold capitalize">Explore Creators</button>
                <p class=" py-7"><a class="text-sm underline underline-offset-2">Intrested in a creator store?</a></p>
            </div>
            <div class="bill-voss w-full md:w-1/2">
                <img src="/media/about-us/Omar-Crispy-Avila.png" width="250" height="250" alt="Omar Crispy Avila" class="w-auto">
            </div>
        </div> -->
    </div>
</section>