<section class="accessibility-policy space-y-4 text-ahy-blue">
    <div class="md:text-center sm:text-left py-20 md:pt-24 pb-12">
        <h1 class="text-6xl leading-normal sm:leading-normal sm:text-8xl md:text-[120px] lg:text-[160px] uppercase font-league-gothic">
            ACCESSIBILITY STATEMENT
        </h1>
    </div>
    <div class="lg:w-[56.33%] w-full flex m-auto flex-col">
        <div class="space-y-8 pb-24">
            <p class="tracking-wide leading-[1.75] text-xl font-light">
                At Everest, we believe that everyone should be able to access our websites. We are committed to making our sites accessible to all users, and we are constantly working to conform our site to the standards set out in the Web Content Accessibility Guidelines (WCAG) version 2.1 or other standards as required by the Americans with Disabilities Act ("ADA").
            </p>
            <p class="tracking-wide leading-[1.75] text-xl font-light">
                If you experience difficulty using or accessing any element of this website, please <a class="underline decoration-1 underline-offset-6" href="/contact">Contact Us.</a> We will work with you to provide the information, item, or transaction you seek through a communication method that is accessible to you and consistent with applicable law (for example, through telephone support).
            </p>
        </div>
    </div>
</section>