<section class="fall-gear-picks text-ahy-blue">
  <!-- Hero section starts -->
  <div class="relative h-auto md:h-[820px] lg:h-[625px] bg-no-repeat bg-[url('media/everestpay/everest-pay-hero-background.png')] bg-cover bg-top py-12 flex items-center justify-center"
      style="background-image: url('/media/everestpay/everest-pay-hero-background.png');">
  >
    <div class="max-w-7xl mx-auto w-full px-4 sm:px-6 hero-title">
      <div class="flex flex-col md:flex-row items-center justify-evenly w-full gap-10 h-full">
        <!-- Left Text -->
        <div class="md:w-1/2 text-white text-left font-poppins flex flex-col justify-center">
          <p class="text-[36px] leading-[42px] pb-4 font-bold leading-tight">
            EverestPay is the smarter payment solution for outdoor customers and merchants.
          </p>
          <p class="mt-4 text-[14px] leading-relaxed w-full">
            EverestPay is a digital payment system that is part of OutdoorWallet.com, a digital wallet dedicated to the outdoor industry with 1.2m registered users.
          </p>
          <div class="mt-6">
            <a href="https://app.bitrail.io/auth/login?&avi=vKKFS6mbxlMbe_0dah6dRP1Qsfda1FBnD9nLbFgzhp4s0vZAOUjIe72dKcRQqdab&consents=user-agreement&msg=&deviceDays=30&client_name=BitRail+Web+App&pg=login" 
               class="inline-flex items-center justify-center bg-ahy-red hover:bg-ahy-red-light text-white font-semibold rounded-full px-12 py-4 text-[14px] shadow-md" >
              Register now
            </a>
          </div>
        </div>
        <!-- Right Content (Payment Options) -->
        <div class="bg-white rounded-xl shadow-lg p-6 md:p-8 space-y-4">
          <!-- EverestPay (Visually Selected) -->
          <div class="flex items-center justify-between rounded-lg border-[3px] border-[#2a67e7] p-6">
            <div class="flex items-center gap-2">
              <div class="relative w-5 h-5 rounded-full bg-[#2a67e7] border-2 border-[#2a67e7]">
                <div class="absolute top-1/2 left-1/2 w-2 h-2 bg-white rounded-full transform -translate-x-1/2 -translate-y-1/2"></div>
              </div>
              <span class="font-semibold text-[14px]">EverestPay</span>
            </div>
            <div class="border border-gray-300 px-2 py-1 flex justify-center items-center w-[100px] sm:w-[157px] rounded-[3px]">
              <img src="/media/everestpay/logo-everestpay2.svg" alt="EverestPay Logo" class="h-6 w-[80px] sm:w-24" />
            </div>
          </div>
          <!-- Credit Card -->
          <div class="flex items-center justify-between rounded-lg border-2 border-gray-400 p-6 gap-8">
            <div class="flex items-center gap-2">
            <div class="w-4 h-4 border-2 border-gray-400 rounded-full shrink-0"></div>
              <span class="font-semibold text-[14px]">Credit Card</span>
            </div>
            <div class="flex gap-2 overflow-x-auto whitespace-nowrap">
              <img src="media/everestpay/everest-pay-masterCard.png" alt="MasterCard"
                   class="h-[24px] w-[40px] sm:h-[30px] sm:w-auto border border-[#8C8C8C] rounded-[3px]" />
              <img src="media/everestpay/everest-pay-visa.png" alt="Visa"
                   class="h-[24px] w-[40px] sm:h-[30px] sm:w-auto border border-[#8C8C8C] rounded-[3px]" />
              <img src="media/everestpay/everest-pay-discover.png" alt="Discover"
                   class="h-[24px] w-[40px] sm:h-[30px] sm:w-auto border border-[#8C8C8C] rounded-[3px]" />
              <img src="media/everestpay/everest-pay-amerricanExpress.png" alt="AmEx"
                   class="h-[24px] w-[40px] sm:h-[30px] sm:w-auto border border-[#8C8C8C] rounded-[3px]" />
            </div>

          </div>
          <!-- PayPal Express -->
          <div class="flex items-center justify-between rounded-lg border-2 border-gray-400 p-6">
            <div class="flex items-center gap-2">
              <div class="w-4 h-4 border-2 border-gray-400 rounded-full"></div>
              <span class="font-semibold text-[14px]">PayPal Express</span>
            </div>
            <img src="/media/everestpay/paypal.svg" alt="PayPal" class="h-[30px] w-[50px] border border-[#8C8C8C] rounded-[3px]" >
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Hero section end -->

<!-- New Section for Customers Start -->
<div class="bg-[#efeadd] py-12 px-4 sm:px-8 md:px-16 lg:px-32">
  <h2 class="text-[#001935] mb-10 text-center text-3xl sm:text-5xl leading-tight sm:leading-[64px] font-league-gothic for-customers-title" >
    FOR CUSTOMERS
  </h2>

  <div class="max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-2 gap-10 text-[#0d2b3e] font-poppins">
    <!-- Left Column -->
    <div class="space-y-6">
      <div class="flex items-start gap-4">
        <img src="/media/everestpay/one-time-registration-icon.svg" alt="One Time Registration"
          class="w-auto max-w-[29px] h-auto mt-1">
        <div>
          <h3 class="font-semibold text-lg">One Time Registration</h3>
          <p class="text-sm">Users register only once and don’t have to type their information in each time they make a purchase.</p>
        </div>
      </div>

      <div class="flex items-start gap-4">
        <img src="/media/everestpay/no-free-or-annual-membership-icon.svg" alt="No Fee"
          class="w-auto max-w-[26px] h-auto mt-1">
        <div>
          <h3 class="font-semibold text-lg">No Fee or Annual Membership</h3>
          <p class="text-sm">EverestPay is free to use.</p>
        </div>
      </div>

      <div class="flex items-start gap-4">
        <img src="/media/everestpay/buy-now-pay-letter-icon.svg" alt="Buy Now Pay Later"
          class="w-auto max-w-[29px] h-auto mt-1">
        <div>
          <h3 class="font-semibold text-lg">Buy Now Pay Later</h3>
          <p class="text-sm">EverestPay will allow customers to use Buy Now Pay Later, track loyalty, redeem points and more.</p>
        </div>
      </div>
    </div>

    <!-- Right Column -->
    <div class="space-y-6">
      <div class="flex items-start gap-4">
        <img src="/media/everestpay/digital-payments-icon.svg" alt="Digital Payments UX"
          class="w-auto max-w-[32px] h-auto mt-1">
        <div>
          <h3 class="font-semibold text-lg">Digital Payments UX</h3>
          <p class="text-sm">Easy to use interface across every device. Payment processing platform securely executes, settles and clears in minutes.</p>
        </div>
      </div>

      <div class="flex items-start gap-4">
        <img src="/media/everestpay/safe-and-secure-icon.svg" alt="Safe and Secure"
          class="w-auto max-w-[32px] h-auto mt-1">
        <div>
          <h3 class="font-semibold text-lg">Safe and Secure</h3>
          <p class="text-sm">24/7 fraud monitoring to help protect your account and keep data secure.</p>
        </div>
      </div>

      <div class="flex items-start gap-4">
        <img src="/media/everestpay/support-outdoor-icon.svg" alt="Supports the Outdoor Industry"
          class="w-auto max-w-[37px] h-auto mt-1">
        <div>
          <h3 class="font-semibold text-lg">Supports the Outdoor Industry</h3>
          <p class="text-sm">EverestPay allows people to shop on thousands of outdoor sites.</p>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- New Section for Customers End -->

<!--How EverestPay works start -->
<div class="bg-white py-16 px-6 md:px-20 lg:px-32 text-center">
  <div class="text-3xl md:text-4xl font-extrabold text-[#0d2b3e] mb-16 font-poppins">
    How EverestPay Works for Customers
  </div>
  <!-- Container with max width applied -->
  <div class="max-w-7xl mx-auto">
    <!-- First Row: Add to Cart & Checkout -->
    <div class="grid grid-cols-1 md:grid-cols-2 mb-12 text-[#0d2b3e]">
      <div class="flex flex-col items-center">
        <div class="flex items-center justify-center w-10 h-10 rounded-full bg-[#0d2f47] text-white font-bold text-lg mb-2">1</div>
        <div class="font-bold text-lg mb-2">Add to Cart</div>
        <div class="text-sm mb-6 max-w-xs text-center">
          Customers browse, select, and add items to purchase to their cart.
        </div>
        <div>
          <img src="/media/everestpay/add-to-cart-everest-pay.png" alt="Add to Cart" class="w-full max-w-sm everestpaydesktop mx-auto">
        </div>
      </div>
      <div class="flex flex-col items-center">
        <div class="flex items-center justify-center w-10 h-10 rounded-full bg-[#0d2f47] text-white font-bold text-lg mb-2">2</div>
        <div class="font-bold text-lg mb-2">Checkout</div>
        <div class="text-sm mb-6 max-w-xs text-center">
          Customers can choose traditional payments as well as EverestPay.
        </div>
        <div>
          <img src="/media/everestpay/register-everest-pay.png" alt="Checkout" class="w-full max-w-sm everestpaydesktop mx-auto">
        </div>
      </div>
    </div>
    <!-- Second Row: Register & Transact -->
    <div class="grid grid-cols-1 md:grid-cols-2 text-[#0d2b3e]">
      <div class="flex flex-col items-center">
        <div class="flex items-center justify-center w-10 h-10 rounded-full bg-[#0d2f47] text-white font-bold text-lg mb-2">3</div>
        <div class="font-bold text-lg mb-2">Register</div>
        <div class="text-sm mb-6 max-w-[400px] text-center leading-snug">
          New users register by entering their phone number and linking their bank account or credit card.
        </div>
        <div>
          <img src="/media/everestpay/checkout-everest-pay-image.png" alt="Register" class="w-full max-w-sm everestpaydesktop mx-auto">
        </div>
      </div>
      <div class="flex flex-col items-center">
        <div class="flex items-center justify-center w-10 h-10 rounded-full bg-[#0d2f47] text-white font-bold text-lg mb-2">4</div>
        <div class="font-bold text-lg mb-2">Transact</div>
        <div class="text-sm mb-6 max-w-[400px] text-center leading-snug">
          Follow the steps on the screen and tap/click “place your order” to complete purchase.
        </div>
        <div>
          <img src="/media/everestpay/transact-everest-pay.svg" alt="Transact" class="w-full max-w-sm everestpaydesktop mx-auto">
        </div>
      </div>
    </div>
    <!-- Button -->
    <div style="margin-top: 4rem;">
      <a href="https://app.bitrail.io/signup" style="border: 4px solid black;" class="inline-block text-[#0d2b3e] font-semibold rounded-full px-8 py-3 text-sm hover:bg-[#0d2b3e] hover:text-white transition">
        Register now
      </a>
    </div>
  </div>
</div>
<!-- EverestPay Steps Section end -->

<!-- Mobile Background Section -->
<div
  class="relative w-full h-[700px] bg-cover bg-center flex items-center justify-center md:hidden"
  style="background-image: url('/media/everestpay/Everest-pay-outdoor-mobile-view.png');">
  <div class="w-full px-4">
    <div class="max-w-7xl mx-auto text-white text-center"
         style="font-family: 'League Gothic', sans-serif; font-size: 80px; line-height: 88px;">
      OUTDOOR CENTRIC PAYMENT SOLUTIONS
    </div>
  </div>
</div>

<!-- Desktop Background Section -->
<div
  class="relative w-full h-[500px] lg:h-[600px] bg-cover bg-center flex items-center justify-center hidden md:flex"
  style="background-image: url('/media/everestpay/everest-pay-mask-group.png');">
  <div class="w-full px-4">
    <div class="max-w-7xl mx-auto text-white text-center"
         style="font-family: 'League Gothic', sans-serif; font-size: 80px; line-height: 88px;">
      OUTDOOR CENTRIC PAYMENT SOLUTIONS
    </div>
  </div>
</div>


<!-- For marchants section start -->
<div class="bg-[#efeadd] px-4 py-16 lg:py-24">
  <div class="max-w-7xl mx-auto">
    <h2 class="text-[#001935] mb-12 text-center text-[48px] sm:text-[64px] leading-[48px] sm:leading-[64px] font-league-gothic" >FOR MERCHANTS</h2>
    <div class="flex flex-col md:flex-row md:flex-wrap gap-y-10 my-gap-21">
      <!-- Left column -->
      <div class="md:w-1/2 pr-4 space-y-6">
        <div class="flex items-start gap-3">
          <img src="/media/everestpay/save-on-transaction-ep.svg" alt="Save on Transaction Costs" class="h-6 w-6 mt-1">
          <div>
            <h3 class="font-bold text-[#001935] text-[18px]">Save on Transaction Costs</h3>
            <p class="text-[#001935] text-[16px] leading-relaxed">
              Allows merchants to pay less in transaction fees, and offers a surcharge option to pass some or all credit card transaction fees on to the consumer.
            </p>
          </div>
        </div>
        <div class="flex items-start gap-3">
          <img src="/media/everestpay/loyalty-program-ep.svg" alt="Loyalty Program" class="h-6 w-6 mt-1">
          <div>
            <h3 class="font-bold text-[#001935] text-[18px]">Loyalty Program</h3>
            <p class="text-[#001935] text-[16px] leading-relaxed">
              Offers reward programs that build brands, drive traffic and increase customer retention.
            </p>
          </div>
        </div>
        <div class="flex items-start gap-3">
          <img src="/media/everestpay/reduce-cart-ep.svg" alt="Reduce Cart Abandonment" class="h-6 w-6 mt-1">
          <div>
            <h3 class="font-bold text-[#001935] text-[18px]">Reduce Cart Abandonment</h3>
            <p class="text-[#001935] text-[16px] leading-relaxed">
              EverestPay is making it easier for customers to check in and out on your site using the information already stored in their accounts.
            </p>
          </div>
        </div>
        <div class="flex items-start gap-3">
          <img src="/media/everestpay/support-outdoor-icon.svg" alt="Supports the Outdoor Industry" class="h-6 w-6 mt-1">
          <div>
            <h3 class="font-bold text-[#001935] text-[18px]">Supports the Outdoor Industry</h3>
            <p class="text-[#001935] text-[16px] leading-relaxed">
              EverestPay allows shooting sport products to be transacted on merchants’ sites.
            </p>
          </div>
        </div>
      </div>
      <!-- Right column -->
      <div class="md:w-1/2 md:pl-4 space-y-6">
        <div class="flex items-start gap-3">
          <img src="/media/everestpay/easy-integration-ep.svg" alt="Easy Integration" class="h-6 w-6 mt-1">
          <div>
            <h3 class="font-bold text-[#001935] text-[18px]">Easy Integration</h3>
            <p class="text-[#001935] text-[16px] leading-relaxed">
              Integrate EverestPay without a major time commitment, and without hidden fees or upfront costs. Our technical team provides resources to facilitate the process.
            </p>
          </div>
        </div>
        <div class="flex items-start gap-3">
          <img src="/media/everestpay/will-everest-pay-ep.svg" alt="Will EverestPay Dilute Our Brand?" class="h-6 w-6 mt-1">
          <div>
            <h3 class="font-bold text-[#001935] text-[18px]">Will EverestPay Dilute Our Brand?</h3>
            <p class="text-[#001935] text-[16px] leading-relaxed">
              People already trust Everest and your site. 48% of consumers look for a well-known payment service like EverestPay at checkout. About one in five people abandon orders because they don’t trust the site with their credit card information.
            </p>
          </div>
        </div>
        <div class="flex items-start gap-3">
          <img src="/media/everestpay/what-is-the-roi-ep.svg" alt="What is the ROI of EverestPay?" class="h-6 w-6 mt-1">
          <div>
            <h3 class="font-bold text-[#001935] text-[18px]">What is the ROI of EverestPay?</h3>
            <p class="text-[#001935] text-[16px] leading-relaxed">
              We see a 20% adoption rate within 21 months of launch and an increase on average purchase price and purchase frequency.
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- for marchants section end -->

<!-- EverestPay vs the rest section start -->
<div class="bg-[#dfb897] py-12 px-4" style="padding: 2rem;">
  <div class="max-w-7xl mx-auto">
    <div class="text-center text-2xl md:text-3xl font-bold text-[#001935] mb-10" style="font-size:36px; line-height: 1.2;">
      EverestPay Versus the Rest
    </div>
    <div class="grid grid-cols-1 md:grid-cols-4 gap-6 everestversusrestgrid">
      <!-- AmazonPay -->
      <div class="bg-[#e9ceb7] rounded-xl p-6">
        <h3 class="font-bold text-lg text-[#001935] mb-2" style="font-size: 24px;">AmazonPay Fees</h3>
        <p class="text-sm text-[#001935] mb-4">Credit card merchants per Transaction</p>
        <p class="text-red-600 text-3xl font-bold mb-4" style="font-size: 42px;">6.2% - 9.2%</p>
        <ul class="text-sm text-[#001935] space-y-2">
          <li>• Contactless: 6.2% + $0.30</li>
          <li>• Chargeback and refund fees</li>
          <li><strong>• No firearm or ammo sales allowed</strong></li>
        </ul>
      </div>
      <!-- PayPal -->
      <div class="bg-[#e9ceb7] rounded-xl p-6">
        <h3 class="font-bold text-lg text-[#001935] mb-2" style="font-size: 24px;">PayPal Fees</h3>
        <p class="text-sm text-[#001935] mb-4">Credit card merchants per Transaction</p>
        <p class="text-red-600 text-3xl font-bold mb-4" style="font-size: 42px;">3.49%</p>
        <ul class="text-sm text-[#001935] space-y-2">
          <li>• Merch fees: 3.49%</li>
          <li>• Chargebacks and other fees</li>
          <li><strong>• No firearm or ammo sales allowed</strong></li>
        </ul>
      </div>
      <!-- Credit Card -->
      <div class="bg-[#e9ceb7] rounded-xl p-6">
        <h3 class="font-bold text-lg text-[#001935] mb-2" style="font-size: 24px;">Credit Card Fees</h3>
        <p class="text-sm text-[#001935] mb-4" >Credit card merchants per Transaction</p>
        <p class="text-red-600 text-3xl font-bold mb-4" style="font-size: 42px;">3.2 - 7.4%</p>
        <ul class="text-sm text-[#001935] space-y-2">
          <li>• Processing fees: 1.3–3.5%</li>
          <li>• Interchange fees: 1.5–3.3%</li>
          <li>• Payment processing fees: .3–.5%</li>
          <li>• Assessment fees: .14% avg.</li>
          <li>• Chargeback and other fees</li>
        </ul>
      </div>
      <!-- EverestPay -->
      <div class="text-white rounded-xl p-6 flex flex-col justify-between" style="background-color:#0d2f47;">
        <div>
          <div class="flex items-center gap-2 mb-2">
            <img src="/media/everestpay/everest-pay-symbol-logo-red-color-ep.png" alt="Everest Logo" class="h-5 w-5">
            <h3 class="font-bold text-lg" style="font-size: 24px;">EverestPay</h3>
          </div>
          <p class="text-sm mb-4">To EverestPay per Transaction</p>
          <p class="text-3xl font-bold mb-4" style="font-size: 42px;">1 - 2.5%</p>
          <ul class="text-sm space-y-2">
            <li>• Save time</li>
            <li>• Save money</li>
            <li>• Gain users faster</li>
            <li><strong>• All shooting sports and hunting gear allowed</strong></li>
          </ul>
        </div>
        <a href="https://app.bitrail.io/auth/login?&avi=vKKFS6mbxlMbe_0dah6dRP1Qsfda1FBnD9nLbFgzhp4s0vZAOUjIe72dKcRQqdab&consents=user-agreement&msg=&deviceDays=30&client_name=BitRail+Web+App&pg=login"
           class="mt-6 inline-flex items-center justify-center text-white text-sm font-bold py-2 px-6 rounded-full hover:bg-ahy-red-light transition"
           style="height: 60px; background: #D63C3F;">
          Get started
        </a>
      </div>
    </div>
  </div>
</div>
<!-- EverestPay vs the rest section end -->

<!-- EverestPay support heading section start-->
<div class="bg-[#efeadd] px-4 py-24 text-center">
  <div class="max-w-7xl mx-auto">
      <h2
      class="text-[60px] md:text-[72px] lg:text-[80px] text-[#001935] mb-10 leading-tight"
      style="font-family: 'League Gothic', sans-serif; color: #0D2F47;">
      EVERESTPAY SUPPORTS<br />
      BUSINESSES JUST LIKE YOURS.
    </h2>
    <a href="https://app.bitrail.io/signup"
      class="inline-block text-[#001935] text-base md:text-lg font-semibold border-2 border-[#0D2F47] rounded-full px-8 py-2 hover:bg-[#001935] hover:text-white transition duration-300"
      style="border: 4px solid #001935;">
      Register now
    </a>
  </div>
</div>
<!-- EverestPay support heading section end-->


<style>
  .cms-everest-pay .top-container{
    display: none;
  }
  .grid.grid-cols-1.md\:grid-cols-2.text-\[\#0d2b3e\]{
    gap: 47px;
  }
  @media screen and (max-width: 768px) {
    .flex.items-start.gap-4 > img{
      max-width: 20px;
    }
   
    .fall-gear-picks + .py-12.px-4 > div,
    .my-gap-21
    {
      gap: 21px !important;
    }
    
    .for-customers-title{
      font-size:48px;
    }
  }
  @media screen and (min-width: 768px)  and (max-width: 1023px) {
    .everestversusrestgrid{
      grid-template-columns: repeat(2,minmax(0,1fr))
    }
  }
  .everestpaydesktop{
    max-width: 21rem;
  }
  @media screen and (max-width: 340px){
    .hero-title{
      padding-block: 0.6rem;
    }
  }
</style>