<section class="fall-gear-picks space-y-4 pb-12 text-ahy-blue">
    <div class="md:text-center sm:text-left pt-10 pb-12 md:py-16 xl:pt-3">
        <div class="badge-logo flex md:justify-center">
            <img src="/media/fall_gear_picks/badge.jpg" width="100" alt="Badge" />
        </div>
        <h1 class="text-6xl leading-none sm:text-8xl md:text-[120px] lg:text-[160px] uppercase font-league-gothic">Winter Gear Picks</h1>
        <p class="font-light pb-8">By Rights-Valued People</p>
        <p class="font-light text-xl md:text-3xl w-full md:w-3/4 m-auto pb-8">Gear up for cold transitions and shorter days: your ultimate solutions for hunting, camping, shooting sports & more.</p>
        <div class="badge-logo flex md:justify-center">
            <img src="/media/wysiwyg/free-decal-pdp-banner.jpeg" class="lg:w-4/6 m-auto" alt="Free Gift Banner" />
        </div>
    </div>
    <div class="pack-list flex gap-x-4 gap-y-6 flex-wrap justify-center">
        <div class="pack-list-items w-full sm:w-[48%] md:w-[31%] lg:w-[23%] xl:w-[24%] card bg-ahy-yellow-card pt-6 pb-0 px-0 rounded-lg">
            <div class="font-bold capitalize text-xl pb-4 px-6 h-[72px] 2xl:h-auto"><a href="/marketplace/seller/profile/shop/WildWaterFlyFishing" class="hover:underline underline-offset-6">Fall Trout
                    Fishing</a></div>
            <div class="pb-4 px-6 pack-item-details h-[110px] md:h-[140px] xl:h-[110px]">Save on high-quality fly fishing kits, rods, reels, tippet, and more with Wild Water Fly Fishing</div>
            <div class="pb-4 px-6">
                <a href="/marketplace/seller/profile/shop/WildWaterFlyFishing" class="">
                    <button class="border-3 border-ahy-blue rounded-full font-bold text-sm w-36 h-12 hover:shadow-[#0d2f47_0px_0px_0px_1px_inset]">Explore</button>
                </a>
            </div>
            <div class="">
                <a href="/marketplace/seller/profile/shop/WildWaterFlyFishing" class=""><img src="/media/fall_gear_picks/fly-fishing-img.jpg" class="hover:brightness-110 hover:mix-blend-darken m-auto rounded-lg" alt="Badge" /></a>
            </div>
        </div>
        <div class="pack-list-items w-full sm:w-[48%] md:w-[31%] lg:w-[23%] xl:w-[24%] card bg-ahy-yellow-card pt-6 pb-0 px-0 rounded-lg">
            <div class="font-bold capitalize text-xl pb-4 px-6 h-[72px] 2xl:h-auto"><a href="/search/?q=Streamlight&productListPgNo=1" class="hover:underline underline-offset-6">Streamlight</a></div>
            <div class="pb-4 px-6 pack-item-details h-[110px] md:h-[140px] xl:h-[110px]">Headlamps, lanterns, flashlights and tactical mounted lights from Streamlight.</div>
            <div class="pb-4 px-6">
                <a href="/search/?q=Streamlight&productListPgNo=1" class="">
                    <button class="border-3 border-ahy-blue rounded-full font-bold text-sm w-36 h-12 hover:shadow-[#0d2f47_0px_0px_0px_1px_inset]">Explore</button>
                </a>
            </div>
            <div class="">
                <a href="/search/?q=Streamlight&productListPgNo=1" class=""><img src="/media/fall_gear_picks/streamlight-img.jpg" class="hover:brightness-110 hover:mix-blend-darken m-auto rounded-lg" alt="Badge" /></a>
            </div>
        </div>
        <div class="pack-list-items w-full sm:w-[48%] md:w-[31%] lg:w-[23%] xl:w-[24%] card bg-ahy-yellow-card pt-6 pb-0 px-0 rounded-lg">
            <div class="font-bold capitalize text-xl pb-4 px-6 h-[72px] 2xl:h-auto"><a href="/forloh" class="hover:underline underline-offset-6">FORLOH Hunting</a></div>
            <div class="pb-4 px-6 pack-item-details h-[110px] md:h-[140px] xl:h-[110px]">Discover temperature regulating, quick-drying gear with unmatched breathability.</div>
            <div class="pb-4 px-6">
                <a href="/forloh" class="">
                    <button class="border-3 border-ahy-blue rounded-full font-bold text-sm w-36 h-12 hover:shadow-[#0d2f47_0px_0px_0px_1px_inset]">Explore</button>
                </a>
            </div>
            <div class="">
                <a href="/forloh" class=""><img src="/media/fall_gear_picks/forloh-img.jpg" class="hover:brightness-110 hover:mix-blend-darken m-auto rounded-lg" alt="Badge" /></a>
            </div>
        </div>
        <div class="pack-list-items w-full sm:w-[48%] md:w-[31%] lg:w-[23%] xl:w-[24%] card bg-ahy-yellow-card pt-6 pb-0 px-0 rounded-lg">
            <div class="font-bold capitalize text-xl pb-4 px-6 h-[72px] 2xl:h-auto"><a href="/outdoor-gear/patches-decals.html" class="hover:underline underline-offset-6">Decals for Crowd Haters</a>
            </div>
            <div class="pb-4 px-6 pack-item-details h-[110px] md:h-[140px] xl:h-[110px]">Badges of honor for those who'd rather be lost in the woods than lost in a crowd</div>
            <div class="pb-4 px-6">
                <a href="/outdoor-gear/patches-decals.html" class="">
                    <button class="border-3 border-ahy-blue rounded-full font-bold text-sm w-36 h-12 hover:shadow-[#0d2f47_0px_0px_0px_1px_inset]">Explore</button>
                </a>
            </div>
            <div class="">
                <a href="/outdoor-gear/patches-decals.html" class=""><img src="/media/fall_gear_picks/decals-img.jpg" class="hover:brightness-110 hover:mix-blend-darken m-auto rounded-lg" alt="Badge" /></a>
            </div>
        </div>
        <div class="pack-list-items w-full sm:w-[48%] md:w-[31%] lg:w-[23%] xl:w-[24%] card bg-ahy-yellow-card pt-6 pb-0 px-0 rounded-lg">
            <div class="font-bold capitalize text-xl pb-4 px-6 h-[72px] 2xl:h-auto"><a href="/boating-gear.html?productListPgNo=1&productListFilters=category%3AMarine%20Navigation%20%26%20Instruments"
                    class="hover:underline underline-offset-6">Marine Electronics</a></div>
            <div class="pb-4 px-6 pack-item-details h-[110px] md:h-[140px] xl:h-[110px]">GPS, fishfinders, and depth sounders for precision on the water for every budget.</div>
            <div class="pb-4 px-6">
                <a href="/boating-gear.html?productListPgNo=1&productListFilters=category%3AMarine%20Navigation%20%26%20Instruments" class="">
                    <button class="border-3 border-ahy-blue rounded-full font-bold text-sm w-36 h-12 hover:shadow-[#0d2f47_0px_0px_0px_1px_inset]">Explore</button>
                </a>
            </div>
            <div class="">
                <a href="/boating-gear.html?productListPgNo=1&productListFilters=category%3AMarine%20Navigation%20%26%20Instruments" class=""><img
                        src="/media/fall_gear_picks/marine-electronics-img.jpg" class="hover:brightness-110 hover:mix-blend-darken m-auto rounded-lg" alt="Badge" /></a>
            </div>
        </div>
        <div class="pack-list-items w-full sm:w-[48%] md:w-[31%] lg:w-[23%] xl:w-[24%] card bg-ahy-yellow-card pt-6 pb-0 px-0 rounded-lg">
            <div class="font-bold capitalize text-xl pb-4 px-6 h-[72px] 2xl:h-auto"><a href="/archery.html?productListPgNo=1" class="hover:underline underline-offset-6">All Archery Pro</a></div>
            <div class="pb-4 px-6 pack-item-details h-[110px] md:h-[140px] xl:h-[110px]">Discover everything you need to keep hammering; from crossbows to string fluid.</div>
            <div class="pb-4 px-6">
                <a href="/archery.html?productListPgNo=1" class="">
                    <button class="border-3 border-ahy-blue rounded-full font-bold text-sm w-36 h-12 hover:shadow-[#0d2f47_0px_0px_0px_1px_inset]">Explore</button>
                </a>
            </div>
            <div class="">
                <a href="/archery.html?productListPgNo=1" class=""><img src="/media/fall_gear_picks/archery-img.jpg" class="hover:brightness-110 hover:mix-blend-darken m-auto rounded-lg" alt="Badge" /></a>
            </div>
        </div>
        <div class="pack-list-items w-full sm:w-[48%] md:w-[31%] lg:w-[23%] xl:w-[24%] card bg-ahy-yellow-card pt-6 pb-0 px-0 rounded-lg">
            <div class="font-bold capitalize text-xl pb-4 px-6 h-[72px] 2xl:h-auto"><a href="/primos-the-great-big-can-deer-call.html" class="hover:underline underline-offset-6">Big A#$ Deer Call</a>
            </div>
            <div class="pb-4 px-6 pack-item-details h-[110px] md:h-[140px] xl:h-[110px]">Larger size for louder and long-range Estrus Bleats — for pre-rut, rut and post-rut hunting.</div>
            <div class="pb-4 px-6">
                <a href="/primos-the-great-big-can-deer-call.html" class="">
                    <button class="border-3 border-ahy-blue rounded-full font-bold text-sm w-36 h-12 hover:shadow-[#0d2f47_0px_0px_0px_1px_inset]">Explore</button>
                </a>
            </div>
            <div class="">
                <a href="/primos-the-great-big-can-deer-call.html" class=""><img src="/media/fall_gear_picks/deer-call-img.jpg" class="hover:brightness-110 hover:mix-blend-darken m-auto rounded-lg" alt="Badge" /></a>
            </div>
        </div>
        <div class="pack-list-items w-full sm:w-[48%] md:w-[31%] lg:w-[23%] xl:w-[24%] card bg-ahy-yellow-card pt-6 pb-0 px-0 rounded-lg">
            <div class="font-bold capitalize text-xl pb-4 px-6 h-[72px] 2xl:h-auto"><a href="/search/?q=coffee&productListPgNo=1&productListFilters=category%3ACoffee%20%26%20Tea"
                    class="hover:underline underline-offset-6">Caffeine for
                    Campers</a></div>
            <div class="pb-4 px-6 pack-item-details h-[110px] md:h-[140px] xl:h-[110px]">Boost your backpacking and long term survival food, emergency food kits.</div>
            <div class="pb-4 px-6">
                <a href="/search/?q=coffee&productListPgNo=1&productListFilters=category%3ACoffee%20%26%20Tea" class="">
                    <button class="border-3 border-ahy-blue rounded-full font-bold text-sm w-36 h-12 hover:shadow-[#0d2f47_0px_0px_0px_1px_inset]">Explore</button>
                </a>
            </div>
            <div class="">
                <a href="/search/?q=coffee&productListPgNo=1&productListFilters=category%3ACoffee%20%26%20Tea" class=""><img src="/media/fall_gear_picks/coffee-img.jpg" class="hover:brightness-110 hover:mix-blend-darken m-auto rounded-lg"
                        alt="Badge" /></a>
            </div>
        </div>
        <div class="pack-list-items w-full sm:w-[48%] md:w-[31%] lg:w-[23%] xl:w-[24%] card bg-ahy-yellow-card pt-6 pb-0 px-0 rounded-lg">
            <div class="font-bold capitalize text-xl pb-4 px-6 h-[72px] 2xl:h-auto"><a href="/steyr-3x-optic-aug-a3-m1.html" class="hover:underline underline-offset-6">Amplify the Steyr</a></div>
            <div class="pb-4 px-6 pack-item-details h-[110px] md:h-[140px] xl:h-[110px]">Steyr 3X Optic AUG A3 M1 for boosting hunting precision and accuracy.</div>
            <div class="pb-4 px-6">
                <a href="/steyr-3x-optic-aug-a3-m1.html" class="">
                    <button class="border-3 border-ahy-blue rounded-full font-bold text-sm w-36 h-12 hover:shadow-[#0d2f47_0px_0px_0px_1px_inset]">Explore</button>
                </a>
            </div>
            <div class="">
                <a href="/steyr-3x-optic-aug-a3-m1.html" class=""><img src="/media/fall_gear_picks/optics-img.jpg" class="hover:brightness-110 hover:mix-blend-darken m-auto rounded-lg" alt="Badge" /></a>
            </div>
        </div>
        <div class="pack-list-items w-full sm:w-[48%] md:w-[31%] lg:w-[23%] xl:w-[24%] card bg-ahy-yellow-card pt-6 pb-0 px-0 rounded-lg">
            <div class="font-bold capitalize text-xl pb-4 px-6 h-[72px] 2xl:h-auto"><a href="/spypoint-force-pro-trail-camera.html" class="hover:underline underline-offset-6">Supreme Hunting
                    Clarity</a></div>
            <div class="pb-4 px-6 pack-item-details h-[110px] md:h-[140px] xl:h-[110px]">Spypoint FORCE-PRO Trail Camera—the hunting game just got a pixel-perfect upgrade.</div>
            <div class="pb-4 px-6">
                <a href="/spypoint-force-pro-trail-camera.html" class="">
                    <button class="border-3 border-ahy-blue rounded-full font-bold text-sm w-36 h-12 hover:shadow-[#0d2f47_0px_0px_0px_1px_inset]">Explore</button>
                </a>
            </div>
            <div class="">
                <a href="/spypoint-force-pro-trail-camera.html" class=""><img src="/media/fall_gear_picks/trial-cam-img.jpg" class="hover:brightness-110 hover:mix-blend-darken m-auto rounded-lg" alt="Badge" /></a>
            </div>
        </div>
        <div class="pack-list-items w-full sm:w-[48%] md:w-[31%] lg:w-[23%] xl:w-[24%] card bg-ahy-yellow-card pt-6 pb-0 px-0 rounded-lg">
            <div class="font-bold capitalize text-xl pb-4 px-6 h-[72px] 2xl:h-auto"><a href="/Grillyourassoff" class="hover:underline underline-offset-6">Boost My Meat</a></div>
            <div class="pb-4 px-6 pack-item-details h-[110px] md:h-[140px] xl:h-[110px]">Taste freedom with good a#$ BBQ from Grill Your A#$ Off. Texas pride packs every bottle</div>
            <div class="pb-4 px-6">
                <a href="/Grillyourassoff" class="">
                    <button class="border-3 border-ahy-blue rounded-full font-bold text-sm w-36 h-12 hover:shadow-[#0d2f47_0px_0px_0px_1px_inset]">Explore</button>
                </a>
            </div>
            <div class="">
                <a href="/Grillyourassoff" class=""><img src="/media/fall_gear_picks/gyao-img.jpg" class="hover:brightness-110 hover:mix-blend-darken m-auto rounded-lg" alt="Badge" /></a>
            </div>
        </div>
        <div class="pack-list-items w-full sm:w-[48%] md:w-[31%] lg:w-[23%] xl:w-[24%] card bg-ahy-yellow-card pt-6 pb-0 px-0 rounded-lg">
            <div class="font-bold capitalize text-xl pb-4 px-6 h-[72px] 2xl:h-auto"><a href="/merrell-moab3-earth-mid-hiking-boot.html" class="hover:underline underline-offset-6">Merrell Moab3</a>
            </div>
            <div class="pb-4 px-6 pack-item-details h-[110px] md:h-[140px] xl:h-[110px]">All-terrain outdoor companion offers rugged durability and exceptional waterproof.</div>
            <div class="pb-4 px-6">
                <a href="/merrell-moab3-earth-mid-hiking-boot.html" class="">
                    <button class="border-3 border-ahy-blue rounded-full font-bold text-sm w-36 h-12 hover:shadow-[#0d2f47_0px_0px_0px_1px_inset]">Explore</button>
                </a>
            </div>
            <div class="">
                <a href="/merrell-moab3-earth-mid-hiking-boot.html" class=""><img src="/media/fall_gear_picks/merrel-boots-img.jpg" class="hover:brightness-110 hover:mix-blend-darken m-auto rounded-lg" alt="Badge" /></a>
            </div>
        </div>
    </div>
</section>
