<section class="space-y-4 text-ahy-blue">
    <div class="md:text-center sm:text-left pt-10 pb-12 md:py-22 xl:pb-22">
        <h1 class="text-6xl leading-none  pb-12 sm:leading-none sm:text-8xl md:text-[120px] lg:text-[160px] uppercase font-league-gothic">
            PRICE MATCH GUARANTEE
        </h1>
        <p class="text-xl md:text-2xl font-light">
            Hey, Yetis! Looking for the best prices in the great outdoors?
        </p>
        <p class="text-xl md:text-2xl m-0 font-light">
            Everest has got you covered with our Price Match guarantee.
        </p>
    </div>
    <div class="md:text-center pb-12">
        <p class="text-2xl m-0 font-light ">
            Terms & Conditions:
        </p>
    </div>
    <div class="lg:w-[56.33%] w-full flex m-auto flex-col">
        <div class="space-y-8 pb-24">
            <ul class="tracking-wide space-y-8 list-disc leading-[1.75] text-xl font-light px-5 md:px-0">
                <li class="text-lg md:text-xl ">
                    This guarantee does not apply to guns, ammo, refurbished, damaged, used, special buys, clearance, close out, rebates, misprints, coupons, bonus offers, mail-in offers, bundled offers, quantity
                    offers, and shipping charges.
                </li>
                <li class="text-lg md:text-xl !mt-11">
                    Being a marketplace, the price match availability for items sold by sellers on the platform is at the sole discretion of each seller.
                </li>
                <li class="text-lg md:text-xl !mt-11">
                    Items must be identical (brand, model number, color, pattern, size).
                </li>
                <li class="text-lg md:text-xl !mt-11">
                    Item must be sold by one of the following companies with the item in stock: Bass Pro Shops, Cabela's, Midway USA, Dick's Sporting Goods, REI, Academy Sports + Outdoors, Sportsman's Warehouse, Scheels, Mills Fleet Farm, TacticalGear.com, Rogers Sporting Goods, BlackOvis.com, Cheaper Than Dirt, Palmetto State Armory, Brownells, Opticsplanet, Tackle Warehouse, Tackle Direct, Overton's and West Marine (In stock means the item is available for purchase and shipment that day).
                </li>
                <li class="text-lg md:text-xl !mt-11">
                    We do not price match other auction sites, memberships, marketplace sellers, wholesale, clearance outlets, or liquidation prices.
                </li>
                <li class="text-lg md:text-xl !mt-11">
                    Proof of the retailer's lower advertised price is required. The lower advertised price must be valid at time of match and not be the result of available coupons, rebates, or bundling. We reserve the right to verify identical item's pricing and availability.
                </li>
                <li class="text-lg md:text-xl !mt-11">
                    This guarantee does not apply Thanksgiving Day through Cyber Week, whether offered by Everest.com or a competitor. 
                </li>
                <li class="text-lg md:text-xl !mt-11">
                    Limit of one price match per item per customer.
                </li>
                <li class="text-lg md:text-xl !mt-11">
                    Price matches can be done at time of purchase or within 10 days.
                </li>
                <li class="text-lg md:text-xl !mt-11">
                    Everest.com does not match below the cost of its sellers or brands.
                </li>
                <li class="text-lg md:text-xl !mt-11">
                    Everest.com's decision is final on all price matches; if dissatisfied with our decision, you may return the item if it's within our policy.
                </li>
            </ul>

        </div>
    </div>
</section>