<section class="privacy-policy space-y-4 text-ahy-blue">
    <div class="md:text-center sm:text-left pt-10 pb-20 md:py-24 xl:pb-32 xl:pt-3">
        <h1 class="text-6xl leading-normal sm:leading-normal sm:text-8xl md:text-[120px] lg:text-[160px] xl:text-[210px] uppercase font-league-gothic">
            Returns
        </h1>
        <p class="text-2xl md:text-3xl lg:text-4xl xl:text-5xl !leading-normal font-light">
            Thanks for trekking through Everest.com. We strive for shopping legend status. For returns, check our policy below.
        </p>
    </div>
    <div class="lg:w-[56.33%] w-full flex m-auto flex-col">
        <div class="space-y-8 border-t-3 border-ahy-blue pt-[4.75rem] pb-24">
            <h2 class="font-extrabold text-[2.2rem] leading-none pb-2">RETURNS ELIGIBILITY:</h2>
            <p class="tracking-wide leading-[1.75] text-xl font-light">
                1.1 Only products purchased from Everest.com are eligible for returns.
            </p>
            <p class="tracking-wide leading-[1.75] text-xl font-light">
                1.2 To be eligible for a return, the product must be unused, in its original condition, and in the original packaging.
            </p>
            <p class="tracking-wide leading-[1.75] text-xl font-light">
                1.3 Certain products may be exempt from returns due to hygiene or safety reasons. These may include but are not limited to personal care items, intimate apparel, perishable goods, and software products. Along with firearms and ammunition.
            </p>
        </div>
        <div class="space-y-8 border-t-3 border-ahy-blue pt-[4.75rem] pb-24">
            <h2 class="font-extrabold text-[2.2rem] leading-none pb-2">RETURN PROCESS:</h2>
            <p class="tracking-wide leading-[1.75] text-xl font-light">
                2.1 If you wish to return a product, please contact the seller directly within 7 days from the date of delivery. The seller's contact information can be found on the product listing page, the seller's storefront or in the order confirmation email.
            </p>
            <div class="flex flex-col">
                <p class="tracking-wide leading-[1.75] text-xl font-light">
                    2.2 When contacting the seller, please provide the following information:
                </p>
                <ul class="list-disc list-inside pl-6 tracking-wide leading-[1.75] text-xl font-light">
                    <li class="">Order number</li>
                    <li class="">Reason for return</li>
                    <li class="">Product details</li>
                </ul>
            </div>
            <p class="tracking-wide leading-[1.75] text-xl font-light">
                2.3 The seller will provide you with instructions on how to proceed with the return. This may include shipping the product back to a specified address or arranging for a pickup.
            </p>
            <p class="tracking-wide leading-[1.75] text-xl font-light">
                2.4 You are responsible for the cost of return shipping unless otherwise agreed upon with the seller.
            </p>
            <p class="tracking-wide leading-[1.75] text-xl font-light">
                2.5 We recommend using a trackable shipping method and keeping the shipping receipt as proof of return.
            </p>
        </div>
        <div class="space-y-8 border-t-3 border-ahy-blue pt-[4.75rem] pb-24">
            <h2 class="font-extrabold text-[2.2rem] leading-none pb-2">RETURN CONDITIONS:</h2>
            <p class="tracking-wide leading-[1.75] text-xl font-light">
                3.1 The seller reserves the right to inspect the returned product upon receipt to ensure it meets the eligibility criteria stated in Section 1.
            </p>
            <p class="tracking-wide leading-[1.75] text-xl font-light">
                3.2 If the returned product does not meet the eligibility criteria or shows signs of use or damage, the seller may refuse the return or deduct a restocking fee from the refund amount.
            </p>
        </div>
        <div class="space-y-8 border-t-3 border-ahy-blue pt-[4.75rem] pb-24">
            <h2 class="font-extrabold text-[2.2rem] leading-none pb-2">REFUNDS:</h2>
            <p class="tracking-wide leading-[1.75] text-xl font-light">
                4.1 Once the seller receives and approves the returned product, they will initiate the refund process.
            </p>
            <p class="tracking-wide leading-[1.75] text-xl font-light">
                4.2 The refund will be issued using the original payment method used for the purchase, unless otherwise agreed upon by both parties.
            </p>
            <p class="tracking-wide leading-[1.75] text-xl font-light">
                4.3 Refunds may take 3 to 5 business days to process and reflect in your account, depending on your payment provider.
            </p>
            <p class="tracking-wide leading-[1.75] text-xl font-light">
                4.4 If a restocking fee or any other deductions apply, the refund amount will be adjusted accordingly, and the seller will provide you with the details.
            </p>
        </div>
        <div class="space-y-8 border-t-3 border-ahy-blue pt-[4.75rem] pb-24">
            <h2 class="font-extrabold text-[2.2rem] leading-none pb-2">DAMAGED OR DEFECTIVE PRODUCTS:</h2>
            <p class="tracking-wide leading-[1.75] text-xl font-light">
                6.1 In the case of receiving a damaged or defective product, please contact the seller immediately. They will guide you through the necessary steps to resolve the issue, which may include a return or replacement.
            </p>
        </div>
        <div class="space-y-8 border-t-3 border-ahy-blue pt-[4.75rem] pb-24">
            <h2 class="font-extrabold text-[2.2rem] leading-none pb-2">DISPUTE RESOLUTION:</h2>
            <p class="tracking-wide leading-[1.75] text-xl font-light">
                7.1 In the event of a dispute between the buyer and the seller regarding a return, we encourage both parties to communicate and attempt to reach a mutually satisfactory resolution.
            </p>
            <p class="tracking-wide leading-[1.75] text-xl font-light">
                7.2 If a resolution cannot be reached, you may contact our customer support team at 866-806-0934. We will review the case and provide assistance to the best of our ability.
            </p>
            <p class="tracking-wide leading-[1.75] text-xl font-light">
                Please note that this return policy applies only to returns for products purchased through Everest.com.
            </p>
            <p class="tracking-wide leading-[1.75] text-xl font-light">
                Sellers on our marketplace may have their own individual return policies, which should be reviewed before making a purchase.
            </p>
            <p class="tracking-wide leading-[1.75] text-xl font-light">
                We reserve the right to modify or update this return policy at any time without prior notice. Any changes will be effective immediately upon posting on our website.
            </p>
            <p class="tracking-wide leading-[1.75] text-xl font-light">
                If you have any questions or need further clarification regarding our return policy, please contact us at <a href="mailto:customerservice@everest.com" class="font-bold underline underline-offset-6">customerservice@everest.com</a> or <a href="tel:+1-866-806-0934" class="font-bold underline-offset-0">1-866-806-0934</a>. 
            </p>
        </div>
    </div>
</section>