<section class="space-y-4 text-ahy-blue">
    <div class="text-left md:text-center py-20 md:pt-24 pb-12">
        <h1 class="text-6xl leading-none  pb-12 sm:leading-none sm:text-8xl md:text-[120px] lg:text-[160px] uppercase font-league-gothic">
            ALL PASSIONS
        </h1>
        <p class="text-2xl md:text-3xl font-light">
            Let the Yeti-inspired explorer in you roam freely as you discover your one true outdoor passion project below.
        </p>
    </div>
    <div class="homepage-category-option">
        <ul role="list" class="mt-3 grid grid-cols-2 items-start justify-center gap-4 md:grid-cols-3 lg:grid-cols-4">
            <li class="mb-4 underline-offset-6 hover:underline">
                <a href="/optics.html">
                    <div class="category-image-ahy border-b-4 border-[#12334b]">
                        <img src="/media/all-passions/category-optics.jpg" alt="Optics" class="" />
                    </div>
                    <div class="category-name-ahy">
                        <h3 class="text-ahy-blue pt-2 text-lg font-bold capitalize !leading-[1.4rem]">Optics</h3>
                    </div>
                </a>
            </li>

            <li class="mb-4 underline-offset-6 hover:underline">
                <a href="/archery-all.html">
                    <div class="category-image-ahy border-b-4 border-[#12334b]">
                        <img src="/media/all-passions/category-archery.jpg" alt="Archery" class="" />
                    </div>
                    <div class="category-name-ahy">
                        <h3 class="text-ahy-blue pt-2 text-lg font-bold capitalize !leading-[1.4rem]">Archery</h3>
                    </div>
                </a>
            </li>

            <li class="mb-4 underline-offset-6 hover:underline">
                <a href="/camping-and-outdoor-gear.html">
                    <div class="category-image-ahy border-b-4 border-[#12334b]">
                        <img src="/media/all-passions/category-camping-gear.jpg" alt="Camping Gear" class="" />
                    </div>
                    <div class="category-name-ahy">
                        <h3 class="text-ahy-blue pt-2 text-lg font-bold capitalize !leading-[1.4rem]">Camping & Hiking Gear</h3>
                    </div>
                </a>
            </li>

            <li class="mb-4 underline-offset-6 hover:underline">
                <a href="/shooting-sports.html">
                    <div class="category-image-ahy border-b-4 border-[#12334b]">
                        <img src="/media/all-passions/category-shooting-sports.jpg" alt="Shooting Sports" class="" />
                    </div>
                    <div class="category-name-ahy">
                        <h3 class="text-ahy-blue pt-2 text-lg font-bold capitalize !leading-[1.4rem]">Shooting Sports</h3>
                    </div>
                </a>
            </li>

            <li class="mb-4 underline-offset-6 hover:underline">
                <a href="/fishing-gear.html">
                    <div class="category-image-ahy border-b-4 border-[#12334b]">
                        <img src="/media/all-passions/category-fishing-gear.jpg" alt="Fishing Gear" class="" />
                    </div>
                    <div class="category-name-ahy">
                        <h3 class="text-ahy-blue pt-2 text-lg font-bold capitalize !leading-[1.4rem]">Fishing Gear</h3>
                    </div>
                </a>
            </li>

            <li class="mb-4 underline-offset-6 hover:underline">
                <a href="/boating-gear.html">
                    <div class="category-image-ahy border-b-4 border-[#12334b]">
                        <img src="/media/all-passions/category-boating-gear.jpg" alt="Boating Gear" class="" />
                    </div>
                    <div class="category-name-ahy">
                        <h3 class="text-ahy-blue pt-2 text-lg font-bold capitalize !leading-[1.4rem]">Boating Gear</h3>
                    </div>
                </a>
            </li>

            <li class="mb-4 underline-offset-6 hover:underline">
                <a href="/hunting-gear.html">
                    <div class="category-image-ahy border-b-4 border-[#12334b]">
                        <img src="/media/all-passions/category-hunting-gear.jpg" alt="Hunting Gear" class="" />
                    </div>
                    <div class="category-name-ahy">
                        <h3 class="text-ahy-blue pt-2 text-lg font-bold capitalize !leading-[1.4rem]">hunting Gear</h3>
                    </div>
                </a>
            </li>

            <li class="mb-4 underline-offset-6 hover:underline">
                <a href="/outdoor-gear.html">
                    <div class="category-image-ahy border-b-4 border-[#12334b]">
                        <img src="/media/all-passions/category-outdoor-gear.jpg" alt="Outdoor Gear" class="" />
                    </div>
                    <div class="category-name-ahy">
                        <h3 class="text-ahy-blue pt-2 text-lg font-bold capitalize !leading-[1.4rem]">outdoor Gear</h3>
                    </div>
                </a>
            </li>

            <li class="mb-4 underline-offset-6 hover:underline">
                <a href="/survival-gear.html">
                    <div class="category-image-ahy border-b-4 border-[#12334b]">
                        <img src="/media/all-passions/category-Survival-Gear.jpg" alt="Survival Gear" class="" />
                    </div>
                    <div class="category-name-ahy">
                        <h3 class="text-ahy-blue pt-2 text-lg font-bold capitalize !leading-[1.4rem]">survival Gear</h3>
                    </div>
                </a>
            </li>

            <li class="mb-4 underline-offset-6 hover:underline">
                <a href="/knives.html">
                    <div class="category-image-ahy border-b-4 border-[#12334b]">
                        <img src="/media/all-passions/category-Knives-Blades-Axes.jpg" alt="Knives, Blade, & Axes" class="" />
                    </div>
                    <div class="category-name-ahy">
                        <h3 class="text-ahy-blue pt-2 text-lg font-bold capitalize !leading-[1.4rem]">Knives, Blade, & Axes</h3>
                    </div>
                </a>
            </li>

            <li class="mb-4 underline-offset-6 hover:underline">
                <a href="/auto-rv-atv.html">
                    <div class="category-image-ahy border-b-4 border-[#12334b]">
                        <img src="/media/all-passions/category-Auto-RV-ATV.jpg" alt="Auto/RV/ATV" class="" />
                    </div>
                    <div class="category-name-ahy">
                        <h3 class="text-ahy-blue pt-2 text-lg font-bold capitalize !leading-[1.4rem]">Auto/RV/ATV</h3>
                    </div>
                </a>
            </li>

            <li class="mb-4 underline-offset-6 hover:underline">
                <a href="/home-decor-toys-and-gifts.html">
                    <div class="category-image-ahy border-b-4 border-[#12334b]">
                        <img src="/media/all-passions/category-Home-Decor-Gifts.jpg" alt="Home Decor & Gifts" class="" />
                    </div>
                    <div class="category-name-ahy">
                        <h3 class="text-ahy-blue pt-2 text-lg font-bold capitalize !leading-[1.4rem]">Home Decor & Gifts</h3>
                    </div>
                </a>
            </li>

            <li class="mb-4 underline-offset-6 hover:underline">
                <a href="/apparel.html">
                    <div class="category-image-ahy border-b-4 border-[#12334b]">
                        <img src="/media/all-passions/category-apparel.jpg" alt="Apparel" class="" />
                    </div>
                    <div class="category-name-ahy">
                        <h3 class="text-ahy-blue pt-2 text-lg font-bold capitalize !leading-[1.4rem]">Apparel</h3>
                    </div>
                </a>
            </li>

            <li class="mb-4 underline-offset-6 hover:underline">
                <a href="/hunting-gear.html?productListPgNo=1&productListFilters=category%3AGame%20Calls">
                    <div class="category-image-ahy border-b-4 border-[#12334b]">
                        <img src="/media/all-passions/gamecall_image_slice_Shop_all_passions.jpg" alt="Game Calls" class="" />
                    </div>
                    <div class="category-name-ahy">
                        <h3 class="text-ahy-blue pt-2 text-lg font-bold capitalize !leading-[1.4rem]">Game Calls</h3>
                    </div>
                </a>
            </li>

            <li class="mb-4 underline-offset-6 hover:underline">
                <a href="/bicycles-gear.html">
                    <div class="category-image-ahy border-b-4 border-[#12334b]">
                        <img src="/media/all-passions/category-Bicycles-Gear.jpg" alt="Bicycles & Gear" class="" />
                    </div>
                    <div class="category-name-ahy">
                        <h3 class="text-ahy-blue pt-2 text-lg font-bold capitalize !leading-[1.4rem]">Bicycles & Gear</h3>
                    </div>
                </a>
            </li>

            <li class="mb-4 underline-offset-6 hover:underline">
                <a href="/watersports.html">
                    <div class="category-image-ahy border-b-4 border-[#12334b]">
                        <img src="/media/all-passions/category-watersports.jpg" alt="Watersports" class="" />
                    </div>
                    <div class="category-name-ahy">
                        <h3 class="text-ahy-blue pt-2 text-lg font-bold capitalize !leading-[1.4rem]">Watersports</h3>
                    </div>
                </a>
            </li>

            <li class="mb-4 underline-offset-6 hover:underline">
                <a href="/sports-equipment.html">
                    <div class="category-image-ahy border-b-4 border-[#12334b]">
                        <img src="/media/all-passions/category-Sports-Equipment.jpg" alt="Sports Equipment" class="" />
                    </div>
                    <div class="category-name-ahy">
                        <h3 class="text-ahy-blue pt-2 text-lg font-bold capitalize !leading-[1.4rem]">Sports Equipment</h3>
                    </div>
                </a>
            </li>

            <li class="mb-4 underline-offset-6 hover:underline">
                <a href="/golf.html">
                    <div class="category-image-ahy border-b-4 border-[#12334b]">
                        <img src="/media/all-passions/category-golf.jpg" alt="golf" class="" />
                    </div>
                    <div class="category-name-ahy">
                        <h3 class="text-ahy-blue pt-2 text-lg font-bold capitalize !leading-[1.4rem]">golf</h3>
                    </div>
                </a>
            </li>

            <li class="mb-4 underline-offset-6 hover:underline">
                <a href="/more-products/electronics.html">
                    <div class="category-image-ahy border-b-4 border-[#12334b]">
                        <img src="/media/all-passions/category-electronics.jpg" alt="electronics" class="" />
                    </div>
                    <div class="category-name-ahy">
                        <h3 class="text-ahy-blue pt-2 text-lg font-bold capitalize !leading-[1.4rem]">electronics</h3>
                    </div>
                </a>
            </li>

            <li class="mb-4 underline-offset-6 hover:underline">
                <a href="/holiday-gifts">
                    <div class="category-image-ahy border-b-4 border-[#12334b]">
                        <img src="/media/icons/nav-mobile-icon-holiday-gifts.webp" alt="Personal Defense" class="" />
                    </div>
                    <div class="category-name-ahy">
                        <h3 class="text-ahy-blue pt-2 text-lg font-bold capitalize !leading-[1.4rem]">Holiday Gifts</h3>
                    </div>
                </a>
            </li>

            <li class="mb-4 underline-offset-6 hover:underline">
                <a href="/pet-supplies.html">
                    <div class="category-image-ahy border-b-4 border-[#12334b]">
                        <img src="/media/all-passions/category-Pet-Supplies.jpg" alt="Pet-Supplies" class="" />
                    </div>
                    <div class="category-name-ahy">
                        <h3 class="text-ahy-blue pt-2 text-lg font-bold capitalize !leading-[1.4rem]">Pet Supplies</h3>
                    </div>
                </a>
            </li>

            <li class="mb-4 underline-offset-6 hover:underline">
                <a href="/more-products/backpacks-bag-accessories.html">
                    <div class="category-image-ahy border-b-4 border-[#12334b]">
                        <img src="/media/all-passions/category-bags.jpg" alt="Watersports" class="" />
                    </div>
                    <div class="category-name-ahy">
                        <h3 class="text-ahy-blue pt-2 text-lg font-bold capitalize !leading-[1.4rem]">Backpacks, Bags and Packs</h3>
                    </div>
                </a>
            </li>

            <li class="mb-4 underline-offset-6 hover:underline">
                <a href="/camping-and-outdoor-gear/cooking-essentials.html">
                    <div class="category-image-ahy border-b-4 border-[#12334b]">
                        <img src="/media/all-passions/category-Food-Cooking-Supplies.jpg" alt="Food & Cooking Supplies" class="" />
                    </div>
                    <div class="category-name-ahy">
                        <h3 class="text-ahy-blue pt-2 text-lg font-bold capitalize !leading-[1.4rem]">Food & Cooking Supplies</h3>
                    </div>
                </a>
            </li>

            <li class="mb-4 underline-offset-6 hover:underline">
                <a href="/snow-sports.html">
                    <div class="category-image-ahy border-b-4 border-[#12334b]">
                        <img src="/media/all-passions/category-Snow-Sports.jpg" alt="Snow Sports" class="" />
                    </div>
                    <div class="category-name-ahy">
                        <h3 class="text-ahy-blue pt-2 text-lg font-bold capitalize !leading-[1.4rem]">Snow Sports</h3>
                    </div>
                </a>
            </li>

            <li class="mb-4 underline-offset-6 hover:underline">
                <a href="/duffels-bags/travel-bags.html">
                    <div class="category-image-ahy border-b-4 border-[#12334b]">
                        <img src="/media/all-passions/Travel_Shop_All_Passions_everest.jpg" alt="Travel" class="" />
                    </div>
                    <div class="category-name-ahy">
                        <h3 class="text-ahy-blue pt-2 text-lg font-bold capitalize !leading-[1.4rem]">Travel</h3>
                    </div>
                </a>
            </li>
        </ul>
    </div>
    <style>
        @media screen and (min-width: 430px) {
            .aspect-ahy {
                aspect-ratio: 3/2;
            }
        }

        .underline-offset-6 {
            text-underline-offset: 6px;
        }
    </style>
</section>