<section class="storefront text-ahy-blue">
    <div class="md:text-center sm:text-left pt-10 md:pt-24 pb-4 md:pb-8">
        <h1 class="text-[92px] leading-[0.9]  sm:text-8xl md:text-[120px] lg:text-[160px] uppercase font-league-gothic text-ahy-blue">
            Outdoor shopper focus
        </h1>
        <p class="!leading-normal md:text-xl font-extrabold uppercase text-ahy-blue">
            Reach outdoor shopping enthusiast
        </p>
    </div>

    <div class="py-8 flex justify-center items-center">
        <a href="https://share.hsforms.com/1Kcqsfl5RTfiEgYGTfLzxeQ4ri79" target="_black" rel="noopener noreferrer">
            <button class="transition duration-300 easy-in-out rounded-full shadow-lg bg-ahy-red text-white font-bold text-sm hover:bg-ahy-red-light w-56 h-12">
                Get Started
            </button>
        </a>
    </div>

    <div x-data="scrollSmoothOnClick()" id="tab_wrapper" class="py-8">
        <div class="tab-bg-line-desktop relative pb-4 flex justify-center">
            <div class="text-ahy-blue tab-bg-mobile relative flex border-b-2 border-white sm:px-4 px-2 pb-2 md:px-6 justify-center">
                <button @click.prevent="scrollToWhyEverest()" class="mx-2 sm:mx-4 hover:underline underline-offset-6 h-16 text-xs sm:text-sm flex items-center font-medium">
                    Why Everest?
                </button>

                <button @click.prevent="scrollToTestimonial()" class="mx-2 sm:mx-4 hover:underline underline-offset-6 h-16 text-xs sm:text-sm flex items-center font-medium">
                    Testimonials
                </button>

                <button @click.prevent="scrollToWhatCanISell()" class="mx-2 sm:mx-4 hover:underline underline-offset-6 h-16 text-xs sm:text-sm flex items-center font-medium">
                    What can I sell?
                </button>
            </div>
        </div>
    </div>

    <div class="w-full md:w-[84%] pb-12 mx-auto">
        <p class="sm:text-2xl md:text-3xl lg:text-4xl !leading-normal font-light md:text-center text-left text-ahy-blue">
        Welcome to a curated community of professional sellers who specialize in top-quality outdoor gear. You can engage with outdoor enthusiasts who are looking for your products on our selling platform. Everest is unlike other marketplaces. You'll only connect with customers who have a high interest in outdoor products.
        </p>
    </div>

    <div id="why-everest" class="py-8">
        <div class="intro pb-8">
            <div class="pb-8">
                <h2 class="uppercase font-extrabold text-3xl md:text-5xl text-center">Why Everest?</h2>
            </div>
            <div class="seller-pros flex flex-col md:flex-row items-baseline justify-center items-center">
                <div class="flex justify-center flex-col items-center p-6">
                    <div class="pb-4">
                        <img src="/media/storefront/seller-icons.png" alt="" class="rounded-full h-24 w-24">
                    </div>
                    <div class="pb-6">
                        <p class="seller-pro-title md:h-12 lg:h-auto  text-center uppercase font-extrabold">
                            Amazing value
                        </p>
                    </div>
                    <div class="">
                        <p class="text-center seller-pro-description font-light">
                            Free to setup your shop and list. No additional monthly fees. Only 9% transactional fees.
                        </p>
                    </div>
                </div>
                <div class="flex justify-center flex-col items-center p-6">
                    <div class="pb-4">
                        <img src="/media/storefront/everest-shopper-connection.png" alt="" class="rounded-full h-24 w-24">
                    </div>
                    <div class="pb-6">
                        <p class="seller-pro-title md:h-12 lg:h-auto  text-center uppercase font-extrabold">
                            shopper connection
                        </p>
                    </div>
                    <div class="">
                        <p class="text-center seller-pro-description font-light">
                            Our Platform’s internal communication tools help make long lasting connections with real shoppers.
                        </p>
                    </div>
                </div>
                <div class="flex justify-center flex-col items-center p-6">
                    <div class="pb-4">
                        <img src="/media/storefront/everest-support.png" alt="" class="rounded-full h-24 w-24">
                    </div>
                    <div class="pb-6">
                        <p class="seller-pro-title md:h-12 lg:h-auto text-center  uppercase font-extrabold">
                            Focused on support
                        </p>
                    </div>
                    <div class="">
                        <p class="text-center seller-pro-description font-light">
                            From setup to ongoing questions to collaborative social post, we are dedicated to helping you.
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="differentiation lg:p-6 md:my-14">
            <div class="flex flex-col md:grid md:grid-cols-2  mb-6">
                <div class="order-2 md:order-1 flex flex-col justify-center md:px-4 py-8 md:px-8">
                    <h2 class="font-extrabold pb-4 md:text-2xl text-center md:text-left lg:text-3xl">AND, DIFFERENTIATION</h2>
                    <p class="pb-4 md:text-3xl lg:w-[80%] text-center md:text-left font-light w-full leading-normal tracking-wide text-xl">
                        We believe in the power of storytelling. We collaborate with our sellers to help their brands stand out. And deeper connection with their audience.
                    </p>
                </div>
                <div class="order-1 md:order-2 flex items-center">
                    <img src="/media/storefront/gyao-seller-storytelling-main1.png" alt="gyao-seller-storytelling" class="">
                </div>
            </div>

        </div>
        <div class="">
            <div class="w-full md:w-3/4 space-y-4 lg:w-1/2 m-auto flex flex-col justify-center items-center py-8 border-y-2 border-white  mb-6">
                <div class="font-bold  uppercase flex gap-2 items-center">
                    <img src="/media/icons/checkmark-black.svg" alt="checked" class="w-4">
                    <p class="text-xs sm:text-base text-center md:text-lg">secure transaction</p>
                </div>
                <div class="font-bold  uppercase flex gap-2 items-center">
                    <img src="/media/icons/checkmark-black.svg" alt="checked" class="w-4">
                    <p class="text-xs  sm:text-base text-center md:text-lg">only 9% transactional fees</p>
                </div>
                <div class="font-bold  uppercase flex gap-2 items-center">
                    <img src="/media/icons/checkmark-black.svg" alt="checked" class="w-4">
                    <p class="text-xs  sm:text-base text-center md:text-lg">free to setup your shop and list</p>
                </div>
            </div>
        </div>
    </div>
    <div id="testimonial">
        <div class="intro pb-8 w-full md:w-3/4 lg:w-[45%] tracking-wide m-auto">
            <div class="pb-8">
                <h2 class="uppercase font-extrabold text-3xl md:text-5xl text-center">Testimonials</h2>
            </div>
            <div class="seller-pros flex flex-col justify-center items-center">
                <div class="flex justify-center flex-col items-center md:p-6 px-0">
                    <div class="pb-6 ">
                        <img src="/media/storefront/forloh-seller-icon.png" alt="" class="rounded-full h-24 w-24">
                    </div>
                    <div class="pb-6">
                        <p class="seller-pro-title text-center text-sm leading-normal md:text-lg font-light">
                            “Everest is the ideal retail space to take FORLOH on. It offers us potential in all the markets we serve and an additional platform to sell our technical outdoor gear. The
                            team at Everest is passionate about the outdoors, and it shows in the Everest community. FORLOH is happy to be aligned with this team and we are excited about the future of
                            Everest.”
                        </p>
                    </div>
                    <div class="">
                        <p class="text-center seller-pro-description mt-1 font-light text-sm md:text-md leading-6">
                            Lisa Ward
                        </p>
                        <p class="text-center seller-pro-description font-light text-sm md:text-md">
                            VP of Sales, FORLOH
                        </p>
                    </div>
                </div>
                <div class="flex justify-center flex-col items-center md:p-6">
                    <div class="pb-6 pt-10">
                        <img src="/media/storefront/accel-Lifestyle-seller-icon.png" alt="Accel_lifestyle" class="rounded-full h-24 w-24">
                    </div>
                    <div class="pb-6">
                        <p class="seller-pro-title text-center text-sm leading-normal md:text-lg font-light">
                            “I am so honored to have Accel Lifestyle part of Everest’s marketplace. Our customers love the outdoors, 100% sourced and made in USA apparel and superior comfort. With my background in chemistry, I invented Prema® antibacterial fabric, which combats the toughest of odors. When wearing Accel Lifestyle, outdoor enthusiasts will not have to worry about their shirts stinking, even if they are in the middle of the woods, on a boat, or on a mountain and do not have a washing machine. We are thrilled to now be part of the Everest community, as we too love the outdoors and nature. We want to help you stay stink-free on your next adventure!”
                        </p>
                    </div>
                    <div class="">
                        <p class="text-center seller-pro-description mt-1 font-light text-sm md:text-md leading-6">
                            Megan Edding
                        </p>
                        <p class="text-center seller-pro-description font-light text-sm md:text-md">
                        Accel Lifestyle Founder & CEO
                        </p>
                    </div>
                </div>
                <div class="flex justify-center flex-col items-center md:p-6 px-0">
                <div class="pb-6 pt-10">
                        <img src="/media/storefront/Favorite-Fishing-seller-icon.png" alt="" class="rounded-full h-24 w-24">
                    </div>
                    <div class="pb-6">
                        <p class="seller-pro-title text-center text-sm leading-normal md:text-lg font-light">
                            “We are excited to be working with a marketplace that is geared to outdoor enthusiasts. It's so refreshing to have an organization that is helping to fuel the passion for
                            future generations!”
                        </p>
                    </div>
                    <div class="">
                        <p class="text-center seller-pro-description mt-1 font-light text-sm md:text-md leading-6">
                            Blake Reese
                        </p>
                        <p class="text-center seller-pro-description font-light text-sm md:text-md">
                            Vice President of Marketing, Favorite Fishing
                        </p>
                    </div>
                </div>
                <div class="flex justify-center flex-col items-center md:p-6 px-0">
                <div class="pb-6 pt-10">
                        <img src="/media/storefront/ReadyWise-seller-icon.png" alt="" class="rounded-full h-24 w-24">
                    </div>
                    <div class="pb-6">
                        <p class="seller-pro-title text-center text-sm leading-normal md:text-lg font-light">
                            “Here at ReadyWise, our mission is to team us with outstanding partners, and we are thrilled our products will now be available on Everest.com. Everest.com carries the top
                            products for all types of adventures and ReadyWise is proud to be one of the meal companies to help fuel these adventures.”
                        </p>
                    </div>
                    <div class="">
                        <p class="text-center seller-pro-description mt-1 font-light text-sm md:text-md leading-6">
                            Nic Zarbock
                        </p>
                        <p class="text-center seller-pro-description font-light text-sm md:text-md">
                            National Accounts Manager, Readywise
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="what-can-i-sell">
        <div class="pb-8">
            <h2 class="uppercase font-extrabold text-3xl md:text-5xl text-center">What can i sell?</h2>
        </div>
        <div class="homepage-category-option">
            <ul role="list" class="mt-3 grid grid-cols-2 items-start justify-center gap-4 lg:grid-cols-4">
                <li class="mb-4 underline-offset-6 hover:underline">
                    <a href="/optics.html">
                        <div class="category-image-ahy border-b-4 border-[#12334b]">
                            <img src="/media/wysiwyg/categories/category-shooting.jpg" alt="Optics" class="" />
                        </div>
                        <div class="category-name-ahy">
                            <h3 class="text-ahy-blue pt-2 text-lg font-bold capitalize !leading-[1.4rem]">Optics</h3>
                        </div>
                    </a>
                </li>

                <li class="mb-4 underline-offset-6 hover:underline">
                    <a href="/archery-all.html">
                        <div class="category-image-ahy border-b-4 border-[#12334b]">
                            <img src="/media/wysiwyg/categories/category-hunting.jpg" alt="Archery" class="" />
                        </div>
                        <div class="category-name-ahy">
                            <h3 class="text-ahy-blue pt-2 text-lg font-bold capitalize !leading-[1.4rem]">Archery</h3>
                        </div>
                    </a>
                </li>

                <li class="mb-4 underline-offset-6 hover:underline">
                    <a href="/camping-and-outdoor-gear.html">
                        <div class="category-image-ahy border-b-4 border-[#12334b]">
                            <img src="/media/wysiwyg/categories/category-camping-hiking.jpg" alt="Camping Gear" class="" />
                        </div>
                        <div class="category-name-ahy">
                            <h3 class="text-ahy-blue pt-2 text-lg font-bold capitalize !leading-[1.4rem]">Camping Gear</h3>
                        </div>
                    </a>
                </li>

                <li class="mb-4 underline-offset-6 hover:underline">
                    <a href="/fishing-gear.html">
                        <div class="category-image-ahy border-b-4 border-[#12334b]">
                            <img src="/media/wysiwyg/categories/category-fishing.jpg" alt="Fishing Gear" class="" />
                        </div>
                        <div class="category-name-ahy">
                            <h3 class="text-ahy-blue pt-2 text-lg font-bold capitalize !leading-[1.4rem]">Fishing Gear</h3>
                        </div>
                    </a>
                </li>

                <li class="mb-4 underline-offset-6 hover:underline">
                    <a href="/knives.html">
                        <div class="category-image-ahy border-b-4 border-[#12334b]">
                            <img src="/media/wysiwyg/categories/category-knife.jpg" alt="Knives, Blade, & Axes" class="" />
                        </div>
                        <div class="category-name-ahy">
                            <h3 class="text-ahy-blue pt-2 text-lg font-bold capitalize !leading-[1.4rem]">Knives, Blade, & Axes</h3>
                        </div>
                    </a>
                </li>

                <li class="mb-4 underline-offset-6 hover:underline">
                    <a href="/bicycles-gear.html">
                        <div class="category-image-ahy border-b-4 border-[#12334b]">
                            <img src="/media/wysiwyg/categories/category-bikes.jpg" alt="Bicycles & Gear" class="" />
                        </div>
                        <div class="category-name-ahy">
                            <h3 class="text-ahy-blue pt-2 text-lg font-bold capitalize !leading-[1.4rem]">Bicycles & Gear</h3>
                        </div>
                    </a>
                </li>

                <li class="mb-4 underline-offset-6 hover:underline">
                    <a href="/boating-gear.html">
                        <div class="category-image-ahy border-b-4 border-[#12334b]">
                            <img src="/media/wysiwyg/categories/category-boating.jpg" alt="Boating Gear" class="" />
                        </div>
                        <div class="category-name-ahy">
                            <h3 class="text-ahy-blue pt-2 text-lg font-bold capitalize !leading-[1.4rem]">Boating Gear</h3>
                        </div>
                    </a>
                </li>

                <li class="mb-4 underline-offset-6 hover:underline">
                    <a href="/auto-rv-atv.html">
                        <div class="category-image-ahy border-b-4 border-[#12334b]">
                            <img src="/media/wysiwyg/categories/category-automotive.jpg" alt="Auto/RV/ATV" class="" />
                        </div>
                        <div class="category-name-ahy">
                            <h3 class="text-ahy-blue pt-2 text-lg font-bold capitalize !leading-[1.4rem]">Auto/RV/ATV</h3>
                        </div>
                    </a>
                </li>
            </ul>
        </div>
        <div class="flex flex-col justify-center my-8 items-center">
            <h2 class="text-6xl  sm:text-8xl md:text-[120px] lg:text-[160px] uppercase text-center font-league-gothic text-ahy-blue">
                and more
            </h2>
            <p class="!leading-normal text-2xl text-ahy-blue">
                For all outdoors
            </p>
            <div class="py-8 flex justify-center items-center">
                <a href="https://share.hsforms.com/1Kcqsfl5RTfiEgYGTfLzxeQ4ri79" target="_black" rel="noopener noreferrer">
                    <button class="transition duration-300 easy-in-out rounded-full shadow-lg bg-ahy-red text-white font-bold text-sm hover:bg-ahy-red-light w-56 h-12">
                        Get Started
                    </button>
                </a>
            </div>
        </div>
    </div>

</section>


<script>
    function scrollSmoothOnClick() {
        return {
            scrollToWhyEverest() {
                const whyEverestEl = document.getElementById("why-everest");
                if (whyEverestEl) {
                    whyEverestEl.scrollIntoView({
                        behavior: "smooth",
                    });
                }
            },
            scrollToTestimonial() {
                const testimonialEl = document.getElementById("testimonial");
                if (testimonialEl) {
                    testimonialEl.scrollIntoView({
                        behavior: "smooth",
                    });
                }
            },
            scrollToWhatCanISell() {
                const whatCanISellEl = document.getElementById("what-can-i-sell");
                if (whatCanISellEl) {
                    whatCanISellEl.scrollIntoView({
                        behavior: "smooth",
                    });
                }
            },
        };
    }

</script>
