<section class="privacy-policy space-y-4 text-ahy-blue">
    <div class="md:text-center sm:text-left pt-10 pb-20 md:py-24 xl:pb-32 xl:pt-3">
        <h1 class="text-6xl leading-normal sm:leading-normal sm:text-8xl md:text-[120px] lg:text-[160px] xl:text-[210px] uppercase font-league-gothic">
            Shipping
        </h1>
        <p class="text-2xl md:text-3xl lg:text-4xl xl:text-5xl !leading-normal font-light">
            Welcome fearless explorer. We march towards shopping glory. Find the shipping policy below, mighty conqueror.
        </p>
    </div>
    <div class="lg:w-[56.33%] w-full flex m-auto flex-col">
        <div class="space-y-8 border-t-3 border-ahy-blue pt-[4.75rem] pb-24">
            <h2 class="font-extrabold text-[2.2rem] leading-none pb-2 uppercase">SHIPPING METHODS:</h2>
            <p class="tracking-wide leading-[1.75] text-xl font-light">
                1.1 Sellers on Everest.com are responsible for shipping the products they sell. Each seller may have their own shipping methods and policies, which can be found on their respective seller storefronts.
            </p>
            <p class="tracking-wide leading-[1.75] text-xl font-light">
                1.2 The available shipping methods may include but are not limited to standard shipping, expedited shipping and free shipping for Caliber Nation Members. The specific shipping methods offered by each seller will be outlined on their seller storefront page.
            </p>
        </div>
        <div class="space-y-8 border-t-3 border-ahy-blue pt-[4.75rem] pb-24">
            <h2 class="font-extrabold text-[2.2rem] leading-none pb-2 uppercase">SHIPPING COST:</h2>
            <p class="tracking-wide leading-[1.75] text-xl font-light">
                2.1 Shipping costs are determined by the seller and may vary depending on the shipping method, destination, and weight or dimensions of the product.
            </p>
            <p class="tracking-wide leading-[1.75] text-xl font-light">
                2.2 The shipping costs associated with a specific product can be found on the seller's storefront page. Please review this information before completing your purchase.
            </p>
        </div>
        <div class="space-y-8 border-t-3 border-ahy-blue pt-[4.75rem] pb-24">
            <h2 class="font-extrabold text-[2.2rem] leading-none pb-2 uppercase">SHIPPING TIMEFRAMES:</h2>
            <p class="tracking-wide leading-[1.75] text-xl font-light">
                3.11 Each seller is responsible for providing accurate shipping timeframes on their product listings. These time frames indicate the estimated delivery time from the point of shipment.
            </p>
            <p class="tracking-wide leading-[1.75] text-xl font-light">
                3.2 The estimated delivery time may vary depending on factors such as the seller's location, the customer's location, and the selected shipping method. Each seller is responsible for updating their shipping policy within their storefront.
            </p>
        </div>
        <div class="space-y-8 border-t-3 border-ahy-blue pt-[4.75rem] pb-24">
            <h2 class="font-extrabold text-[2.2rem] leading-none pb-2 uppercase">TRACKING INFORMATION:</h2>
            <p class="tracking-wide leading-[1.75] text-xl font-light">
                4.1 Sellers are required to provide tracking information for the shipped products whenever applicable. The tracking information will allow you to monitor the progress of your shipment.
            </p>
            <p class="tracking-wide leading-[1.75] text-xl font-light">
                4.2 Once our order has been shipped, you will receive an email notification from Everest.com containing the tracking details. Please ensure that the email address provided during the checkout process is accurate and up to date
            </p>
            <p class="tracking-wide leading-[1.75] text-xl font-light">
                4.3 To track your shipment, please follow the instructions provided in the email or log in to your Everest.com account and navigate to the "Order History" section.
            </p>
        </div>
        <div class="space-y-8 border-t-3 border-ahy-blue pt-[4.75rem] pb-24">
            <h2 class="font-extrabold text-[2.2rem] leading-none pb-2 uppercase">Seller’s shipping policies:</h2>
            <p class="tracking-wide leading-[1.75] text-xl font-light">
                5.1 Each seller on Everest.com may have their own specific shipping policies, which can be found on their seller storefront.
            </p>
            <p class="tracking-wide leading-[1.75] text-xl font-light">
                5.2 It is important to review the individual seller's shipping policies before making a purchase. These policies may include additional information on shipping times, shipping regions, shipping restrictions, and any other relevant details.
            </p>
        </div>
        <div class="space-y-8 border-t-3 border-ahy-blue pt-[4.75rem] pb-24">
            <h2 class="font-extrabold text-[2.2rem] leading-none pb-2 uppercase">LOST OR DAMAGED SHIPMENTS:</h2>
            <p class="tracking-wide leading-[1.75] text-xl font-light">
                6.1 In the unfortunate event that your shipment is lost or damaged during transit, please contact the seller directly as they are responsible for handling such situations.
            </p>
            <p class="tracking-wide leading-[1.75] text-xl font-light">
                6.2 Sellers should have their own procedures in place to assist you with lost or damaged shipments, including filing claims with the shipping carrier if necessary.
            </p>
        </div>
        <div class="space-y-8 border-t-3 border-ahy-blue pt-[4.75rem] pb-24">
            <h2 class="font-extrabold text-[2.2rem] leading-none pb-2 uppercase"> DISPUTE RESOLUTION:</h2>
            <p class="tracking-wide leading-[1.75] text-xl font-light">
                7.1 In the event of any disputes or issues related to shipping, we encourage open communication between the buyer and the seller to resolve the matter amicably.
            </p>
            <p class="tracking-wide leading-[1.75] text-xl font-light">
                7.2 If a resolution cannot be reached, you may contact our customer support team at <a href="mailto:customerservice@everest.com" class="font-bold">customerservice@everest.com</a> or <a href="tel:+1-866-806-0934" class="font-bold">1-866-806-0934</a>. We will review the case and provide assistance to the best of our ability.
            </p>
            <p class="tracking-wide leading-[1.75] text-xl font-light">
                Please note that this shipping policy applies to the shipping process facilitated through Everest.com. Each seller may have their own shipping policies, which should be reviewed before making a purchase.
            </p>
            <p class="tracking-wide leading-[1.75] text-xl font-light">
                We reserve the right to modify or update this shipping policy at any time without prior notice. Any changes will be effective immediately upon posting on our website.
            </p>
        </div>
    </div>
</section>