<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magento\Framework\Escaper;
use Magento\Sales\Block\Order\Info;

/** @var Info $block */
/** @var Escaper $escaper */
?>

<span class="order-status inline-block text-ahy-green py-3 ">
    <?= $escaper->escapeHtml(($block->getOrder()->getStatusLabel() !== 'Suspected Fraud') ? $block->getOrder()->getStatusLabel() : 'Processing'); ?>
</span>
