<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magento\Framework\Escaper;
use Magento\GiftMessage\Helper\Message;
use Magento\Sales\Block\Order\View;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper

/** @var View $block */
/** @var Escaper $escaper */

$giftMessageHelper = $this->helper(Message::class);
?>
<?php $order = $block->getOrder() ?>


<div class="bg-white p-8 relative z-20">
    <div class="absolute block md:hidden top-0 left-1/2 transform -translate-x-1/2 h-full w-screen bg-white z-[-1]"></div>
    <div class="ahy-order-details pb-4">
        <div class="md:flex md:justify-between">
            <div class="lg:flex items-center  md:text-left">
                <div class="lg:inline-block">
                    <div class="text-2xl text-ahy-blue"><?= $escaper->escapeHtml(__('Order # %1', $order->getRealOrderId())) ?></div>
                    <div class="font-bold">
                        <?= $block->getChildHtml('order.status') ?>
                    </div>
                </div>
            </div>
            <?php if (!$block->getData('is_context_shipment')): ?>
                <?= $block->getChildHtml('sales.order.buttons') ?>
            <?php else: ?>
                <?= $block->getChildHtml('sales.shipment.buttons') ?>
            <?php endif; ?>
        </div>
    </div>
    <div class="ahy-order-date pb-4">
        <?= $block->getChildHtml('order.date') ?>
    </div>
    <div class="ahy-payment-and-address-details">
        <div class="mb-4 !text-ahy-blue">
            <?= $block->getChildHtml('sales.order.info') ?>
        </div>
    </div>

    <?= $block->getChildHtml('order.comments') ?>

    <div class="ahy-item-ordered-heading">
        <?php if (!$block->getData('is_context_shipment')): ?>
            <div class="order-title">
                <p class="text-lg font-bold text-ahy-blue mt-8 mb-4 uppercase "><?= $escaper->escapeHtml(__('Items Ordered')) ?></p>
                <?php if (!empty($order->getTracksCollection()->getItems())): ?>
                    <?= $block->getChildHtml('tracking-info-link') ?>
                <?php endif; ?>
            </div>
        <?php endif; ?>
    </div>
    <div class="ahy-order-items">
        <?= $block->getChildHtml('order_items') ?>
    </div>
    <div class="ahy-order-amount-details">
        
    </div>
    <?php if ($giftMessageHelper->isMessagesAllowed('order', $order) && $order->getGiftMessageId()): ?>
        <div class="block block-order-details-gift-message">
            <div class="block-title"><strong><?= $escaper->escapeHtml(__('Gift Message for This Order')) ?></strong>
            </div>
            <?php
            $giftMessage =
                $giftMessageHelper->getGiftMessageForEntity($order);
            ?>
            <div class="block-content">
                <dl class="item-options">
                    <dt class="item-sender">
                        <strong class="label">
                            <?= $escaper->escapeHtml(__('From')) ?>
                        </strong>
                        <?= $escaper->escapeHtml($giftMessage->getSender()) ?>
                    </dt>
                    <dt class="item-recipient">
                        <strong class="label">
                            <?= $escaper->escapeHtml(__('To')) ?>
                        </strong>
                        <?= $escaper->escapeHtml($giftMessage->getRecipient()) ?>
                    </dt>
                    <dd class="item-message">
                        <?= /* @noEscape */ $giftMessageHelper->getEscapedGiftMessage($order) ?>
                    </dd>
                </dl>
            </div>
        </div>
    <?php endif; ?>
    <div class="actions-toolbar">
        <div class="secondary">
            <a class="action back" href="<?= $escaper->escapeUrl($block->getBackUrl()) ?>">
                <button class="ml-2 border-3 border-ahy-blue rounded-full font-bold text-sm w-56 h-10 hover:shadow-[#0d2f47_0px_0px_0px_1px_inset] ">
                    <span><?= $escaper->escapeHtml($block->getBackTitle()) ?></span>
                </button>
            </a>
        </div>
    </div>
</div>
