<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpMultiShipping
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$enabledProductWise = $block->enabledProductWiseShipping();
?>
<script>
        window.productWiseShippingEnabled = <?= (int)$enabledProductWise; ?>;
</script>