<?php
    /**
     * Hyvä Themes - https://hyva.io
     * Copyright © Hyvä Themes 2020-present. All rights reserved.
     * This product is licensed per Magento install
     * See https://hyva.io/license
     */
    
    declare(strict_types=1);
    
    use Magento\Contact\Block\ContactForm;
    use Magento\Contact\Helper\Data as ContactHelper;
    use Magento\Framework\Escaper;
    use Hyva\Theme\ViewModel\ReCaptcha;
    
    // phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper
    
    /** @var ContactForm $block */
    /** @var Escaper $escaper */
    /** @var ReCaptcha $recaptcha|null */
    
    $formId = 'contact';
    /** @var ContactHelper $contactHelper */
    $contactHelper = $this->helper(ContactHelper::class);
    
    // Do not replace this with $viewModels->require(ReCaptcha::class); that would break the dependency
    // on the Magento_ReCaptchaContact module
    $recaptcha = $block->getData('viewModelRecaptcha');
?>

<div class="flex-columns-wrapper flex-col lg:flex-row justify-center py-8 gap-12">
    
    <div class="lg:w-1/3 w-full">
        <?= $block->getChildHtml('contact.details') ?>
    </div>
    <form class="form contact p-4 lg:p-12 md:p-8 card bg-ahy-yellow-card w-full lg:w-2/4"
        action="<?= $escaper->escapeUrl($block->getFormAction()) ?>"
        id="<?= $escaper->escapeHtmlAttr($formId) ?>"
        x-data="initContactForm()"
        method="post"
        @submit.prevent="submitForm(event)"
    >
        <fieldset class="">
            <div id="write-us" class="flex flex-col  w-full mb12">
                <h2 class="text-2xl text-center title-font font-bold mb-4 text-ahy-blue">
                    <span><?= $escaper->escapeHtml(__('Write Us')) ?></span>
                </h2>
                <p class="w-full mx-auto leading-relaxed text-base">
                    <?= $escaper->escapeHtml( __('Jot us a note and we’ll get back to you as quickly as possible.') ) ?>
                </p>
            </div>
            <div class="flex flex-wrap -m-2">
                <div class="field name required p-2 w-full text-left">
                    <label class="label font-bold text-ahy-blue" for="name">
                        <span>
                            <?= $escaper->escapeHtml( __('Name *') ) ?>
                        </span>
                    </label>
                    <input 
                        name="name" 
                        id="name" 
                        required 
                        title="<?= $escaper->escapeHtmlAttr(__('Name')) ?>"
                        value="<?= $escaper->escapeHtmlAttr( $contactHelper->getPostValue('name') ?: $contactHelper->getUserName() ) ?>"
                        class="form-input w-full focus:ring-transparent !text-ahy-blue h-16 !border border-ahy-gray focus:border-ahy-blue required-entry"
                        type="text"
                        placeholder="<?= $escaper->escapeHtml(__('Name')) ?>"
                    />
                </div>
                <div class="field email required p-2 w-full text-left">
                    <label class="label font-bold text-ahy-blue" for="email">
                        <span>
                            <?= $escaper->escapeHtml(  __('Email *') ) ?>
                        </span>
                    </label>
                    <input 
                        name="email" 
                        id="email" 
                        required 
                        title="<?= $escaper->escapeHtmlAttr(__('Email')) ?>"
                        value="<?= $escaper->escapeHtmlAttr( $contactHelper->getPostValue('email') ?: $contactHelper->getUserEmail() ) ?>"
                        class="form-input w-full focus:ring-transparent !text-ahy-blue h-16 !border border-ahy-gray focus:border-ahy-blue required-entry"
                        placeholder="<?= $escaper->escapeHtmlAttr(__('Email')) ?>"
                        type="email"
                        style="height: 4rem; border-radius: .375rem; font-family: inherit; font-size: 1rem; padding: .5rem .75rem;"
                        oninput="this.value = this.value.replace(/[^a-zA-Z0-9@._-]/g, '')"
                    />
                </div>
                <div class="field telephone p-2 w-full text-left">
                    <label class="label font-bold text-ahy-blue" for="telephone">
                        <span>
                            <?= $escaper->escapeHtml( __('Phone Number *') ) ?>
                        </span>
                    </label>
                    <input 
                        name="telephone" 
                        id="telephone"
                        title="<?= $escaper->escapeHtmlAttr(__('Phone Number')) ?>"
                        value="<?= $escaper->escapeHtmlAttr( $contactHelper->getPostValue('telephone')  ) ?>"
                        class="form-input w-full focus:ring-transparent !text-ahy-blue h-16 !border border-ahy-gray focus:border-ahy-blue required-entry"
                        placeholder="<?= $escaper->escapeHtmlAttr(__('Phone Number')) ?>"
                        type="text"
                        required
                        maxlength="15"
                        oninput="this.value = this.value.replace(/[^+0-9()\-]/g, '')"
                    />
                </div>
                <div class="field order p-2 w-full text-left">
                    <label class="label font-bold text-ahy-blue" for="telephone">
                        <span>
                            <?= $escaper->escapeHtml( __('Order # (OPTIONAL)') ) ?>
                        </span>
                    </label>
                    <input 
                        name="OrderID" 
                        id="OrderID"
                        title="<?= $escaper->escapeHtmlAttr(__('Order # (OPTIONAL)')) ?>"
                        value="<?= $escaper->escapeHtmlAttr( $contactHelper->getPostValue('telephone')  ) ?>"
                        class="form-input w-full focus:ring-transparent !text-ahy-blue h-16 !border border-ahy-gray focus:border-ahy-blue required-entry"
                        placeholder="<?= $escaper->escapeHtmlAttr(__('Order #ID')) ?>"
                        type="text"
                    />
                </div>
                <div class="field reason p-2 w-full text-left">
                    <label class="label font-bold text-ahy-blue" for="telephone">
                        <span>
                            <?= $escaper->escapeHtml( __('Reason for reaching out? *') ) ?>
                        </span>
                    </label>
                    <select 
                        id="reason-list" 
                        name="reason-list" 
                        title="Reason" 
                        class="form-select w-full pr-6 validate-select reason-list focus:ring-transparent h-16 !border border-ahy-gray focus:border-ahy-blue " 
                        required
                    >
                        <option value="">Select question about</option>
                        <option value="My-order">My order</option>
                        <option value="How-to-pay">How to pay</option>
                        <option value="My-account">My account</option>
                        <!-- <option value="My-FFL-transfer">My FFL transfer</option> -->
                        <option value="Tracking my order">Tracking my order</option>
                        <!-- <option value="My Caliber Membership">My Caliber Membership</option> -->
                        <option value="Making-a-donation">Making a donation</option>
                        <option value="Contributing-content">Contributing content</option>
                        <option value="Setting-up-my-storefront">Setting up my storefront</option>
                        <option value="Seller-fees">Seller fees</option>
                        <option value="Buying-advertisement">Buying advertisement</option>
                        <option value="Sponsoring-products">Sponsoring products</option>
                        <option value="Email-sponsorships">Email sponsorships</option>
                        <option value="Becoming-an-affiliate">Becoming an affiliate</option>
                        <option value="Other">Other</option>
                    </select>
                </div>
                <div class="field comment required p-2 w-full text-left">
                    <label class="label font-bold text-ahy-blue" for="comment">
                        <span>
                            <?= $escaper->escapeHtml( __('What’s on your mind?') ) ?>
                        </span>
                    </label>
                    <textarea 
                        name="comment" 
                        id="comment" 
                        required
                        title="<?= $escaper->escapeHtmlAttr(__('What’s on your mind? *')) ?>"
                        class="form-input w-full focus:ring-transparent !text-ahy-blue !border border-ahy-gray focus:border-ahy-blue required-entry h-48" 
                        placeholder="<?= $escaper->escapeHtmlAttr(__('Tell us')) ?>"
                    ><?= $escaper->escapeHtml(trim($contactHelper->getPostValue('comment'))) ?></textarea>
                </div>
                <?= $block->getChildHtml('form.additional.info') ?>
                <?= $recaptcha ? $recaptcha->getInputHtml(ReCaptcha::RECAPTCHA_FORM_ID_CONTACT) : '' ?>
            </div>
        </fieldset>
        <div class="w-full my-8">
            <?= $block->getBlockHtml('formkey') ?>
            <button type="submit" title="<?= $escaper->escapeHtmlAttr(__('Submit')) ?>" class="ahy-custom-btn bg-ahy-red text-white font-bold hover:bg-ahy-red-light w-full h-16">
                <span>
                    <?= $escaper->escapeHtml(__('Submit')) ?>
                </span>
            </button>
        </div>
        <div class="w-full">
            <?= $block->getChildHtml('form.additional.after') ?>
            <?= $recaptcha ? $recaptcha->getLegalNoticeHtml(ReCaptcha::RECAPTCHA_FORM_ID_CONTACT) : '' ?>
        </div>
    </form>
    <script>
        function initContactForm() {
            return {
                errors: 0,
                hasCaptchaToken: 0,
                submitForm() {
                    // Do not rename $form, the variable is expected to be declared in the recaptcha output
                    const $form = document.querySelector('#<?= $escaper->escapeJs($formId) ?>');
                    <?= $recaptcha ? $recaptcha->getValidationJsHtml(ReCaptcha::RECAPTCHA_FORM_ID_CONTACT) : '' ?>

                    if (this.errors === 0) {
                        $form.submit();
                    }
                },
            }
        }
    </script>
</div>