<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ProductPage;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var ProductPage $productViewModel */
$productViewModel = $viewModels->require(ProductPage::class);
/** @var Product $product */
$product = $productViewModel->getProduct();
$productId = $product->getId(); 
// $productId = 269227; //change the product ID to its original value
?>

<script defer id="ahy-yotpoReview">
	function yotpoReview() {
		return {
            apiKey:             "NUJogmcy1Rt0ZI1mKiVaZY2BjAk7Lh1lNmBbSlT9",
            params:             `?per_page=150&v=${Date.now()}`,
			search:             "",
			fetchUrl:           "https://api-cdn.yotpo.com/v1/widget/NUJogmcy1Rt0ZI1mKiVaZY2BjAk7Lh1lNmBbSlT9/products/<?= $productId ?>/reviews.json",
			pageSize:           7,
			myForData:          this.reviewData,
            modalOpen:          false,
			pageNumber:         0,
			totalPages:         "",
			reviewData:         "",
            currentIndex:       0,
            currentImage:       {},
			yotpoEndpoint:      "https://api-cdn.yotpo.com/v1/widget/",
            oneStartCount:      0,
            twoStartCount:      0,
			fiveStartCount:     0,
            fourStartCount:     0,
            threeStartCount:    0,
            allReviewsData:     "",
            filteredRating:     this.reviewData,
            selectedRatings:    [],
			totalReviewCount:    0,
            defaultSortValue:   { target: { value: 'most-recent' } },
			isReviewAvailable:   false,
            currentContentData: {},
            twoStartPercentage:  0,
            oneStartPercentage:  0,
            fiveStartPercentage: 0,
            fourStartPercentage: 0,
            threeStartPercentage:0,
			totalReviewCountText:'',
			totalRatingCountText:'',
            currentReviewAllImages: {},

			initReview() {
				const yotpoApiOptions = {
					method: "GET",
					headers: {
						"accept": "application/json",
						"Content-Type": "application/json",
					},
				};
				fetch(this.fetchUrl + this.params, yotpoApiOptions)
					.then(res => {
						return res.json();
					})
					.then(data => {
						if (data.response.bottomline.total_review > 0) {
							this.reviewData = data.response.reviews;
                            // Remove this code later
                            // ----------------------------
                            // let repeatedData = [];
                            // for (let i = 0; i < 20; i++) {
                            //     repeatedData.push(...this.reviewData);
                            // }
                            // this.reviewData = repeatedData;
                            // ----------------------------
                            
                            this.allReviewsData = this.reviewData;
							this.isReviewAvailable = true;
                            
                            //All Init Function calls in a separate function
                            this.allInitFunctions();

						}
					})
					.catch(err => {
						console.error(err);
					});
			},
            openDialog(index) {
                this.currentIndex = index,
                this.currentImage = null; // Reset currentImage initially
                this.currentContentData = null; // Reset currentContentData
                this.currentReviewAllImages = null; // Reset currentReviewAllImages
                this.reviewData.forEach(review => {
                    this.currentReviewAllImages = review.images_data;
                    this.currentContentData = {
                        "content": review.content,
                        "title": review.title
                    }
                    this.currentImage = review.images_data[index];
                });
                // Open the dialog if a matching image is found
                if (this.currentImage) {
                    this.modalOpen = true;
                }
            },
            prevImage() {
                if (this.currentIndex > 0) {
                    this.currentIndex--;
                    this.currentImage = this.currentReviewAllImages[this.currentIndex];
                }
            },
            nextImage() {
                if (this.currentIndex < this.currentReviewAllImages.length - 1) {
                    this.currentIndex++;
                    this.currentImage = this.currentReviewAllImages[this.currentIndex];
                }
            },
            allInitFunctions(){
                this.reviewsSortBy(this.defaultSortValue);
                this.calculateIndividualStarPercentage();
            },
            getAverageReviewScore(){
                if(this.reviewData.length > 0){
                    const totalScore    = this.reviewData.reduce((acc, curr) => acc + curr.score, 0);
                    const averageScore  = totalScore / this.reviewData.length;
                    return averageScore.toFixed(2);
                }{
                    return null;
                }
            },
            calculateIndividualStarPercentage(){
                const totalReviews      = this.reviewData.length;
				this.totalReviewCount   = totalReviews;
                this.totalRatingCountText = this.totalReviewCount === 1 ? 'rating' : 'ratings'; 
                this.totalReviewCountText = this.totalReviewCount === 1 ? 'review' : 'reviews'; 
                let oneStarCount    = 0;
                let twoStarCount    = 0;
                let threeStarCount  = 0;
                let fourStarCount   = 0;
                let fiveStarCount   = 0;

                this.reviewData.forEach(review => {
                    switch (review.score) {
                    case 1:
                        oneStarCount++;
                        break;
                    case 2:
                        twoStarCount++;
                        break;
                    case 3:
                        threeStarCount++;
                        break;
                    case 4:
                        fourStarCount++;
                        break;
                    case 5:
                        fiveStarCount++;
                        break;
                    default:
                        break;
                    }
                });

				this.oneStartCount  = oneStarCount;
                this.twoStartCount  = twoStarCount;
                this.threeStartCount = threeStarCount;
                this.fourStartCount = fourStarCount;
                this.fiveStartCount = fiveStarCount;

                this.oneStartPercentage     = ((oneStarCount / totalReviews) * 100).toFixed(2) + '%';
                this.twoStartPercentage     = ((twoStarCount / totalReviews) * 100).toFixed(2) + '%';
                this.threeStartPercentage   = ((threeStarCount / totalReviews) * 100).toFixed(2) + '%';
                this.fourStartPercentage    = ((fourStarCount / totalReviews) * 100).toFixed(2) + '%';
                this.fiveStartPercentage    = ((fiveStarCount / totalReviews) * 100).toFixed(2) + '%';
            },
			searchReviews() {
				this.myForData  = this.reviewData;
				const startPage = this.pageNumber * this.pageSize, endPage = startPage + this.pageSize;

				if (this.search === "") {
					this.totalPages = this.myForData.length;
					return this.myForData.slice(startPage, endPage);
				}

				//Return the totalPages results of the filters
				this.totalPages = this.myForData.filter(review => {
					var searchContent = review.content.toLowerCase().includes(this.search.toLowerCase()) || review.title.toLowerCase().includes(this.search.toLowerCase()) || review.user.display_name.toLowerCase().includes(this.search.toLowerCase());
					return searchContent;
				}).length;

				return this.myForData
					.filter(review => {
						var searchContent = review.content.toLowerCase().includes(this.search.toLowerCase()) || review.title.toLowerCase().includes(this.search.toLowerCase()) || review.user.display_name.toLowerCase().includes(this.search.toLowerCase());;
						return searchContent;
					})
					.slice(startPage, endPage);
			},
			//Create array of all pages (for loop to display page numbers)
			pages() {
				return Array.from({
					length: Math.ceil(this.totalPages / this.pageSize),
				});
			},
			//Next Page
			nextPage() {
				this.pageNumber++;
                this.scrollToYotpoReviews()
			},
			//Previous Page
			prevPage() {
				this.pageNumber--;
                this.scrollToYotpoReviews()
			},
			//Total number of pages
			pageCount() {
				return Math.ceil(this.totalPages / this.pageSize);
			},
			//Return the startPage range of the paginated results
			startPageResults() {
				return this.pageNumber * this.pageSize + 1;
			},
			//Return the endPage range of the paginated results
			endResults() {
				let resultsOnPage = (this.pageNumber + 1) * this.pageSize;

				if (resultsOnPage <= this.totalPages) {
					return resultsOnPage;
				}

				return this.totalPages;
			},
			//Link to navigate to page
			viewPage(index) {
				this.pageNumber = index;
				this.scrollToYotpoReviews()
			},
			scrollToYotpoReviews() {
				const yotpoFilterEl = document.querySelector('.yotpo-filter');
				if (yotpoFilterEl) {
					yotpoFilterEl.scrollIntoView({ behavior: 'smooth' });
				}
			},
			formatReviewDate(timestamp) {
				const date = new Date(timestamp);
				const options = {
					year: "numeric",
					month: "short",
					day: "numeric",
				};
				const formattedDate = date.toLocaleDateString("en-US", options);
				return formattedDate;
			},
			updateStarRating(rating) {
				rating = rating > 5 ? 5 : rating;
				const starIcons     = document.querySelectorAll(".star-icon");
				const ratingDecimal = Math.round(rating * 2) / 2; // round to nearest 0.5
				const fullStars     = Math.floor(ratingDecimal);
				const halfStars     = Math.round(ratingDecimal - fullStars);
				const emptyStars    = 5 - fullStars - halfStars;
				let i               = 0;

				for (i = 0; i < fullStars; i++) {
					starIcons[i].classList.remove("text-gray-300");
					starIcons[i].classList.add("text-yellow-400");
				}

				if (halfStars === 1) {
					starIcons[i].classList.remove("text-gray-300");
					starIcons[i].classList.remove("text-yellow-400");
					starIcons[i].classList.add("half-star");
					i++;
				}

				for (; i < 5; i++) {
					starIcons[i].classList.remove("text-yellow-400");
					starIcons[i].classList.add("text-gray-300");
				}
			},
			reviewFeedback(vote_type, review_id, event) {
                const parentNodeEl = event.target.parentNode.parentNode;
                const helpfulLoadingEl = parentNodeEl.querySelector('.helpful-loading');

                if (helpfulLoadingEl) {
                    helpfulLoadingEl.style.display = "flex";
                }

                const add_vote_string = vote_type === 0 ? "down" : "up";

                const svg = parentNodeEl.querySelector(`#vote-${add_vote_string}-${review_id}`);
                const isAlreadyVoted = svg.classList.contains("fill-current");

                const options = {
                    method: "POST",
                    headers: {
                        accept: "application/json",
                        "Content-Type": "application/json",
                    },
                };

                let url;
                if (isAlreadyVoted) {
                    url = `https://api.yotpo.com/reviews/${review_id}/vote/${vote_type === 0 ? "down" : "up"}/true`;
                } else {
                    url = `https://api.yotpo.com/reviews/${review_id}/vote/${vote_type !== 0 ? "up" : "down"}`;
                }

                fetch(url, options)
                    .then(response => response.json())
                    .then(response => {
                        console.log("Vote response:");
                        console.log(response);

                        svg.classList.toggle("fill-current");

                        if (isAlreadyVoted && vote_type === "up") {
                            const oppositeSvg = parentNodeEl.querySelector(`#vote-down-${review_id}`);
                            oppositeSvg.classList.remove("fill-current");
                        } else if (isAlreadyVoted && vote_type === "down") {
                            const oppositeSvg = parentNodeEl.querySelector(`#vote-up-${review_id}`);
                            oppositeSvg.classList.remove("fill-current");
                        }

                        if (helpfulLoadingEl) {
                            helpfulLoadingEl.style.display = "none";
                        }
                    })
                    .catch(err => {
                        console.error(err);
                    });
            },

            reviewsSortBy(event){
                const sortBy = event.target.value;
                switch (sortBy) {
                    case "most-recent":
                        this.reviewData = this.reviewData.sort((a, b) => {
                                const dateA = new Date(a.created_at);
                                const dateB = new Date(b.created_at);
                                return dateB - dateA;
                            });
                        break;
                    case "least-recent":
                        this.reviewData = this.reviewData.sort((a, b) => {
                                const dateA = new Date(a.created_at);
                                const dateB = new Date(b.created_at);
                                return dateA - dateB;
                            });
                        break;
                    case "rating-high-low":
                        this.reviewData = this.reviewData.sort((a, b) => {
                            return b.score - a.score;
                        });
                        break;
                    case "rating-low-high":
                        this.reviewData = this.reviewData.sort((a, b) => {
                            return a.score - b.score;
                        });
                        break;
                    default:
                        return;
                }
            },
            filterByRatings(event){
                const checked = event.target.checked;
                const value = event.target.value;

                if (checked) {
                    this.selectedRatings.push(value);
                } else {
                    const index = this.selectedRatings.indexOf(value);
                    if (index !== -1) {
                        this.selectedRatings.splice(index, 1);
                    }
                }

                // If nothing is selected OR All Selected
                if(this.selectedRatings.length == 0 || this.selectedRatings.length == 5){
                    //If we want to reset to show all reviews
                    this.reviewData = this.allReviewsData;
                } else {
                    this.reviewData = this.allReviewsData.filter(review => {
                        return this.selectedRatings.includes(review.score.toString());
                    });
                }
                this.viewPage(0);
            },
            goToReview() {
                reviewEl = document.getElementById('ahy-yotpo-product-reviews');
                if (reviewEl) {
                    reviewEl.scrollIntoView({ behavior: "smooth" });
                }
            },
		};
	}
</script>

<script defer id="ahy-createReview"> 
    function createReview() {
        return{
            sku: ' <?= $productId ?> ',
            product_title: '<?= $escaper->escapeHtml( $product->getName() ) ?>',
            product_url: `${BASE_URL}<?= $product->getUrlKey() ?>`,
            customerName: '',
            customerEmail: '',
            apiKey: 'NUJogmcy1Rt0ZI1mKiVaZY2BjAk7Lh1lNmBbSlT9',
            errorMessage: null,
            showForm: true,
            showThankYouForm: false,
            submitReviews(){
                this.errorMessage = null;
                const data = {
                    appkey: this.apiKey,
                    sku: this.sku,
                    product_title: this.product_title,
                    product_url: this.product_url,
                    display_name: this.display_name,
                    email: this.email,
                    review_content: this.review_content,
                    review_title: this.review_title,
                    review_score: this.review_score
                };
                console.log(data);
                const options = {
                    method: 'POST',
                    headers: {accept: 'application/json', 'Content-Type': 'application/json'},
                    body: JSON.stringify(data)
                };

                fetch('https://api.yotpo.com/v1/widget/reviews', options)
                .then(res => {
                    return res.json();
                })
                .then(res => {
                    if (res.status?.message !== 'ok' && typeof res.status?.message !== 'undefined') {
                        switch(res.status?.message) {
                            case 'Missing email':
                                return this.errorMessage = 'Enter your email';
                            case 'Missing review_title':
                                return this.errorMessage = 'Enter review summary';
                            case 'Missing review_content':
                                return this.errorMessage = 'Enter review description';
                            case 'Missing display_name':
                                return this.errorMessage = 'Enter';
                            case 'Missing review_score': 
                                return this.errorMessage = 'Please select the rating';
                            default:
                                return this.errorMessage = res.status?.message;
                        }
                        this.showForm = true;
                        this.showThankYouForm = false;
                        return ''
                    }else{
                        this.showForm = false; 
                        this.showThankYouForm = true;
                        return ''
                    }
                    console.log('res');
                    console.log(res);
                })
                .catch(err => {
                    console.log('err');
                    console.log(err);
                });
            },
            getCustomerData(customerData) {
                if (typeof customerData.customer.fullname === 'undefined' || typeof customerData.customer.email === 'undefined') {
                    this.customerName = '';
                    this.customerEmail = '';
                }else{
                    this.customerName = customerData.customer.fullname;
                    this.customerEmail = customerData.customer.email;
                }
                return customerData;
            },
            getCustomerName() {
                return this.customerName;
            },
            getCustomerEmail() {
                return this.customerEmail;
            },
            generateTitle(star) {
                return star + ' ' + (star == 1 ? 'Star' : 'Stars');
            },
        }
    }
</script>