<div class="">
    <div class="component-messenger message mb-4 relative warning" 
        x-data="{
                component: null,
                show: false,
                message: {
                    type: 'error',
                    text: 'Something\u0020went\u0020wrong.'
                },
                paymentError: function () {
                    window.addEventListener('order:place:error', (event) => {
                        const eventData = event.detail;
                        this.message.text = eventData.text;
                    })
                },
                dispatched: 0
            }" 
        @order:place:error.window="
            component = null
            show = true
            message = Object.assign(message, $event.detail.text)
            dispatched++
        "  
        x-bind:data-testid="component ? `${component}-message` : ''" 
        x-show="show" x-transition:enter="transition ease-in duration-300" 
        x-transition:enter-start="opacity-0"
        x-transition:enter-end="opacity-100" 
        x-transition:leave="transition ease-out duration-300" 
        x-transition:leave-start="opacity-100" 
        x-transition:leave-end="opacity-0"
        data-testid="checkout.payment.error-message"
        x-init="paymentError()"
    >
        <span x-text="message.text"></span>

        <div class="absolute -left-1.5 -top-1.5" x-show="dispatched >= 2 &amp;&amp; message.type !== 'success'" x-transition.opacity="" x-transition:enter.scale.0.duration.600ms=""
            x-transition:leave.scale.0.duration.300ms="" style="display: none;">
            <span class="flex h-4 w-4">
                <span class="animate-ping absolute inline-flex h-full w-full rounded-full bg-red-500 opacity-75"></span>
                <span class="relative inline-flex rounded-full h-4 w-4 bg-red-500 border-2 border-white shadow-xl"></span>
            </span>
        </div>

        <button class="close cursor-pointer" title="Close" x-on:click.prevent="show = false; dispatched = 0">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="fill-current" width="18" height="18">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
            </svg>
        </button>
    </div>

    <div class=""
        x-data="{
            cardNumber: '',
            cardType: 'Unknown',
            detectCardType: function(cardNumber) {
                const visaPattern = /^4/;
                const mastercardPattern = /^5[1-5]/;
                const amexPattern = /^3[47]/;
                const discoverPattern = /^6(?:011|5[0-9]{2})/;
                const jcbPattern = /^(?:2131|1800|35\d{3})/;
                const dinersClubPattern = /^3(?:0[0-5]|[68])/;

                switch (true) {
                    case visaPattern.test(cardNumber):
                        return 'Visa';
                    case mastercardPattern.test(cardNumber):
                        return 'Mastercard';
                    case amexPattern.test(cardNumber):
                        return 'American Express';
                    case discoverPattern.test(cardNumber):
                        return 'Discover';
                    case jcbPattern.test(cardNumber):
                        return 'JCB';
                    case dinersClubPattern.test(cardNumber):
                        return 'Diners Club/ Carte Blanche';
                    default:
                        return 'Unknown';
                }
            },
            isValidCardNumber: function(cardNumber) {
                // Perform additional validation if needed
                // (e.g., check length, Luhn algorithm, etc.)
                return cardNumber.length >= 1;
            },
            checkCardType: function() {
                if (this.isValidCardNumber(this.cardNumber)) {
                    this.cardType = this.detectCardType(this.cardNumber);
                } else {
                    this.cardType = 'Unknown';
                }
            },
            getCardImage: function() {
                const imageMap = {
                    'Visa': '/media/icons/visa.svg',
                    'Mastercard': '/media/icons/mastercard.svg',
                    'American Express': '/media/icons/amex.svg',
                    'Discover': '/media/icons/discover.svg',
                    'JCB': '/media/icons/jcb.svg',
                    'Diners Club/ Carte Blanche': '/media/icons/diners.svg',
                    'Unknown': '/media/icons/unknown-code.svg'
                };

                return imageMap[this.cardType] || imageMap['Unknown'];
            }
        }"

    >
        <form class="flex flex-wrap gap-3 w-full p-5">
            <label class="relative w-full flex flex-col">
                <span class="font-bold mb-3">Card number</span>
                <input 
                    type="text" 
                    @input="cardNumber = $event.target.value.replace(/\W/gi, '').replace(/(.{4})/g, '$1 ').trim()"
                    :value="cardNumber"
                    maxlength="19"
                    wire:model.lazy="cardNumber"
                    x-model="cardNumber" 
                    x-on:keyup="checkCardType"
                    oninput="this.value = this.value.replace(/[^0-9\s]/g, '')"
                    placeholder="xxxx xxxx xxxx xxxx"
                    name="card_number"
                    class="rounded-md peer pl-16 pr-2 py-2 border-2 border-gray-200 placeholder-gray-300"
                />
                <img x-bind:src="getCardImage()" alt="Credit Card"
                    class="absolute bottom-0 left-0 -mb-0.5 transform translate-x-1/3 -translate-y-2/3 text-black peer-placeholder-shown:text-gray-300 w-8"
                >
            </label>

            <div class="expire-date flex flex-col w-full md:w-1/2">
                <div class="font-bold mb-3">Expire date</div>
                <div class="flex gap-2">
                    <label class="relative flex flex-col w-1/2">
                        <select class="rounded-md peer pl-6 pr-2 py-2 border-2 border-gray-200 placeholder-gray-300" id="month" name="month" wire:model.lazy="expireMonth">
                            <option selected="selected">Month</option>
                            <?php for ($i = 1; $i <= 12; $i++) : ?>
                                <option value="<?php echo str_pad($i, 2, '0', STR_PAD_LEFT); ?>"><?php echo str_pad($i, 2, '0', STR_PAD_LEFT); ?></option>
                            <?php endfor; ?>
                        </select>
                    </label>

                    <label class="relative flex flex-col w-1/2">
                        <select class="rounded-md peer pl-6 pr-2 py-2 border-2 border-gray-200 placeholder-gray-300" id="year" name="year" wire:model.lazy="expireYear">
                            <?php
                                $currentYear = date('Y');
                                $endYear = $currentYear + 20;
                            ?>
                            <option selected="selected">Year</option>
                            <?php for ($year = $currentYear; $year <= $endYear; $year++) :?>
                                <option value="<?php echo $year; ?>"><?php echo $year; ?></option>
                            <?php endfor; ?>
                        </select>
                    </label>

                </div>
            </div>
        
            <label class="relative flex-1 flex flex-col">
                <span class="font-bold flex items-center gap-3 mb-3">
                    CVV
                    <span class="relative group">
                        <span class="hidden group-hover:flex justify-center items-center px-2 py-1 text-xs absolute -right-2 transform translate-x-full -translate-y-1/2 w-max top-1/2 bg-black text-white"> The CVV code is a three digit security code printed on the back of your card.</span>
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M8.228 9c.549-1.165 2.03-2 3.772-2 2.21 0 4 1.343 4 3 0 1.4-1.278 2.575-3.006 2.907-.542.104-.994.54-.994 1.093m0 3h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                        </svg>
                    </span>
                </span>
                <input
                    class="rounded-md peer pl-12 pr-2 py-2 border-2 border-gray-200 placeholder-gray-300"
                    type="password"
                    name="card_cvc"
                    maxlength="4"
                    oninput="this.value = this.value.replace(/[^0-9\s]/g, '')"
                    placeholder="&bull;&bull;&bull;"
                    wire:model.lazy="cardCvv"
                />
                <svg xmlns="http://www.w3.org/2000/svg" class="absolute bottom-0 left-0 -mb-0.5 transform translate-x-1/2 -translate-y-1/2 text-black peer-placeholder-shown:text-gray-300 h-6 w-6" fill="none"
                    viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
                </svg>
            </label>
        </form>
    </div>  
</div>




