<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ProductPage;
use Hyva\Theme\ViewModel\ProductPrice;
use Magento\Catalog\Block\Product\AbstractProduct;
use Magento\Catalog\Model\Product;
use Magento\Catalog\Pricing\Price\FinalPrice;
use Magento\Catalog\Pricing\Price\RegularPrice;
use Magento\Catalog\Pricing\Price\TierPrice;
use Magento\Framework\Escaper;
use Hyva\Theme\ViewModel\HeroiconsOutline;

/** @var HeroiconsOutline $heroicons */
/** @var AbstractProduct $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var Product $product */
$product = $block->getProduct();

/** @var ProductPrice $productPriceViewModel */
$productPriceViewModel = $viewModels->require(ProductPrice::class);
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var ProductPage $productViewModel */
$productViewModel = $viewModels->require(ProductPage::class);

$regularPrice   = $productPriceViewModel->getPriceValue(RegularPrice::PRICE_CODE, $product);
$finalPrice     = $productPriceViewModel->getPriceValue(FinalPrice::PRICE_CODE, $product);
$tierPrices     = $productPriceViewModel->getTierPrices(TierPrice::PRICE_CODE, $product);
// ahy variables start
$discountPrice  = ($regularPrice != 0) ? (100 * ($regularPrice - $finalPrice) / $regularPrice) : 0;
$showSpecialPriceLabel      = ($finalPrice < $regularPrice) ? true : false;
$eventSaleLabel             = $product->getAttributeText('events_sale_label');
$isEventSaleLabelAvailable  = !empty($eventSaleLabel); //$eventSaleLabel ? true : false;

// ahy variables end

if ($productPriceViewModel->displayPriceInclAndExclTax()) {
    $regularPriceExclTax    = $productPriceViewModel->getPriceValueExclTax(RegularPrice::PRICE_CODE, $product);
    $finalPriceExclTax      = $productPriceViewModel->getPriceValueExclTax(FinalPrice::PRICE_CODE, $product);
}

$displayTax = $productPriceViewModel->displayPriceIncludingTax();

?>
<script>
    function initPrice<?= (int)$product->getId() ?>() {

        <?php /* All four of these keys are used - they are rendered by PHP */ ?>
        const regularPriceInclTaxKey    = 'oldPrice',
              regularPriceExclTaxKey    = 'baseOldPrice',
              finalPriceInclTaxKey      = 'finalPrice',
              finalPriceExclTaxKey      = 'basePrice';

        function calculateCustomOptionPrices(activeCustomOptions, customOptionPrices) {
            return activeCustomOptions.reduce((priceAccumulator, activeCustomOptionId) => {
                const customOptionPrice = customOptionPrices[activeCustomOptionId];
                if (customOptionPrice) {
                    return Number.parseFloat(priceAccumulator) + Number.parseFloat(customOptionPrice);
                }
                return priceAccumulator;
            }, 0);
        }

        return {
            regularPriceKey: <?= $displayTax ? 'regularPriceInclTaxKey' : 'regularPriceExclTaxKey' ?>,
            finalPriceKey: <?= $displayTax ? 'finalPriceInclTaxKey' : 'finalPriceExclTaxKey' ?>,
            activeProductsPriceData: false,
            initialFinalPrice: <?= (float)$finalPrice ?>,
            calculatedFinalPrice: false,
            calculatedFinalPriceWithCustomOptions: false,
            initialTierPrices: <?= /** @noEscape */ json_encode($tierPrices) ?>,
            showRegularPriceLabel: <?= ($finalPrice < $regularPrice) ? 'true' : 'false' ?>,
            customOptionPrices: [],
            <?php if ($productPriceViewModel->displayPriceInclAndExclTax()): ?>
            initialBasePrice: <?= (float)$finalPriceExclTax ?>,
            calculatedBasePrice: false,
            customOptionBasePrices: [],
            calculatedBasePriceWithCustomOptions: false,
            <?php endif; ?>
            activeCustomOptions: [],
            qty: 1,
            updateCustomOptionActive(data) {
                let activeCustomOptions = this.activeCustomOptions;
                const customOptionId = data.customOptionId;

                if (data.active) {
                    if (!activeCustomOptions.includes(customOptionId)) {
                        activeCustomOptions.push(data.customOptionId);
                    }
                } else {
                    if (customOptionId && activeCustomOptions.includes(customOptionId)) {
                        let index = activeCustomOptions.indexOf(customOptionId);
                        activeCustomOptions.splice(index, 1);
                    }
                }
                this.calculateFinalPriceWithCustomOptions()
            },
            updateCustomOptionPrices(prices, basePrices) {
                if (prices) {
                    this.customOptionPrices = prices;
                }

                <?php if ($productPriceViewModel->displayPriceInclAndExclTax()): ?>
                if (basePrices) {
                    this.customOptionBasePrices = basePrices;
                }
                <?php endif; ?>

                this.calculateFinalPriceWithCustomOptions();
            },
            calculateFinalPrice() {

                const findApplicableTierPrice = (initialPrice, withTax) => {
                    if (this.activeProductsPriceData && this.activeProductsPriceData.tierPrices) {
                        const key = withTax ? 'price' : 'basePrice'
                        return this.activeProductsPriceData.tierPrices.reduce((acc, tierPrice) => {
                            if (this.qty >= tierPrice.qty && tierPrice[key] < acc) {
                                return tierPrice[key];
                            }
                            return acc;
                        }, this.activeProductsPriceData[withTax ? finalPriceInclTaxKey : finalPriceExclTaxKey].amount);

                    } else {
                        const key = withTax ? 'price_incl_tax' : 'price_excl_tax';
                        return Object.values(this.initialTierPrices).reduce((acc, tierPrice) => {
                            if (this.qty >= tierPrice.price_qty && tierPrice[key] < acc) {
                                return tierPrice[key];
                            }
                            return acc;
                        }, initialPrice);

                    }
                }

                this.calculatedFinalPrice = findApplicableTierPrice(this.initialFinalPrice, <?= $displayTax ? 'true' : 'false' ?>);
                window.dispatchEvent(new CustomEvent("update-product-final-price", {detail: this.calculatedFinalPrice}));

                <?php if ($productPriceViewModel->displayPriceInclAndExclTax()): ?>
                this.calculatedBasePrice = findApplicableTierPrice(<?= (float) $finalPriceExclTax ?>, false);
                window.dispatchEvent(new CustomEvent("update-product-base-price", {detail: {basePrice: this.calculatedBasePrice}}));
                <?php endif; ?>
            },
            calculatePriceLabelVisibility() {
                this.showRegularPriceLabel =
                    (this.calculatedFinalPrice === this.activeProductsPriceData[this.regularPriceKey].amount) &&
                    this.activeProductsPriceData.isMinimalPrice;
            },
            simpleProductPrice(){
                return hyva.formatPrice(
                    this.calculatedFinalPriceWithCustomOptions ||
                    this.calculatedFinalPrice ||
                    this.initialFinalPrice
                )
            },
            calculateFinalPriceWithCustomOptions() {
                const finalPrice = this.calculatedFinalPrice || this.initialFinalPrice;
                this.calculatedFinalPriceWithCustomOptions = finalPrice + this.getCustomOptionPrice();
                <?php if ($productPriceViewModel->displayPriceInclAndExclTax()): ?>
                const basePrice = this.calculatedBasePrice || this.initialBasePrice;
                this.calculatedBasePriceWithCustomOptions = basePrice + this.getCustomOptionBasePrice();
                <?php endif; ?>
            },
            getCustomOptionPrice() {
                return calculateCustomOptionPrices(this.activeCustomOptions, this.customOptionPrices);
            },
            <?php if ($productPriceViewModel->displayPriceInclAndExclTax()): ?>
            getCustomOptionBasePrice() {
                return calculateCustomOptionPrices(this.activeCustomOptions, this.customOptionBasePrices);
            },
            <?php endif; ?>
            getFormattedFinalPrice() {
                return hyva.formatPrice(
                    this.calculatedFinalPriceWithCustomOptions ||
                    this.calculatedFinalPrice ||
                    this.initialFinalPrice
                )
            },
            <?php if ($productPriceViewModel->displayPriceInclAndExclTax()): ?>
            getFormattedBasePrice() {
                return hyva.formatPrice(
                    this.calculatedBasePriceWithCustomOptions ||
                    this.calculatedBasePrice ||
                    this.initialBasePrice
                )
            },
            <?php endif; ?>
            isPriceHidden() {
                const finalPrice = this.calculatedFinalPriceWithCustomOptions ||
                    this.calculatedFinalPrice ||
                    this.initialFinalPrice;
                return <?= $product->isSaleable() ? 'false' : 'true' ?> && finalPrice === 0;
            },
            eventListeners: {
                ['@update-prices-<?= (int)$product->getId() ?>.window'](event) {
                    this.activeProductsPriceData = event.detail;
                    this.calculateFinalPrice();
                    this.calculateFinalPriceWithCustomOptions();
                    this.calculatePriceLabelVisibility();
                },
                ['@update-qty-<?= (int)$product->getId() ?>.window'](event) {
                    this.qty = event.detail;
                    this.calculateFinalPrice();
                    this.calculateFinalPriceWithCustomOptions();

                    console.log(this.calculateFinalPriceWithCustomOptions());
                },
                ['@update-custom-option-active.window'](event) {
                    this.updateCustomOptionActive(event.detail);
                },
                ['@update-custom-option-prices.window'](event) {
                    this.updateCustomOptionPrices(event.detail);
                },
                <?php if ($productPriceViewModel->displayPriceInclAndExclTax()): ?>
                ['@update-custom-option-base-prices.window'](event) {
                    this.updateCustomOptionPrices(null, event.detail);
                }
                <?php endif; ?>
            }
        }
    }
</script>

<?php

// Get child products
if ($product->canConfigure()){
    $childProducts = $product->getTypeInstance()->getUsedProducts($product);

    $childPrice = array();
    // Loop through child products
    foreach ($childProducts as $child) {
        // Get child product details
        $childSku = $child->getSku();
        $childPrice[] = $childSku . ' ' . $child->getPrice();
        $childName = $child->getName();
        $childDescription = $child->getDescription();
        // and so on...
    }
}

?>

<div x-data="initPrice<?= (int)$product->getId() ?>()" x-bind="eventListeners" class="price-box price-final_price text-ahy-blue flex flex-col">


    <!-- simple product pricing label -->
    <?php if (!$product->canConfigure()): ?>
        <?php if ($showSpecialPriceLabel): ?>
            <span class="price-label capitalize block font-bold text-ahy-red text-sm">
                <?= $escaper->escapeHtml(__('Deal')) ?>
            </span>
        <?php endif; ?>
    <?php endif; ?>

    <!-- configurable product pricing label -->
    <?php if ($product->canConfigure() && is_int($product->getPrice())): ?>
        <?php if ($showSpecialPriceLabel): ?>
            <span class="price-label block capitalize font-bold text-ahy-red text-sm" >
                <?= $escaper->escapeHtml(__('Deal from')) ?>
            </span>
        <?php else : ?>
            <span class="price-label block capitalize font-bold text-ahy-red text-sm" >
                <?= $escaper->escapeHtml(__('from')) ?>
            </span>
        <?php endif; ?>
    <?php endif; ?>

    <!-- Content for pricing-->
    <div class="flex items-start justify-between flex-col md:flex-row pb-4 md:min-h-[56px]">
        <template x-if="!activeProductsPriceData && !isPriceHidden()">
            <div class="price-container flex flex-row md:flex-col items-baseline text-ahy-blue">
                <div class="flex items-baseline flex-row md:flex-col">
                    <div class="flex items-baseline">
                        <div class="final-price inline-block" itemprop="offers" itemscope="" itemtype="http://schema.org/Offer">
                            <span id="product-price-<?= (int)$product->getId() ?>" class="price-wrapper title-font font-extrabold text-[1.6rem] sm:text-4xl">
                                <span class="price " x-html="getFormattedFinalPrice()">
                                    <?= /** @noEscape */ $productViewModel->format($finalPrice) ?>
                                </span>
                            </span>
                            <meta itemprop="price" content="<?= $escaper->escapeHtmlAttr($finalPrice) ?>">
                            <meta itemprop="priceCurrency" content="<?= $escaper->escapeHtmlAttr($productViewModel->getCurrencyData()['code']) ?>">
                        </div>
                        <?php if ($productPriceViewModel->displayPriceInclAndExclTax()): ?>
                            <div class="final-price-excl-tax">
                                <span class="font-regular text-gray-900">
                                    <span><?= $escaper->escapeHtml(__('Excl. Tax')) ?>:</span>
                                    <span class="price" x-html="getFormattedBasePrice()">
                                        <?= /** @noEscape */ $productViewModel->format($finalPriceExclTax) ?>
                                    </span>
                                </span>
                            </div>
                        <?php endif; ?>
                        <?php if ($finalPrice < $regularPrice): ?>
                            <div class="old-price mr-2 flex text-ahy-blue">
                                <span id="product-price-<?= (int)$product->getId() ?>"
                                    class="price-wrapper title-font font-bold text-sm line-through text-ahy-blue">
                                    <span class="price pl-2" x-html="hyva.formatPrice(<?= (float)$regularPrice ?> + getCustomOptionPrice())">
                                        <?= /** @noEscape */ $productViewModel->format($regularPrice) ?>
                                    </span>
                                </span>
                            </div>
                        </div>
                        <!-- discount -->
                        <?php if ($discountPrice != 0): ?>
                            <div class="ahy-discount-container text-ahy-blue">
                                <span class="ahy-discount font-bold text-sm capitalize" >You save <?= round($discountPrice, 2) ?>%</span>
                            </div>
                        <?php endif; ?>
                    </div>
                    <?php if ($productPriceViewModel->displayPriceInclAndExclTax()): ?>
                        <div class="old-price-excl-tax">
                            <span class="font-regular line-through text-ahy-blue">
                                <span><?= $escaper->escapeHtml(__('Excl. Tax')) ?>:</span>
                                <span class="price" x-html="hyva.formatPrice(<?= (float)$regularPriceExclTax ?> + getCustomOptionBasePrice())">
                                    <?= /** @noEscape */ $productViewModel->format($regularPriceExclTax) ?>
                                </span>
                            </span>
                        </div>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
        </template>

        <!-- <template x-if="activeProductsPriceData &&  activeProductsPriceData.oldPrice && activeProductsPriceData[finalPriceKey].amount < activeProductsPriceData[regularPriceKey].amount">
            <div class="old-price flex mr-2 text-ahy-blue order-2">
                <span id="product-price-<?//= (int)$product->getId() ?>"
                      class="price-wrapper title-font font-bold text-sm line-through text-ahy-blue">
                    <span class="price" x-html="hyva.formatPrice(activeProductsPriceData[regularPriceKey].amount + getCustomOptionPrice())"></span>
                </span>
            </div>
        </template> -->
        <template x-if="activeProductsPriceData">
            <div class="flex gap-2 lg:gap-4 items-baseline flex-row md:flex-col lg:flex-row">
                <div class="final-price inline-block">
                    <span id="product-price-<?= (int)$product->getId() ?>" class="price-wrapper title-font font-extrabold text-4xl">
                        <span class="price" x-html="getFormattedFinalPrice()"></span>
                    </span>
                </div>
                <div class="flex">
                    <template x-if="activeProductsPriceData &&  activeProductsPriceData.oldPrice && activeProductsPriceData[finalPriceKey].amount < activeProductsPriceData[regularPriceKey].amount">
                        <div class="old-price flex mr-2 text-ahy-blue">
                            <span id="product-price-<?= (int)$product->getId() ?>" class="price-wrapper title-font font-bold line-through text-ahy-blue">
                                <span class="price" x-html="hyva.formatPrice(activeProductsPriceData[regularPriceKey].amount + getCustomOptionPrice())"></span>
                            </span>
                        </div>
                    </template>
                    <!-- discount -->
                    <?php if ($discountPrice != 0 && $product->canConfigure()): ?>
                        <div class="ahy-discount-container text-ahy-blue">
                            <span class="ahy-discount font-medium text-sm" ><?= __('(' . round($discountPrice, 2) . '% off)')?></span>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </template>
        <?php if ($productPriceViewModel->displayPriceInclAndExclTax()): ?>
        <template x-if="activeProductsPriceData &&  activeProductsPriceData.oldPrice && activeProductsPriceData[finalPriceKey].amount < activeProductsPriceData[regularPriceKey].amount">
            <div class="old-price-excl-tax">
                <span><?= $escaper->escapeHtml(__('Excl. Tax')) ?>:</span>
                <span class="font-regular text-gray-900">
                    <span class="price" x-html="hyva.formatPrice(activeProductsPriceData['baseOldPrice'].amount + getCustomOptionBasePrice())"></span>
                </span>
            </div>
        </template>
        <template x-if="activeProductsPriceData">
            <div class="price-excl-taxinline-block">
                <span><?= $escaper->escapeHtml(__('Excl. Tax')) ?>:</span>
                <span class="font-regular text-gray-900">
                    <span class="price" x-html="getFormattedBasePrice()"></span>
                </span>
            </div>
        </template>
        <?php endif; ?>
        <!-- stylized badges -->
        <?php if ($isEventSaleLabelAvailable): ?>
            <div class="flex items-center mt-4 md:mt-0 order-3 event-sale-label">
                <span class="bg-ahy-blue rounded-md border p-2 text-center text-xs font-bold uppercase text-white">
                    <?= $escaper->escapeHtml(__($eventSaleLabel))?>
                </span>
            </div>
        <?php endif; ?>
    </div>
    <!-- discount -->
    <?php if ($discountPrice != 0 && $product->canConfigure()): ?>
        <!-- <div class="ahy-discount-container text-ahy-blue">
            <span class="ahy-discount font-bold text-sm capitalize" >You save <?= round($discountPrice, 2) ?>%</span>
        </div> -->
    <?php endif; ?>
</div>
<div class="p-2" style="border-top: 1px solid #e5e7eb" x-data="{open:false}">
    <button @click="open = true" class="text-ahy-blue-light hover:text-ahy-blue hover:underline hover:underline-offset-6 font-bold"> Shipping & Returns </button>
    <template x-if="true">
        <div role="dialog"
            aria-labelledby="shipping-and-returns-title"
            aria-modal="true"
            class="fixed inset-y-0 right-0 z-[500] flex max-w-full"
        >
            <div class="backdrop"
                x-show="open"
                x-transition:enter="ease-in-out duration-500"
                x-transition:enter-start="opacity-0"
                x-transition:enter-end="opacity-100"
                x-transition:leave="ease-in-out duration-500"
                x-transition:leave-start="opacity-100"
                x-transition:leave-end="opacity-0"
                @click="open=false"
                aria-label="Close panel"
            >
            </div>
            <div class="relative w-screen max-w-lg shadow-2xl"
                x-show="open"
                x-transition:enter="transform transition ease-in-out duration-500 sm:duration-700"
                x-transition:enter-start="translate-x-full"
                x-transition:enter-end="translate-x-0"
                x-transition:leave="transform transition ease-in-out duration-500 sm:duration-700"
                x-transition:leave-start="translate-x-0"
                x-transition:leave-end="translate-x-full"
            >
                <div
                    x-show="open"
                    x-transition:enter="ease-in-out duration-500"
                    x-transition:enter-start="opacity-0"
                    x-transition:enter-end="opacity-100"
                    x-transition:leave="ease-in-out duration-500"
                    x-transition:leave-start="opacity-100"
                    x-transition:leave-end="opacity-0" class="absolute top-0 right-0 z-20  flex p-2 mt-2"
                >
                    <button @click="open=false" aria-label="Close panel"
                            class="p-2 card rounded-full text-ahy-blue transition duration-150 ease-in-out hover:text-black">
                        <?= $heroicons->xHtml(); ?>
                    </button>
                </div>
                <div class="flex flex-col h-full overflow-y-scroll pt-6 bg-white shadow-xl">
                    <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('shipping-and-return-slideout-content')->toHtml();?>
                </div>
            </div>
        </div>
    </template>
</div>