<?php
    /** @var Klevu\FrontendJs\Block\Html\Head\JsDeferredPowerUp $block */
    $isHomePage = $block->getRequest()->getFullActionName() === 'cms_index_index';

?>
<script type="text/javascript" id="klevu_jsdeferredpowerup" defer>
    
<?php if ($isHomePage): ?>
    document.addEventListener('klevuLoaded', function() {
        klevu(<?php /** @noEscape */ echo $block->getJsDeferredPowerUpSerialized(); ?>);
    });
<?php else:?>
    klevu(<?php /** @noEscape */ echo $block->getJsDeferredPowerUpSerialized(); ?>);
<?php endif?>
</script>
