<div id="paymentModal" class="modal">
    <div class="modal-content">
        <div class="modal-header">
            <div class="modal-title" id="paymentModalTitle"></div>
            <span class="close close-modal" id="closePaymentModal">&times;</span>
        </div>
        <hr />
        <div class="modal-body">
            <iframe id="ordersmodal" height="100%" width="100%"
                style="overflow: auto; width: 100%; height: 100%; min-height: 575px;">

            </iframe>
        </div>
        <hr />
        <footer class="modal-footer">
            <button class="close-modal" type="button"><span>Cancel</span></button>
        </footer>
    </div>
</div>
<div id="spinner-wrapper">
    <div class="spinner"></div>
</div>