<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

/** @var Template $block */
/** @var Escaper $escaper */

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Magento\Customer\Model\Account\Redirect;
?>
<?php if ($block->hasData('title')): ?>
    <header class="section-title my-6 flex flex-col justify-between items-start <?= $block->getData('title') == 'Order Summary' ? ' mb-0 ' : 'border-b-2 border-ahy-blue pb-6' ?>">
       <div class="flex flex-col md:flex-row w-full justify-between md:items-center">
          <h2 class="text-ahy-blue text-2xl font-extrabold hidden md:block">
            <?= $escaper->escapeHtml($block->getData('title')) ?>
        </h2>
            <?php if($block->getData('title') == 'Billing & Shipping Address'):?>
                <script>
                    "use strict";
                    function initComponentLoggedIn() {
                        return {
                            cart: false,
                            customer: false,
                            receiveCustomerData(data) {
                                if (data.cart) {
                                    this.cart = data.cart;
                                }
                                if (data.customer.firstname) {
                                    this.customer = data.customer;
                                }
                            }
                        }
                    }
                </script>
                <div x-data="initComponentLoggedIn()"
                    @private-content-loaded.window="receiveCustomerData($event.detail.data)"
                    style="display:block" x-bind:style="!customer ? 'display:block' : 'display:none'"
                >
                    <template x-if="!customer">
                        <div class="text-ahy-blue p-2 font-normal text-sm flex items-center">
                            <span class="">
                                <a onclick="hyva.setCookie && hyva.setCookie(
                                        '<?= /** @noEscape */ Redirect::LOGIN_REDIRECT_URL ?>',
                                        window.location.href,
                                        1
                                    )"
                                    href="<?= $escaper->escapeUrl($block->getUrl('customer/account/index')) ?>" 
                                    class="font-bold hover:underline text-[#0070ba] hover:text-ahy-blue underline-offset-4">Sign In</a> to speed up checkout
                            </span>
                        </div>
                    </template>
                </div>
            <?php endif;?>
            <?php if($block->getData('title') == 'Order Summary'):?>
                <a href="/checkout/cart" class="">
                    <button class="w-28 font-bold rounded-full text-ahy-blue ahy-edit-cart bg-transparent border-2 p-2 text-sm capitalize border-ahy-blue hover:">
                        edit cart
                    </button>
                </a>
            <?php endif;?>
        </div>
        <?php if($block->getData('title') == 'Billing & Shipping Address'):?>
            <div class="p-2 md:p-0">
                <span class="text-xs font-semibold text-ahy-blue">* For security purposes, we only allow orders where the billing and shipping address are the same</span>
            </div>
        <?php endif;?>
    </header>
    <style>
        button.ahy-edit-cart:hover {
            box-shadow: #0d2f47 0px 0px 0px 1px inset;
        }
        .billing-details-checkout {
            display: none !important;
        }
        .shipping-methods-checkout{
            margin-bottom: 32px !important;
        }
    </style>
<?php endif ?>
<style>
    @media screen and (max-width: 767px) {
        .step-shipping.step-layout-2columns .price-summary.card,  
        .step-shipping.step-layout-2columns .coupon-text.text-center,  
        .step-shipping.step-layout-2columns .coupon-code .flex.mt-2.items-stretch.w-full{
            display: none;
        }
    }
</style>
