<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2023 Amasty (https://www.amasty.com)
 * @package Automatic Related Products for Magento 2
 */
/** @var \Amasty\Mostviewed\Block\Checkout\Cart\Bundle $block */
$bundle = $block->getBundle();
?>

<?php if ($bundle): ?>
    <div class="amrelated-cart-bundle" data-pack-id="<?= /* @noEscape */ $bundle->getPackId();?>">
        <?= /* @noEscape */ $block->renderBundle($bundle); ?>
    </div>
<?php endif;?>

