<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2023 Amasty (https://www.amasty.com)
 * @package Automatic Related Products for Magento 2
 */
/** @var \Amasty\Mostviewed\Block\Checkout\Cart\Messages $block */
$object = $block->getMessage();
?>

<?php if ($object && ($message = $block->convertMessage($object))): ?>
    <div class="amrelated-cart-message" data-pack-id="<?= /* @noEscape */ $object->getPackId();?>">
        <?= /* @noEscape */ $message; ?>
    </div>
<?php endif;?>
