<!-- meet marcus start -->
<div class="meet-marcus-section text-ahy-blue flex flex-col md:flex-row pb-4 lg:w-[85%] 2xl:w-[75%]">
    <div class="customer-support p-2  lg:pl-2 lg:pt-2 flex flex-row lg:flex-col">
        <div class="customer-support-icon">
            <img src="/media/icons/contact-us-icon.png" alt="customer support" class="h-12 w-12 rounded-full" />
        </div>
        <div class="meet-marcus-content">
            <div class="customer-support-title text-lg leading-none font-bold pb-1">
                <span class="capitalize">customer support</span>
            </div>
            <div class="customer-support-description text-[12px]">
                <span class="capitalize">
                    <a href="tel:1-866-806-0934" class="">1-866-806-0934</a>
                    meet <a href="" class="underline-offset-4 underline">marcus</a>
                </span>
            </div>
        </div>
    </div>

    <hr class="">

    <div class="shop-secure-promise p-2  lg:pl-2 flex flex-row lg:flex-col">
        <div class="shop-secure-promise-icon">
            <img src="/media/icons/shop-secure-promise-icon.png" alt="shop secure promise" class="h-12 w-12" />
        </div>
        <div class="meet-marcus-content">
            <div class="shop-secure-promise-title text-lg leading-none font-bold pb-1">
                <span class="capitalize">shop secure promise</span>
            </div>
            <div class="shop-secure-promise-description text-[12px]">
                <span class="capitalize">securely processed</span>
            </div>
        </div>
    </div>

    <hr class="">

    <div class="give-back-fund p-2 flex  lg:pl-2 flex-row lg:flex-col">
        <div class="give-back-fund-icon">
            <img src="/media/icons/give-back-fund-icon.png" alt="give back fund" class="h-12 w-12" />
        </div>
        <div class="meet-marcus-content">
            <div class="give-back-fund-title flex 2xl:justify-between items-baseline">
                <div class="leading-none pb-1"><span class="capitalize leading-none text-lg font-bold">give back fund</span></div>
                <div class="ahy-tooltip">
                    <img src="/media/icons/info-icon-up.svg" alt="" class="w-8 h-4 img-info-up">
                    <img src="/media/icons/info-icon-over.svg" alt="" class="w-8 h-4 hidden">
                    <div class="ahy-tooltip-text bg-white shadow-xl p-4 flex flex-col gap-4">
                        <div class="ahy-tooltip-header"><span class="capitalize text-lg font-bold">give back fund</span></div>
                        <div class="ahy-tooltip-description">
                            <p class="text-xs font-medium">Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem esse rem vel maxime hic nostrum.</p>
                        </div>
                        <div class="ahy-tooltip-button">
                            <a href="" class="">
                                <button class="border-ahy-blue border-2 text-[11px] rounded-full px-8 py-1 font-bold">Details</button>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="give-back-fund-description text-[12px]">
                <span class="capitalize">supporting outdoor causes</span>
            </div>
        </div>
    </div>

    <hr class="">

    <div class="price-match-guarantee p-2  lg:pl-2 flex flex-row lg:flex-col">
        <div class="price-match-guarantee-icon">
            <img src="/media/icons/price-match-guarantee-icon.png" alt="price match guarantee" class="h-12 w-12" />
        </div>
        <div class="meet-marcus-content">
            <div class="price-match-guarantee-title flex 2xl:justify-between items-baseline">
                <div class="lg:leading-none pb-1"><span class="capitalize text-base lg:text-lg lg:leading-none font-bold">price match guarantee</span></div>
                <div class="ahy-tooltip">
                    <img src="/media/icons/info-icon-up.svg" alt="" class="w-8 h-4 img-info-up">
                    <img src="/media/icons/info-icon-over.svg" alt="" class="w-8 h-4 hidden">
                    <div class="ahy-tooltip-text bg-white shadow-xl p-4 flex flex-col gap-4">
                        <div class="ahy-tooltip-header"><span class="capitalize text-lg font-bold">price match guarantee</span></div>
                        <div class="ahy-tooltip-description">
                            <p class="text-xs font-medium">Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem esse rem vel maxime hic nostrum.</p>
                        </div>
                        <div class="ahy-tooltip-button">
                            <a href="" class="">
                                <button class="border-ahy-blue border-2 text-[11px] rounded-full px-8 py-1 font-bold">Details</button>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="price-match-guarantee-description text-[12px]">
                <span class="">Found a lower price? We'll match it.</span>
            </div>
        </div>
    </div>
</div>
<!-- meet marcus end -->
<!-- create review section -->
<div x-data="{
        open: false,
    }"
>
    <button @click="open = !open"
        class="bg-ahy-blue mt-8 hover:bg-ahy-blue-light text-white uppercase text-xs tracking-widest font-medium py-3 px-4 rounded transition duration-300 ease-in-out w-full md:w-64">
        write a review
    </button>
    <template x-if="open">
        <div role="dialog"
             aria-labelledby="cart-drawer-title"
             aria-modal="true"
             @click.outside="open=false"
             class="fixed inset-y-0 right-0 z-30 flex max-w-full">
            <div class="backdrop"
                 x-show="open"
                 x-transition:enter="ease-in-out duration-500"
                 x-transition:enter-start="opacity-0"
                 x-transition:enter-end="opacity-100"
                 x-transition:leave="ease-in-out duration-500"
                 x-transition:leave-start="opacity-100"
                 x-transition:leave-end="opacity-0"
                 @click="open=false"
                 aria-label="Close panel"></div>
            <div class="relative w-screen max-w-md shadow-2xl"
                 x-show="open"
                 x-transition:enter="transform transition ease-in-out duration-500 sm:duration-700"
                 x-transition:enter-start="translate-x-full"
                 x-transition:enter-end="translate-x-0"
                 x-transition:leave="transform transition ease-in-out duration-500 sm:duration-700"
                 x-transition:leave-start="translate-x-0"
                 x-transition:leave-end="translate-x-full"
            >
                <div
                    x-show="open"
                    x-transition:enter="ease-in-out duration-500"
                    x-transition:enter-start="opacity-0"
                    x-transition:enter-end="opacity-100"
                    x-transition:leave="ease-in-out duration-500"
                    x-transition:leave-start="opacity-100"
                    x-transition:leave-end="opacity-0" class="absolute top-0 right-0 flex p-2 mt-2">
                    <button @click="open=false" aria-label="Close panel"
                            class="p-2 card rounded-full text-ahy-blue transition duration-150 ease-in-out hover:text-black">
                        <?= $heroicons->xHtml(); ?>
                    </button>
                </div>
                <div class="flex flex-col h-full pt-6 bg-white shadow-xl">

                    <header class="px-4 sm:px-6">
                        <h2 id="cart-drawer-title" class="text-lg pb-4 border-b border-ahy-blue font-extrabold leading-7 text-ahy-blue">
                            title here
                        </h2>
                    </header>

                    <div class="relative grid gap-6 px-4 py-6 overflow-y-auto bg-white
                        sm:gap-8 sm:px-6">
                    </div>
                </div>
            </div>
        </div>
    </template>
</div>