<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$viewModel = $block->getViewModel();
$orderHelper = $viewModel->getOrderHelper();
$orderId = $block->getRequest()->getParam('id');
$order = $block->Order->load($orderId);
$orderStatusLabel = $order->getStatusLabel();
$tracking = $orderHelper->getOrderinfo($orderId);
$isCanceled = $tracking->getIsCanceled();
$itemCollection = $block->getOrderItemCollection($orderId);
$qtyToCancelAvail = $block->getQtyToCancelCount($itemCollection);
if ($isCanceled && !$qtyToCancelAvail) {
    $orderStatusLabel = 'Canceled';
}
?>
<span class="order-status"><?= $escaper->escapeHtml($orderStatusLabel)?></span>
<div class="order-date">
    <?= /* @noEscape */ __('<span class="label">Order Date:</span> %1', '<date>' . $block
    ->formatDate($order->getCreatedAt(), \IntlDateFormatter::LONG) . '</date>') ?>
</div>
