<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpAssignProduct
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$productList = $block->getLayout()->createBlock(\Webkul\MpAssignProduct\Block\Product\ProductList::class);
if ($block->getConfigData('active') && $block->getConfigData('allow_seller')) {
    $productType = $block->getData('product_type');
    $regionBlock = $block->getLayout()->createBlock(
        \Webkul\Mppercountryperproductshipping\Block\Adminhtml\RegionRule\Create::class
    );
    $helper = $productList->getHelperObject('marketplaceHelper');
    $currentHelper = $block->helper(Webkul\Mppercountryperproductshipping\Helper\Data::class);
    $isPartner = $helper->isSeller();
    if ($isPartner == 1) {
        $rightseller = 1;
        if ($rightseller == 1) {
            $count = 0;
            $ar['countries'] = $regionBlock->getCountriesByRegion();
            $regionArray = array_merge($regionBlock->getRegion(), $ar);
            $loadShippingData = $block->getData('shipping_country_charge') ?? '';
            $isAvail = false;
            if ($productType!='virtual' && $productType!='downloadable' && $productType!='grouped') {
                $isAvail = true;
            }
            ?>
            <div class="field shippingprice">
                <?php if ($isAvail) { ?>
                <div class="control">
                    <input type="hidden" value="" id="mp_shipping_country_charge" name="shipping_country_charge"/>
                </div>
                <?php } ?>
                <label class="label"><?= /* @noEscape */ __('Per Country Per Product Shipping:') ?></label>
                <?php if ($isAvail) { ?>
                <div class="wk_mp_option-box">
                <div class="table-wrapper order-items">
                    <table class="data table" id="shipping_table">
                    <thead>
                        <tr class="wk_mp_headcus ul_first headings">
                            <th class="col applyon"><span><?= /* @noEscape */ __('Select Apply on') ?></span></th>
                            <th class="col country-region">
                                <span><?= /* @noEscape */ __('Select Country/Region') ?></span>
                            </th>
                            <th class="col cost"><span><?= /* @noEscape */ __('Shipping Cost') ?></span></th>
                            <th class="col action"><span><?= /* @noEscape */ __('Action') ?></span></th>
                            <th class="col more"><span>
                                <button class="button addshippingprice" 
                                title="<?= /* @noEscape */ __('Add') ?>" type="button">
                                    <span>
                                        <span><?= /* @noEscape */ __('Add') ?></span>
                                    </span>
                                </button>
                            </span></th>
                        </tr>
                    </thead>
                    <?php if ($loadShippingData == ''): ?>
                        
                    <?php else: ?>
                        <?php if ($block->getConfigData('sallowspecific')): ?>
                            <?php $totalCountries = array_filter(explode('/', $loadShippingData));
                                $count = count($totalCountries);
                                $i=0;
                            foreach ($totalCountries as $price):
                                $sepratecountry= explode(',', $price);
                                $idship='row'.$i;
                                ?>
                            <tbody class="wk_mp_headcus wk-mp-body">
                                <tr class="wk-shipbody">
                                    <td class="col applyon" data-th="<?= /* @noEscape */ __('Select Apply on') ?>">
                                        <select class="required-entry select applyon" 
                                        name="ship[<?= /* @noEscape */ $i; ?>][1]">
                                            <option value="" selected="selected" disabled="disabled">
                                            <?= /* @noEscape */ __('Select Option')?></option>
                                            <option 
                                            <?= /* @noEscape */ ($sepratecountry[0]=="R")?"selected='selected'":"" ?> 
                                            value="R"><?= /* @noEscape */ __("Region") ?></option>
                                            <option 
                                            <?= /* @noEscape */ ($sepratecountry[0]=="C")?"selected='selected'":"" ?> 
                                            value="C"><?= /* @noEscape */ __("Country") ?></option>
                                        </select>
                                    </td>
                                    <td class="col country-region" 
                                    data-th="<?= /* @noEscape */ __('Select Country/Region') ?>">
                                    
                                        <select 
                                        <?= /* @noEscape */ ($sepratecountry[0]=="C")?"":"style='display:none;'" ?> 
                                        name="ship[<?= /* @noEscape */ $i; ?>][2]" 
                                        class="country-select select countryoption 
                                        <?= /* @noEscape */ ($sepratecountry[0]=="C")?"required-entry":"" ?>">
                                            <option value="" selected="selected" disabled="disabled">
                                            <?= /* @noEscape */ __('Select Country')?></option>
                                        <?php  $shippingcountries = $block->getConfigData('specificcountry');
                                                $arrcountry = explode(',', $shippingcountries);
                                        foreach ($arrcountry as $country) {
                                            $country_name = $block->getCountryNameByLocale($country);
                                            ?>

                                                        <option <?= /* @noEscape */ ($sepratecountry[1]==$country
                                                        && $sepratecountry[0]=="C")?"selected='selected'":"" ?> 
                                                        value="<?= /* @noEscape */ $country; ?>">
                                                        <?= /* @noEscape */ $country_name; ?></option>
                                            <?php }    ?>
                                        </select>
                                    
                                        <select 
                                        <?= /* @noEscape */ ($sepratecountry[0]=="R")?"":"style='display:none;'" ?> 
                                        name="ship[<?= /* @noEscape */ $i; ?>][3]" 
                                        class="select regionoption 
                                        <?= /* @noEscape */ ($sepratecountry[0]=="R")?"required-entry":"" ?> ">
                                        <option value="" selected="selected" disabled="disabled">
                                        <?= /* @noEscape */ __('Select Region')?></option>
                                        <?php	foreach ($regionArray['region'] as $region) {
                                                        $countryByRegion = $regionArray['countries'][$region['value']];
                                                        $regionCollection = $regionBlock->getRegionDataByRegionCode(
                                                            $region['value']
                                                        );
                                                        $allowedCountries = $block->getAllowedCountriesFromCollection(
                                                            $regionCollection
                                                        );
                                            ?>
                                                        <option class="optionparent" 
                                                        <?= /* @noEscape */ ($sepratecountry[1]==$region['value']
                                                        && $sepratecountry[0]=="R")?"selected='selected'":"" ?> 
                                                        value="<?= /* @noEscape */ $region['value']; ?>" >
                                                        <?= /* @noEscape */ $region['label']; ?></option>
                                                        <?php
                                                        foreach ($countryByRegion as $country) {
                                                            if (in_array($country['value'], $allowedCountries)) {
                                                                ?>
                                                                <option class="optionchild" 
                                                                value="<?= /* @noEscape */ $region['value']; ?>" 
                                                                disabled> -<?= /* @noEscape */ $country['label']; ?>
                                                                </option>
                                                                <?php
                                                            }
                                                        }
                                                        ?>                                                
                                                <?php }    ?>
                                        </select>
                                    </td>
                                    <td class="col cost" data-th="<?= /* @noEscape */ __('Shipping Cost') ?>">
                                        <input class="required-entry validate-number input-text" type="text" 
                                        value='<?= /* @noEscape */ (isset($sepratecountry[2])) ?
                                        $sepratecountry[2] : '' ?>' 
                                        name="ship[<?= /* @noEscape */ $i; ?>][4]">
                                    </td>
                                    <td class="col action" data-th="<?= /* @noEscape */ __('Action') ?>">
                                        <button class="button delete" 
                                        title="<?= /* @noEscape */ __('Delete') ?>" type="button">
                                            <span>
                                                <span><?= /* @noEscape */ __('Delete') ?></span>
                                            </span>
                                        </button>
                                    </td>        
                                </tr>
                            </tbody>
                                <?php
                                $i++;
                            endforeach; ?>
                        <?php else: ?>
                            <?php $totalCountries = [];
                            if ($loadShippingData != ',') {
                                $totalCountries = array_filter(explode('/', $loadShippingData));
                            }
                                $count = count($totalCountries);
                                $i = 0;
                            foreach ($totalCountries as $price):
                                $sepratecountry = explode(',', $price);
                                $idship = 'row'.$i;
                                ?>
                            <tbody class="wk_mp_headcus wk-mp-body">
                                <tr class="wk-shipbody">
                                    <td class="col applyon" data-th="<?= /* @noEscape */ __('Select Apply on') ?>">
                                        <select class="required-entry applyon" 
                                        name="ship[<?= /* @noEscape */ $i; ?>][1]">
                                            <option value="" selected="selected" disabled="disabled">
                                            <?= /* @noEscape */ __('Select Option')?>
                                            </option>
                                            <option value="R" 
                                            <?= /* @noEscape */ ($sepratecountry[0]=="R")?"selected='selected'":"" ?> >
                                                <?= /* @noEscape */ __("Region")?>
                                            </option>
                                            <option value="C" 
                                            <?= /* @noEscape */ ($sepratecountry[0]=="C")?"selected='selected'":"" ?> >
                                                <?= /* @noEscape */ __("Country")?>
                                            </option>
                                        </select>
                                    </td>
                                    <td class="col country-region" 
                                    data-th="<?= /* @noEscape */ __('Select Country/Region') ?>">
                                        <select 
                                        <?= /* @noEscape */ ($sepratecountry[0]=="C")?"":"style='display:none;'" ?> 
                                        name="ship[<?= /* @noEscape */ $i; ?>][2]" 
                                        class="country-select select countryoption 
                                        <?= /* @noEscape */ ($sepratecountry[0]=="C")?"required-entry":"" ?>">
                                            <option value="" selected="selected" disabled="disabled">
                                            <?= /* @noEscape */ __('Select Country')?></option>
                                        <?php  $shippingcountries = $block->getCountryList();
                                        foreach ($shippingcountries as $country) {
                                            if ($country['value'] != ''):
                                                ?>
                                                        <option 
                                                        <?= /* @noEscape */ ($sepratecountry[1]==$country['value']
                                                        && $sepratecountry[0]=="C")?"selected='selected'":"" ?>  
                                                        value="<?= /* @noEscape */ $country['value']; ?>">
                                                        <?= /* @noEscape */ $country['label']; ?>
                                                        </option>
                                                    <?php
                                                endif;
                                        }    ?>
                                        </select>
                                        
                                        <select 
                                        <?= /* @noEscape */ ($sepratecountry[0]=="R")?"":"style='display:none;'" ?> 
                                        name="ship[<?= /* @noEscape */ $i; ?>][3]" class="select regionoption  
                                        <?= /* @noEscape */ ($sepratecountry[0]=="R")?"required-entry":"" ?>">
                                            <option value="" selected="selected" disabled="disabled">
                                            <?= /* @noEscape */ __('Select Region')?></option>
                                            <?php foreach ($regionArray['region'] as $region) {
                                                    $countryByRegion = $regionArray['countries'][$region['value']];
                                                    $regionCollection = $regionBlock->getRegionDataByRegionCode(
                                                        $region['value']
                                                    );
                                                    $allowedCountries = $block->getAllowedCountriesFromCollection(
                                                        $regionCollection
                                                    );
                                                ?>
                                                    <option class="optionparent" 
                                                    <?= /* @noEscape */ ($sepratecountry[1]==$region['value']
                                                    && $sepratecountry[0]=="R")?"selected='selected'":"" ?> 
                                                    value="<?= /* @noEscape */ $region['value']; ?>" >
                                                    <?= /* @noEscape */ $region['label']; ?></option>
                                                    <?php
                                                    foreach ($countryByRegion as $country) {
                                                        if (in_array($country['value'], $allowedCountries)) {
                                                            ?>
                                                            <option value="<?= /* @noEscape */ $region['value']; ?>"
                                                             class="optionchild" 
                                                             disabled> -<?= /* @noEscape */ $country['label']; ?>
                                                             </option>
                                                            <?php
                                                        }
                                                    }
                                                    ?>
                                            <?php }    ?>
                                        </select>
                                    </td>
                                    <td class="col cost" data-th="<?= /* @noEscape */ __('Shipping Cost') ?>">
                                    <input class="required-entry validate-zero-or-greater input-text" type="text" 
                                    value='<?= /*@noEscape */ (isset($sepratecountry[2])) ? $sepratecountry[2] : '' ?>' 
                                    name="ship[<?= /* @noEscape */ $i; ?>][4]">
                                    </td>
                                    <td class="col action" data-th="<?= /* @noEscape */ __('Action') ?>">
                                        <button style="margin:0" class="button delete" 
                                        title="<?= /* @noEscape */ __('Delete') ?>" type="button">
                                            <span>
                                                <span><?= /* @noEscape */ __('Delete') ?></span>
                                            </span>
                                        </button>
                                    </td>        
                                </tr>
                            </tbody>
                                <?php $i++;
                            endforeach;
                            ?>
                        <?php endif; ?>
                    <?php endif; ?>
                    </table>
                </div>
                </div>
            <?php } else { ?>
                <div>
                    <?= /* @noEscape */ __('Not available for this product type.') ?>
                <div>
            <?php } ?>
            </div>
            <?php
        }
    } ?>
<style>
    .optionparent {
        color: #41362f;
        font-weight: bold;
    }
    .optionchild {
        color: #757575;
        padding-left: 25px;
    }
</style>
<script id="shipping-template" type="text/x-magento-template">
    <tbody class="wk_mp_headcus wk-mp-body">
        <?php if ($block->getConfigData('sallowspecific')): ?>
            <tr class="wk-shipbody">
                <td class="col applyon" data-th="<?= /* @noEscape */ __('Select Apply on') ?>">
                    <select class="required-entry applyon" name="ship[<%- data.index %>][1]">
                        <option value="" disabled="disabled"><?= /* @noEscape */ __('Select Option')?></option>
                        <option selected="selected" value="R"><?= /* @noEscape */ __('Region') ?></option>
                        <option value="C"><?= /* @noEscape */ __('Country') ?></option>
                    </select>
                </td>
                <td class="col country-region" data-th="<?= /* @noEscape */ __('Select Country/Region') ?>">
                    <select style="display:none;" name="ship[<%- data.index %>][2]" 
                    class="country-select required-entry countryoption">
                        <option value="" selected="selected" disabled="disabled">
                        <?= /* @noEscape */ __('Select Country')?></option>
                        <?php  $shippingcountries = $block->getConfigData('specificcountry');
                            $arrcountry = explode(',', $shippingcountries);
                        foreach ($arrcountry as $country) {
                            $country_name=$block->getCountryNameByLocale($country);
                            ?>
                                <option value="<?= /* @noEscape */ $country; ?>">
                                <?= /* @noEscape */ $country_name; ?></option>
                            <?php }    ?>
                    </select>
                    <select name="ship[<%- data.index %>][3]" class="required-entry regionoption">
                        <option value="" selected="selected" disabled="disabled">
                        <?= /* @noEscape */ __('Select Region')?></option>
                        <?php	foreach ($regionArray['region'] as $region) {
                            $countryByRegion = $regionArray['countries'][$region['value']];
                            $regionCollection = $regionBlock->getRegionDataByRegionCode($region['value']);
                            $allowedCountries = $block->getAllowedCountriesFromCollection($regionCollection);
                            ?>
                            <option class="optionparent" value="<?= /* @noEscape */ $region['value']; ?>" >
                            <?= /* @noEscape */ $region['label']; ?></option>
                            <?php
                            foreach ($countryByRegion as $country) {
                                if (in_array($country['value'], $allowedCountries)) {
                                    ?>
                                    <option value="<?= /* @noEscape */ $region['value']; ?>" 
                                    class="optionchild" disabled> -<?= /* @noEscape */ $country['label']; ?></option>
                                    <?php
                                }
                            }
                            ?>                                                
                    <?php }    ?>
                    </select>
                </td>
                <td class="col cost" data-th="<?= /* @noEscape */ __('Shipping Cost') ?>">
                    <input type="text" name="ship[<%- data.index %>][4]" 
                    class="required-entry validate-zero-or-greater input-text">
                </td>
                <td class="col action" data-th="<?= /* @noEscape */ __('Action') ?>">
                    <button style="margin:0" class="button delete" title="<?= /* @noEscape */ __('Delete') ?>" 
                    type="button">
                        <span>
                            <span><%- data.button %></span>
                        </span>
                    </button>
                </td>        
            </tr>
        <?php else: ?>
            <tr class="wk-shipbody">
                <td class="col applyon" data-th="<?= /* @noEscape */ __('Select Apply on') ?>">
                    <select class="required-entry applyon" name="ship[<%- data.index %>][1]">
                        <option value="" disabled="disabled"><?= /* @noEscape */ __('Select Option')?></option>
                        <option selected="selected" value="R"><?= /* @noEscape */ __('Region') ?></option>
                        <option value="C"><?= /* @noEscape */ __('Country') ?></option>
                    </select>
                </td>
                <td class="col country-region" data-th="<?= /* @noEscape */ __('Select Country/Region') ?>">
                    <select style="display:none;" name="ship[<%- data.index %>][2]" 
                    class="country-select countryoption">
                        <option value="" selected="selected" disabled="disabled">
                        <?= /* @noEscape */ __('Select Country')?></option>
                        <?php $shippingcountries = $block->getCountryList();
                        foreach ($shippingcountries as $country) {
                            if ($country['value'] != ''):
                                ?>
                                <option value="<?= /* @noEscape */ $country['value']; ?>">
                                <?= /* @noEscape */ $country['label']; ?></option>
                                <?php
                                endif;
                        }    ?>
                    </select>
                    <select name="ship[<%- data.index %>][3]" class="required-entry regionoption">
                        <option value="" selected="selected" disabled="disabled">
                        <?= /* @noEscape */ __('Select Region')?></option>
                        <?php	foreach ($regionArray['region'] as $region) {
                            $countryByRegion = $regionArray['countries'][$region['value']];
                            $regionCollection = $regionBlock->getRegionDataByRegionCode($region['value']);
                            $allowedCountries = $block->getAllowedCountriesFromCollection($regionCollection);
                            ?>
                            <option class="optionparent" value="<?= /* @noEscape */ $region['value']; ?>" >
                            <?= /* @noEscape */ $region['label']; ?></option>
                            <?php
                            foreach ($countryByRegion as $country) {
                                if (in_array($country['value'], $allowedCountries)) {
                                    ?>
                                    <option value="<?= /* @noEscape */ $region['value']; ?>" 
                                    class="optionchild" disabled> -<?= /* @noEscape */ $country['label']; ?>
                                    </option>
                                    <?php
                                }
                            }
                            ?>                                                
                    <?php }    ?>
                    </select>
                </td>
                <td class="col cost" data-th="<?= /* @noEscape */ __('Shipping Cost') ?>">
                    <input type="text" name="ship[<%- data.index %>][4]" 
                    class="required-entry validate-zero-or-greater input-text">
                </td>
                <td class="col action" data-th="<?= /* @noEscape */ __('Action') ?>">
                    <button style="margin:0" title="<?= /* @noEscape */ __('Delete') ?>" 
                    class="button delete" type="button">
                        <span>
                            <span><%- data.button %></span>
                        </span>
                    </button>
                </td>        
            </tr>
        <?php endif; ?>
    </tbody>
    </script>
    <?php
        $data = [
            'count' => $count,
            'templateSelector'  => '#shipping-template',
            'addTemplateAfter'  => '.shippingprice .wk_mp_option-box #shipping_table',
            'topParentSelector' => '.shippingprice',
            'addShippingButton' => '.addshippingprice',
            'deleteButton'        => '.delete',
            'productSaveForm'   => '.wk-product-save-btn',
            'shippingCharge'    => '#mp_shipping_country_charge',
            'removeContent'     => '.wk_mp_headcus',
            'onCountrySelect'    => '.country-select',
            'mapDataSelector'   => '.wk-shipbody input,.wk-shipbody select',
        ];
        $serializedData = $productList->getHelperObject('jsonHelper')->jsonEncode($data);
        ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "addShippingPrice": <?= /* @noEscape */ /* @noEscape */ $serializedData; ?>
            }
        }
    </script>
<?php } ?>
