<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpFixedRateshipping
 * @author    Webkul
 * @copyright Copyright (c)  Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

?>
<?php if ($block->getConfigData('active')): ?>
    <form action="<?= /* @noEscape */ $block->getUrl('mpfixrate/shipping', ['_secure' =>
        $block->getRequest()->isSecure()]) ?>" method="post" id="form-validate"
        data-mage-init='{"validation":{}}'  data-hasrequired=
        "<?= /* @noEscape */ __('* Required Fields') ?>" autocomplete="off">
        <fieldset class="fieldset info">
            <legend class="legend"><span><?= /* @noEscape */ __('Fixed Rate Shipping Details') ?></span>
                <button type="submit" class="button wk-mp-btn action save primary">
                    <span><span><?= /* @noEscape */ __('Save') ?></span></span>
                </button>
            </legend><br>
            <?= /* @noEscape */ $block->getBlockHtml('formkey')?>
            <div class="field required">
            <?php if ($block->getConfigData('shippingappliedon') == 'vendor'): ?>
                <label class="label"><span><?= /* @noEscape */ __("Shipping Cost"); ?>:</span></label>
            <?php else: ?>
                <label class="label"><span><?= /* @noEscape */ __("Shipping Cost"); ?>:</span></label>
            <?php endif; ?>
            <div class="control">
                <div class="addon">
                    <?php
                        $price = $block->getHelperObject('pricingHelper')
                            ->currency($block->getCustomerData()->getMpshippingFixrate(), false, false);
                    ?>
                    <input id="mpshipping_fixrate" type="text" name="mpshipping_fixrate"
                        class="required validate-zero-or-greater" value="<?= /* @noEscape */
                        $block->getCustomerData()->getMpshippingFixrate()!=''?
                        $block->getCurrentyFormat($price):''; ?>" />
                    <label class="addbefore"for="price">
                        <strong><?= /* @noEscape */ $block->getHelper()->getCurrencySymbol();?></strong>
                    </label>
                </div>
            </div>
        </div>
        <div class="field required">
            <label class="label"><span><?= /* @noEscape */ __("Allow Free Shipping From Amount"); ?>:</span></label>
            <div class="control">
                <div class="addon">
                    <?php
                        $amount = $block->getHelperObject('pricingHelper')
                            ->currency($block->getCustomerData()
                            ->getMpshippingFixrateUpto(), false, false);
                    ?>
                    <input id="mpshipping_fixrate_upto" type="text" name="mpshipping_fixrate_upto"
                        class="required validate-zero-or-greater" value="<?= /* @noEscape */
                        $block->getCustomerData()->getMpshippingFixrate()!=''?
                        $block->getCurrentyFormat($amount):''; ?>" />

                    <label class="addbefore" for="price">
                        <strong><?= /* @noEscape */ $block->getHelper()->getCurrencySymbol();?></strong>
                    </label>
                </div>
            </div>
        </div>
        </fieldset>
    </form>
<?php endif; ?>
